/**
 * The playtest device protocol's message types, read from packages/playtest/src/three/device.ts
 * itself (BRIDGE_METHODS and every `input.*` operation dispatchInput accepts), as a C++ table the
 * native endpoint test walks (PRD-529). A method added to device.ts makes `--check` fail until the
 * table, and so the native endpoint, cover it.
 *
 *   pnpm --workspace-root exec tsx packages/runtime-native/tests/native-engine/inspect/protocol-methods.ts
 *   ... -- --check
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, "protocol_methods.inc");
const DEVICE = path.join(HERE, "../../../../playtest/src/three/device.ts");

const source = readFileSync(DEVICE, "utf8");
const bridgeBlock = /const BRIDGE_METHODS = new Set<[^>]*>\(\[([^\]]*)\]\)/u.exec(source)?.[1];
if (bridgeBlock === undefined)
  throw new Error("TN_PROTOCOL_SOURCE: BRIDGE_METHODS not found in device.ts");
const bridge = [...bridgeBlock.matchAll(/"([a-zA-Z]+)"/gu)].map((m) => m[1] as string);
const inputs = [
  ...new Set([...source.matchAll(/method === "(input\.[a-zA-Z]+)"/gu)].map((m) => m[1] as string)),
];
if (bridge.length === 0 || inputs.length === 0)
  throw new Error("TN_PROTOCOL_SOURCE: no methods found");

const methods = [...bridge, ...inputs].sort();
const text = [
  "// Generated by packages/runtime-native/tests/native-engine/inspect/protocol-methods.ts from",
  "// packages/playtest/src/three/device.ts. Do not edit: rerun the generator.",
  "static const char* const kMethods[] = {",
  ...methods.map((m) => `    ${JSON.stringify(m)},`),
  "};",
  "",
].join("\n");
if (process.argv.includes("--check")) {
  if (readFileSync(OUT, "utf8") !== text) {
    console.error("TN_FIXTURE_STALE: protocol_methods.inc is not device.ts's method set");
    process.exit(1);
  }
  console.log(`current: ${methods.length} methods`);
} else {
  writeFileSync(OUT, text);
  console.log(`wrote ${methods.length} methods: ${methods.join(", ")}`);
}
