// Generate one tiny native-css game project per fixture or interaction scenario.
//
// The project is the smallest thing that puts the subject's own tree and stylesheet in front of the
// real desktop host: `src/ui/Fixture.tsx` is the tree as React (same tags, same attributes, same
// order, same `data-n` numbering `shared.mjs` gives the Chromium page), `src/ui/fixture.css` is the
// oracle's `FONT + css` byte for byte, and `src/native.tsx` mounts it through `createCssUiRoot()`
// over a cube scene. It sits inside the example so its imports resolve from the workspace
// `node_modules` without an install of its own.
//
// Everything written here is build output: the projects live in the gitignored `corpus/out-desktop/`.
import { copyFileSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { FONT_FILES, IMAGE_FILES, fontDir, imageDir, number } from "./shared.mjs";

/** React spells two of the subject's attributes differently; the rest cross as written. */
const REACT_ATTR = { class: "className", tabindex: "tabIndex" };

/** One attribute as one JSX prop. `disabled=""` is the oracle's own HTML spelling. */
function prop(name, value) {
  const react = REACT_ATTR[name] ?? name;
  return value === "" ? react : `${react}={${JSON.stringify(value)}}`;
}

/** The tree as JSX: the oracle's numbering, the oracle's attributes, no extras. */
export function fixtureJsx(tree, listen = []) {
  const walk = (node, depth) => {
    const pad = "  ".repeat(depth);
    if (node.text !== undefined) return `${pad}{${JSON.stringify(node.text)}}`;
    const attrs = [`data-n={${node.n}}`];
    for (const [name, value] of Object.entries(node.attrs)) attrs.push(prop(name, value));
    if (listen.includes(node.n)) attrs.push(`onClick={() => onClick(${node.n})}`);
    if (node.children.length === 0) return `${pad}<${node.tag} ${attrs.join(" ")} />`;
    const body = node.children.map((child) => walk(child, depth + 1)).join("\n");
    return `${pad}<${node.tag} ${attrs.join(" ")}>\n${body}\n${pad}</${node.tag}>`;
  };
  return tree.map((node) => walk(node, 2)).join("\n");
}

/**
 * The fixture as a React component, generated from the same data the browser oracle renders.
 *
 * Every tag, attribute, text node and `data-n` is the oracle's, so a difference in the capture
 * cannot be a difference in what was asked for. `onClick` rides only the ids the scenario's
 * mutation protocol would have armed a listener on, which is what makes the click ledger
 * comparable with the oracle's. A fixture with several roots is a fragment: React appends its
 * children to the body root exactly as the oracle's HTML appends several siblings to `body`.
 */
function fixtureModule(jsx) {
  return `/**
 * GENERATED by corpus/project.mjs — do not edit. The tree is the corpus data the browser oracle
 * renders as HTML; the props below are the only difference between the two subjects.
 */
export function Fixture({ onClick }: { onClick?: (n: number) => void }): React.ReactElement {
  return (
    <>
${jsx}
    </>
  );
}
`;
}

/**
 * The scene every subject sits over: the example's cube game, with two fields added for the corpus —
 * a click ledger the playtest reads back, and the mounted flag that says the React tree committed
 * (so a run whose UI never attached cannot be read as a run that painted nothing).
 */
const GAME_TS = `import { type ICtx, Scene, defineGame } from "@threenative/core";
import { playtest } from "@threenative/core/playtest";
import { BoxGeometry, Color, Mesh, MeshStandardMaterial, PointLight } from "three";

/** What the playtest reads back: the click ledger, the mount, and the frame count. */
export type CorpusState = {
  clicks: string;
  frames: number;
  mounted: boolean;
};

declare global {
  var canvas: HTMLCanvasElement | undefined;
}

const hostCanvas = globalThis.canvas;

class Cube extends Scene<CorpusState> {
  static override readonly initialState: CorpusState = { clicks: "", frames: 0, mounted: false };

  override enter(ctx: ICtx<CorpusState>) {
    // The dark clear colour the browser reference page paints, so both targets agree on nothing here.
    ctx.scene.background = new Color(0x18181b);
    ctx.camera.position.set(2, 2, 3);
    ctx.camera.lookAt(0, 0, 0);
    const light = ctx.add(new PointLight(0xffffff, 40));
    light.position.set(4, 6, 8);
    const cube = ctx.add(new Mesh(new BoxGeometry(1, 1, 1), new MeshStandardMaterial()));
    return (frameCtx: ICtx<CorpusState>, dt: number) => {
      cube.rotation.x += dt * 0.6;
      cube.rotation.y += dt;
      frameCtx.state.set({ frames: frameCtx.state.getState().frames + 1 });
    };
  }
}

const game: ReturnType<typeof defineGame<CorpusState>> = defineGame<CorpusState>({
  canvas: hostCanvas,
  inputTarget: hostCanvas,
  plugins: [playtest()],
  scenes: { cube: Cube },
  start: "cube",
});

/** One click on a listened element, in order: "1,3,6" is the ledger the oracle also builds. */
export function noteClick(n: number): void {
  const state = game.state.getState();
  const ledger = state.clicks === "" ? String(n) : \`\${state.clicks},\${n}\`;
  game.state.set({ clicks: ledger });
  game.state.flush();
}

/** The UI committed: the mutation batch left the JS realm, which the host log then confirms. */
export function noteMounted(): void {
  game.state.set({ mounted: true });
  game.state.flush();
}

export default game;
`;

const CONFIG_TS = (
  name,
  [width, height],
) => `import type { IThreeNativeConfig } from "@threenative/core";

/**
 * GENERATED by corpus/project.mjs. The window is the subject's own size: the desktop host sizes its
 * surface from this config, and a capture at another size would not be this subject's frame.
 */
const config: IThreeNativeConfig = {
  app: {
    id: "com.threenative.corpus.${name.replaceAll(/-/gu, "")}",
    name: "tn-corpus-${name}",
    version: "1.0.0",
    build: 1,
  },
  display: {
    orientation: "landscape",
  },
  window: {
    width: ${width},
    height: ${height},
  },
  nativeEntry: "src/native.tsx",
  ui: { renderer: "native-css" },
};

export default config;
`;

const VITE_TS = `import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

/** GENERATED by corpus/project.mjs — the React plugin only: the sheet here is plain CSS. */
export default defineConfig({
  plugins: [react()],
});
`;

/**
 * The stylesheet entry the native build compiles to obtain the CSS the engine resolves. It imports
 * the sheet and nothing else: the browser reference for this corpus is `corpus/oracle.mjs`, which
 * renders the same bytes in Chromium, so this entry exists only to make Vite emit the stylesheet.
 */
const MAIN_TSX = `/**
 * GENERATED by corpus/project.mjs. The import below is the whole job: it is what makes the native
 * build emit the stylesheet the native CSS engine resolves.
 */
import "./fixture.css";

export {};
`;

const NATIVE_TSX = (clickArmed) => `import { createCssUiRoot } from "@threenative/core/react-css";
import game, { ${clickArmed ? "noteClick, noteMounted" : "noteMounted"} } from "./game.js";
import { Fixture } from "./ui/Fixture.js";

const root = createCssUiRoot();
root.render(<Fixture${clickArmed ? " onClick={noteClick}" : ""} />);
// The tree committed: the mutation batch left the JS realm. The host log then says whether it
// was accepted and painted.
noteMounted();

export default game;
`;

/**
 * Write one project under `dir`. `subject` is the fixture or the interaction scenario, `listen` the
 * ids its protocol arms a click listener on, and `scenario` the playtest the runner is given.
 */
export function writeProject(dir, subject, { fontCss, listen = [], scenario }) {
  rmSync(dir, { force: true, recursive: true });
  mkdirSync(join(dir, "src", "ui"), { recursive: true });
  number(subject.tree);
  writeFileSync(
    join(dir, "package.json"),
    `${JSON.stringify(
      {
        name: `tn-corpus-${subject.name.replaceAll(/-/gu, "")}`,
        version: "0.0.0",
        private: true,
        type: "module",
      },
      null,
      2,
    )}\n`,
  );
  writeFileSync(join(dir, "threenative.config.ts"), CONFIG_TS(subject.name, subject.size));
  writeFileSync(join(dir, "vite.config.ts"), VITE_TS);
  writeFileSync(join(dir, "src", "game.ts"), GAME_TS);
  writeFileSync(
    join(dir, "src", "ui", "Fixture.tsx"),
    fixtureModule(fixtureJsx(subject.tree, listen)),
  );
  writeFileSync(join(dir, "src", "ui", "main.tsx"), MAIN_TSX);
  // The oracle's bytes: FONT + the subject's own sheet, with the assets flat beside it so every
  // `url()` resolves as it does for the Chromium page and for the engine's one asset root.
  writeFileSync(join(dir, "src", "ui", "fixture.css"), `${fontCss}${subject.css}`);
  for (const font of FONT_FILES) {
    copyFileSync(join(fontDir, font), join(dir, "src", "ui", font));
  }
  for (const image of IMAGE_FILES) {
    copyFileSync(join(imageDir, image), join(dir, "src", "ui", image));
  }
  writeFileSync(join(dir, "src", "native.tsx"), NATIVE_TSX(listen.length > 0));
  writeFileSync(join(dir, "playtest.json"), `${JSON.stringify(scenario, null, 2)}\n`);
  return dir;
}
