import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { Document, NodeIO, type Primitive } from "@gltf-transform/core";
import { PNG } from "pngjs";

/**
 * Generates the deterministic skinned fixture model used to prove the model pass: skinned
 * (3 joints), animated (one rotation clip), multi-primitive (two primitives per mesh),
 * multi-material (two materials), textured (a base-colour map and a normal map), with
 * non-uniform node transforms and float32 joint weights. No such asset existed in the
 * repository — `native-proof.glb` is one flat static mesh — so the phase ships its own
 * hardest case (PRD-096).
 *
 * Tests build the document in memory through {@link buildFixtureDocument}; the one committed
 * `.glb` under `fixtures/` is regenerated by running this file as a script:
 *
 *     npx tsx test-support/generate-fixture-model.ts
 */

/** The committed copy of the generated model. */
export const FIXTURE_PATH = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "fixtures",
  "skinned-character.glb",
);

function checkerPng(size: number, cellsA: number[], cellsB: number[]): Buffer {
  const png = new PNG({ height: size, width: size });
  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      const cell = ((x >> 2) + (y >> 2)) % 2 === 0 ? cellsA : cellsB;
      const offset = (size * y + x) << 2;
      png.data[offset] = cell[0] ?? 0;
      png.data[offset + 1] = cell[1] ?? 0;
      png.data[offset + 2] = cell[2] ?? 0;
      png.data[offset + 3] = 255;
    }
  }
  return PNG.sync.write(png);
}

function normalMapPng(size: number): Buffer {
  // Flat tangent-space normals with a deterministic diagonal ridge: RGB encodes (x, y, z).
  const png = new PNG({ height: size, width: size });
  for (let y = 0; y < size; y += 1) {
    for (let x = 0; x < size; x += 1) {
      const slope = (x + y) % 8 === 0 ? 96 : 128;
      const offset = (size * y + x) << 2;
      png.data[offset] = slope;
      png.data[offset + 1] = slope;
      png.data[offset + 2] = 255;
      png.data[offset + 3] = 255;
    }
  }
  return PNG.sync.write(png);
}

function scalarAccessor(
  document: Document,
  buffer: ReturnType<Document["createBuffer"]>,
  name: string,
  array: ArrayBufferView,
): ReturnType<Document["createAccessor"]> {
  return document.createAccessor(name).setArray(array).setBuffer(buffer);
}

/**
 * Builds a flat indexed grid in the XZ plane bound between two joints: every vertex carries
 * JOINTS_0/WEIGHTS_0 blending it from the hips bone to the torso bone down its length.
 */
function gridPrimitive(
  document: Document,
  buffer: ReturnType<Document["createBuffer"]>,
  depth: number,
  width: number,
): Primitive {
  const positions: number[] = [];
  const normals: number[] = [];
  const uvs: number[] = [];
  const joints0: number[] = [];
  const weights0: number[] = [];
  const indices: number[] = [];
  for (let row = 0; row <= depth; row += 1) {
    for (let column = 0; column <= width; column += 1) {
      const u = column / width;
      const v = row / depth;
      positions.push((u - 0.5) * 0.6, 0.02 * Math.sin(u * Math.PI), (v - 0.5) * 0.9);
      normals.push(0, 1, 0);
      uvs.push(u, v);
      joints0.push(0, 1, 0, 0);
      weights0.push(1 - v, v, 0, 0);
    }
  }
  for (let row = 0; row < depth; row += 1) {
    for (let column = 0; column < width; column += 1) {
      const a = row * (width + 1) + column;
      indices.push(a, a + width + 1, a + 1, a + 1, a + width + 1, a + width + 2);
    }
  }
  const primitive = document.createPrimitive();
  primitive.setIndices(
    scalarAccessor(document, buffer, "cloth-indices", new Uint32Array(indices)).setType("SCALAR"),
  );
  primitive.setAttribute(
    "POSITION",
    scalarAccessor(document, buffer, "cloth-positions", new Float32Array(positions)).setType(
      "VEC3",
    ),
  );
  primitive.setAttribute(
    "NORMAL",
    scalarAccessor(document, buffer, "cloth-normals", new Float32Array(normals)).setType("VEC3"),
  );
  primitive.setAttribute(
    "TEXCOORD_0",
    scalarAccessor(document, buffer, "cloth-uvs", new Float32Array(uvs)).setType("VEC2"),
  );
  primitive.setAttribute(
    "JOINTS_0",
    scalarAccessor(document, buffer, "cloth-joints", new Uint8Array(joints0)).setType("VEC4"),
  );
  primitive.setAttribute(
    "WEIGHTS_0",
    scalarAccessor(document, buffer, "cloth-weights", new Float32Array(weights0)).setType("VEC4"),
  );
  return primitive;
}

/** A six-vertex octahedron bound entirely to the head joint (index 2). */
function headPrimitive(
  document: Document,
  buffer: ReturnType<Document["createBuffer"]>,
): Primitive {
  const positions = [
    0, 0.14, 0, 0.08, 0.07, 0, 0, 0.07, 0.08, -0.08, 0.07, 0, 0, 0.07, -0.08, 0, 0, -0.08,
  ];
  const indices = [0, 2, 1, 0, 3, 2, 0, 4, 3, 0, 1, 4, 5, 1, 2, 5, 2, 3, 5, 3, 4, 5, 4, 1];
  const joints0 = new Array<number>(6 * 4).fill(0).map((_, index) => (index % 4 === 0 ? 2 : 0));
  const weights0 = new Array<number>(6 * 4).fill(0).map((_, index) => (index % 4 === 0 ? 1 : 0));
  const primitive = document.createPrimitive();
  primitive.setIndices(
    scalarAccessor(document, buffer, "head-indices", new Uint16Array(indices)).setType("SCALAR"),
  );
  primitive.setAttribute(
    "POSITION",
    scalarAccessor(document, buffer, "head-positions", new Float32Array(positions)).setType("VEC3"),
  );
  primitive.setAttribute(
    "JOINTS_0",
    scalarAccessor(document, buffer, "head-joints", new Uint8Array(joints0)).setType("VEC4"),
  );
  primitive.setAttribute(
    "WEIGHTS_0",
    scalarAccessor(document, buffer, "head-weights", new Float32Array(weights0)).setType("VEC4"),
  );
  return primitive;
}

function identityBind(translation: number[]): number[] {
  const [x = 0, y = 0, z = 0] = translation;
  return [1, 0, 0, x, 0, 1, 0, y, 0, 0, 1, z, 0, 0, 0, 1];
}

export interface IFixtureOptions {
  /** Grid subdivisions of the cloth primitive; defaults reproduce the committed fixture. */
  readonly gridDepth?: number;
  readonly gridWidth?: number;
  /**
   * Embeds the base-colour and normal-map textures (default true). Bare-node tests that
   * parse through GLTFLoader pass false — image decoding has no browser surface there.
   */
  readonly textured?: boolean;
}

export function buildFixtureDocument(options: IFixtureOptions = {}): Document {
  const document = new Document();
  document.getRoot().getAsset().generator = "threenative-fixture-generator";
  const buffer = document.createBuffer("fixture");

  const textured = options.textured ?? true;
  let cloth = document.createMaterial("cloth").setBaseColorFactor([0.78, 0.16, 0.24, 1]);
  if (textured) {
    const checker = document
      .createTexture("checker")
      .setImage(checkerPng(32, [200, 40, 60], [30, 90, 160]))
      .setMimeType("image/png");
    const normalMap = document
      .createTexture("cloth-normal")
      .setImage(normalMapPng(32))
      .setMimeType("image/png");
    cloth = cloth.setBaseColorTexture(checker).setNormalTexture(normalMap);
  }
  const skinMaterial = document.createMaterial("skin").setBaseColorFactor([0.9, 0.75, 0.6, 1]);

  const mesh = document.createMesh("character");
  mesh.addPrimitive(
    gridPrimitive(document, buffer, options.gridDepth ?? 3, options.gridWidth ?? 2).setMaterial(
      cloth,
    ),
  );
  mesh.addPrimitive(headPrimitive(document, buffer).setMaterial(skinMaterial));

  const hips = document.createNode("hips").setTranslation([0, 0, 0]);
  const torso = document.createNode("torso").setTranslation([0, 0.35, 0]);
  const head = document.createNode("head").setTranslation([0, 0.4, 0]);
  torso.addChild(head);
  hips.addChild(torso);

  const root = document
    .createNode("character-root")
    .setTranslation([0, 0.55, 0])
    .setScale([1.05, 1, 1]); // Non-uniform transform on purpose.
  root.addChild(hips);

  const scene = document.createScene("CharacterScene");
  scene.addChild(root);

  // Inverse bind matrices: identity rotations, each joint's bind-pose translation.
  const skin = document
    .createSkin("character-skin")
    .addJoint(hips)
    .addJoint(torso)
    .addJoint(head)
    .setInverseBindMatrices(
      scalarAccessor(
        document,
        buffer,
        "inverse-binds",
        new Float32Array([
          ...identityBind([0, 0, 0]),
          ...identityBind([0, 0.35, 0]),
          ...identityBind([0, 0.75, 0]),
        ]),
      ).setType("MAT4"),
    );
  hips.setSkin(skin);
  hips.setMesh(mesh);

  // One rotation clip waving the head bone; the pipeline compresses but never resamples it.
  const animation = document.createAnimation("wave");
  const sampler = document
    .createAnimationSampler("wave-sampler")
    .setInput(
      scalarAccessor(document, buffer, "wave-times", new Float32Array([0, 0.5, 1])).setType(
        "SCALAR",
      ),
    )
    .setOutput(
      scalarAccessor(
        document,
        buffer,
        "wave-rotations",
        new Float32Array([0, 0, 0, 1, 0, 0.25881904510252074, 0, 0.9659258262890683, 0, 0, 0, 1]),
      ).setType("VEC4"),
    )
    .setInterpolation("LINEAR");
  const channel = document
    .createAnimationChannel("wave-channel")
    .setSampler(sampler)
    .setTargetNode(head)
    .setTargetPath("rotation");
  animation.addSampler(sampler).addChannel(channel);

  return document;
}

/** Serializes the fixture to a plain `.glb` with no extensions declared. */
export async function buildFixtureGlb(options: IFixtureOptions = {}): Promise<Uint8Array> {
  const io = new NodeIO();
  return io.writeBinary(buildFixtureDocument(options));
}

const invokedDirectly =
  process.argv[1] !== undefined && pathToFileURL(resolve(process.argv[1])).href === import.meta.url;

if (invokedDirectly) {
  const target = process.argv[2] ?? FIXTURE_PATH;
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, await buildFixtureGlb());
  console.log(`wrote ${target}`);
}
