import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import path from "node:path";
import { buildAnimalData, clearBuildCache, writeBake } from "procedural-animals";
import wolf from "procedural-animals/species/wolf";
import {
  ANIMAL_ADAPTER_VERSION,
  ANIMAL_DONOR_REVISION,
  animalError,
  bakeIntegrity,
  parseAnimalBake,
} from "./format.js";
import type { AnimalTier } from "./format.js";

export const ANIMAL_BUILD_NODE = "20.19.6";
export interface IWolfBakeOptions {
  readonly seed: number;
  readonly tier: AnimalTier;
  readonly sex?: "male" | "female";
  readonly age?: "adult" | "juvenile";
  readonly variant?: "grey" | "black" | "pale" | "tawny";
}

const donorRoot = path.dirname(
  createRequire(import.meta.url).resolve("procedural-animals/package.json"),
);
const digest = (bytes: string | Uint8Array) => createHash("sha256").update(bytes).digest("hex");

function normalized(options: IWolfBakeOptions): IWolfBakeOptions {
  if (process.versions.node !== ANIMAL_BUILD_NODE)
    throw animalError(
      "BUILD_RUNTIME",
      `baking requires Node ${ANIMAL_BUILD_NODE}; found ${process.versions.node}`,
    );
  if (!options || typeof options !== "object" || Array.isArray(options))
    throw animalError("OPTIONS", "wolf options must be an object");
  for (const key of Object.keys(options))
    if (!["seed", "tier", "sex", "age", "variant"].includes(key))
      throw animalError("OPTIONS", `unknown wolf option ${key}`);
  if (!Number.isSafeInteger(options.seed) || options.seed < 0 || options.seed > 0xffff_ffff)
    throw animalError("OPTIONS", "seed must be an unsigned 32-bit integer");
  if (options.tier !== "high" && options.tier !== "crowd")
    throw animalError("OPTIONS", "tier must be high or crowd");
  for (const [key, allowed] of [
    ["sex", ["male", "female"]],
    ["age", ["adult", "juvenile"]],
    ["variant", ["grey", "black", "pale", "tawny"]],
  ] as const) {
    const value = options[key];
    if (value !== undefined && !(allowed as readonly string[]).includes(value))
      throw animalError("OPTIONS", `unsupported ${key}`);
  }
  return {
    seed: options.seed,
    tier: options.tier,
    sex: options.sex,
    age: options.age,
    variant: options.variant,
  };
}

/**
 * Bake the pinned wolf on the build machine, never on the portable runtime path.
 * @situation bake high and crowd wolf geometry before the ordinary asset cook
 * @constraint exact pinned Node runtime, donor revision, options and generated bytes are validated; no worker is created
 * @requires npm i @threenative/procedural-animals
 * @example const bytes = await bakeWolf({ seed: 7, tier: "crowd" });
 */
export async function bakeWolf(options: IWolfBakeOptions): Promise<ArrayBuffer> {
  const o = normalized(options);
  const definitionHash = digest(await readFile(path.join(donorRoot, "src/species/wolf/index.js")));
  const cacheKey = digest(
    JSON.stringify({
      donor: ANIMAL_DONOR_REVISION,
      adapter: ANIMAL_ADAPTER_VERSION,
      runtime: `node-v${ANIMAL_BUILD_NODE}`,
      definitionHash,
      species: "wolf",
      options: o,
    }),
  );
  // Every proof call really generates; donor's in-memory cache cannot stand in for repeatability.
  clearBuildCache();
  const generated: Record<string, unknown> = await buildAnimalData(wolf, {
    seed: o.seed,
    quality: o.tier,
    sex: o.sex,
    age: o.age,
    variant: o.variant,
    worker: false,
  });
  const stats = { ...(generated.stats as Record<string, unknown>) };
  for (const key of ["weightsMs", "coatMs", "buildMs"]) delete stats[key];
  const metadata = {
    donorRevision: ANIMAL_DONOR_REVISION,
    adapterVersion: ANIMAL_ADAPTER_VERSION,
    buildRuntime: `node-v${ANIMAL_BUILD_NODE}`,
    cacheKey,
  };
  const data = { ...generated, stats, threenative: metadata };
  const integrity = bakeIntegrity(writeBake(data));
  const bytes = writeBake({ ...data, threenative: { ...metadata, integrity } });
  const bake = parseAnimalBake(bytes);
  if (bake.quality === "crowd" && (bake.nV > 8_000 || bake.bones.length > 128))
    throw animalError("CROWD_LIMIT", `wolf has ${bake.nV} vertices/${bake.bones.length} bones`);
  return bytes;
}

/**
 * Stage a validated source bake with a same-directory atomic rename, then use compileAssets.
 * @situation publish a generated wolf without replacing the last valid bake on interruption
 * @constraint validation and generation complete before the destination is touched; temporary files are removed on failure
 * @requires npm i @threenative/procedural-animals
 * @example await bakeWolfToFile({ seed: 7, tier: "crowd" }, "assets/wolf-crowd.animal");
 */
export async function bakeWolfToFile(
  options: IWolfBakeOptions,
  destination: string,
): Promise<string> {
  if (!destination.endsWith(".animal"))
    throw animalError("OPTIONS", "destination must end in .animal");
  const bytes = await bakeWolf(options);
  await mkdir(path.dirname(destination), { recursive: true });
  const temporary = `${destination}.${process.pid}.${randomUUID()}.tmp`;
  try {
    await writeFile(temporary, new Uint8Array(bytes), { flag: "wx" });
    await rename(temporary, destination);
  } finally {
    await rm(temporary, { force: true });
  }
  return digest(new Uint8Array(bytes));
}

/**
 * Validate staged PANM sources inside the existing asset compiler; it owns the hashed manifest.
 * @situation cook staged animal bakes through the ordinary asset pipeline
 * @constraint only .animal inputs are interpreted; corruption fails the cook, without regeneration
 * @requires npm i @threenative/procedural-animals
 * @example await compileAssets({ passes: [animalBakePass()] });
 */
export function animalBakePass() {
  return {
    name: "animal-bake",
    appliesTo: ["other"] as const,
    cacheKey: `${ANIMAL_DONOR_REVISION}:${ANIMAL_ADAPTER_VERSION}:node-v${ANIMAL_BUILD_NODE}`,
    apply(input: Buffer, logicalPath: string) {
      if (!logicalPath.endsWith(".animal")) return input;
      const bake = parseAnimalBake(Uint8Array.from(input).buffer);
      return {
        buffer: input,
        entry: {
          animal: {
            species: bake.species,
            seed: bake.seed,
            tier: bake.quality,
            vertices: bake.nV,
            bones: bake.bones.length,
            sha256: digest(input),
          },
        },
      };
    },
  };
}
