export const STANDALONE_PLAYTEST_OBSERVATION_FIELDS = [
  "components",
  "componentSeries",
  "console",
  "framebufferCoverage",
  "hud",
  "network",
  "physicsDebugSeries",
  "performanceSeries",
  "resources",
  "resourceSeries",
  "runtimeDiagnostics",
  "runtimeObservations",
  "signals",
  "signalSeries",
  "visual",
] as const;
