// Single owner of the core version (PRD-181): package.json is the source of truth and
// src/version.ts is generated from it and checked in. A hand-edited constant goes stale the
// moment the manifest bumps; the pinning spec turns that red.
import { readFile, writeFile } from "node:fs/promises";

const manifest = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
if (typeof manifest.version !== "string" || manifest.version.length === 0) {
  throw new Error("generate-version: package.json has no version");
}
await writeFile(
  new URL("../src/version.ts", import.meta.url),
  `// Generated by scripts/generate-version.mjs - do not edit. Source: package.json.\nexport const CORE_VERSION = ${JSON.stringify(manifest.version)};\n`,
);
