/* Generated by scripts/generate-assertion-validators.ts — do not hand-edit. */

import { invalidScenario } from "./errors.js";
import type { IPlaytestScenarioAssertions } from "./schema-base.js";

type IGeneratedPrimitive = string | number | boolean | null;
type IGeneratedRule =
  | { fields: readonly string[]; kind: "requireOneOf"; message?: string }
  | { equals: IGeneratedPrimitive; field: string; kind: "requireWhen"; message?: string; required: string }
  | { field: string; kind: "nonEmptyArray"; message?: string }
  | { field: string; kind: "noConsecutiveDuplicates"; message?: string }
  | { fields: readonly string[]; kind: "requireOneOfOrTrue"; message?: string; trueFields: readonly string[] };
type IGeneratedConstraint =
  | { kind: "boolean" }
  | { integer?: boolean; kind: "number"; max?: number; min?: number; minExclusive?: boolean }
  | { format?: "project-relative-png"; kind: "string"; minNonWhitespace?: number; nonEmpty?: boolean }
  | { kind: "json" }
  | { items: IGeneratedConstraint; kind: "array"; maxItems?: number; minItems?: number }
  | { items: readonly IGeneratedConstraint[]; kind: "tuple" }
  | { fields: readonly IGeneratedField[]; kind: "record"; rules?: readonly IGeneratedRule[]; unknownKeys?: "allow" | "reject" }
  | { kind: "literal"; values: readonly IGeneratedPrimitive[] }
  | { discriminator?: { field: string; presentVariant: number }; kind: "union"; variants: readonly IGeneratedConstraint[] };
type IGeneratedField = { constraints: IGeneratedConstraint; name: string; required: boolean; type: string };
type IGeneratedEntry = { cardinality: "array" | "object"; kind: keyof IPlaytestScenarioAssertions; minItems?: number; minItemsMessage?: string; schema: IGeneratedConstraint };

export const GENERATED_ASSERTION_SCHEMAS: readonly IGeneratedEntry[] = [
  {
    "cardinality": "object",
    "kind": "framebufferCoverage",
    "schema": {
      "fields": [
        {
          "constraints": {
            "items": [
              {
                "integer": true,
                "max": 255,
                "min": 0,
                "kind": "number"
              },
              {
                "integer": true,
                "max": 255,
                "min": 0,
                "kind": "number"
              },
              {
                "integer": true,
                "max": 255,
                "min": 0,
                "kind": "number"
              }
            ],
            "kind": "tuple"
          },
          "name": "backdrop",
          "required": true,
          "type": "[integer 0..255, integer 0..255, integer 0..255]"
        },
        {
          "constraints": {
            "fields": [
              {
                "constraints": {
                  "integer": true,
                  "max": 256,
                  "min": 1,
                  "kind": "number"
                },
                "name": "columns",
                "required": true,
                "type": "positive integer <= 256"
              },
              {
                "constraints": {
                  "integer": true,
                  "max": 256,
                  "min": 1,
                  "kind": "number"
                },
                "name": "rows",
                "required": true,
                "type": "positive integer <= 256"
              }
            ],
            "unknownKeys": "reject",
            "kind": "record"
          },
          "name": "grid",
          "required": false,
          "type": "{ columns: positive integer <= 256, rows: positive integer <= 256 }"
        },
        {
          "constraints": {
            "integer": true,
            "max": 255,
            "min": 0,
            "kind": "number"
          },
          "name": "tolerance",
          "required": true,
          "type": "integer 0..255"
        },
        {
          "constraints": {
            "fields": [
              {
                "constraints": {
                  "nonEmpty": true,
                  "kind": "string"
                },
                "name": "startStep",
                "required": true,
                "type": "string"
              },
              {
                "constraints": {
                  "nonEmpty": true,
                  "kind": "string"
                },
                "name": "endStep",
                "required": true,
                "type": "string"
              }
            ],
            "unknownKeys": "reject",
            "kind": "record"
          },
          "name": "window",
          "required": true,
          "type": "{ startStep: string, endStep: string }"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "object",
    "kind": "reachability",
    "schema": {
      "fields": [
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "artifact",
          "required": true,
          "type": "string"
        },
        {
          "constraints": {
            "minItems": 2,
            "items": {
              "nonEmpty": true,
              "kind": "string"
            },
            "kind": "array"
          },
          "name": "entities",
          "required": true,
          "type": "string[] (minimum 2)"
        }
      ],
      "rules": [
        {
          "field": "entities",
          "kind": "noConsecutiveDuplicates",
          "message": "Assertion 'assert.reachability.entities' must not repeat a consecutive entity id."
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "array",
    "kind": "aerodynamics",
    "schema": {
      "fields": [
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "entity",
          "required": true,
          "type": "string"
        },
        {
          "constraints": {
            "integer": true,
            "min": 1,
            "kind": "number"
          },
          "name": "minForceSamples",
          "required": false,
          "type": "positive integer"
        },
        {
          "constraints": {
            "items": {
              "fields": [
                {
                  "constraints": {
                    "nonEmpty": true,
                    "kind": "string"
                  },
                  "name": "surface",
                  "required": true,
                  "type": "string"
                },
                {
                  "constraints": {
                    "values": [
                      "negative",
                      "positive"
                    ],
                    "kind": "literal"
                  },
                  "name": "sign",
                  "required": true,
                  "type": "'negative' | 'positive'"
                },
                {
                  "constraints": {
                    "min": 0,
                    "kind": "number"
                  },
                  "name": "minAbs",
                  "required": false,
                  "type": "number"
                }
              ],
              "unknownKeys": "reject",
              "kind": "record"
            },
            "kind": "array"
          },
          "name": "controls",
          "required": false,
          "type": "Array<{ surface: string, sign: 'negative' | 'positive', minAbs?: number }>"
        },
        {
          "constraints": {
            "items": {
              "fields": [
                {
                  "constraints": {
                    "nonEmpty": true,
                    "kind": "string"
                  },
                  "name": "label",
                  "required": true,
                  "type": "string"
                },
                {
                  "constraints": {
                    "nonEmpty": true,
                    "kind": "string"
                  },
                  "name": "relativeToLabel",
                  "required": false,
                  "type": "string"
                },
                {
                  "constraints": {
                    "values": [
                      "x",
                      "y",
                      "z"
                    ],
                    "kind": "literal"
                  },
                  "name": "axis",
                  "required": true,
                  "type": "'x' | 'y' | 'z'"
                },
                {
                  "constraints": {
                    "values": [
                      "negative",
                      "positive"
                    ],
                    "kind": "literal"
                  },
                  "name": "sign",
                  "required": true,
                  "type": "'negative' | 'positive'"
                },
                {
                  "constraints": {
                    "min": 0,
                    "kind": "number"
                  },
                  "name": "minAbs",
                  "required": false,
                  "type": "number"
                }
              ],
              "unknownKeys": "reject",
              "kind": "record"
            },
            "kind": "array"
          },
          "name": "torques",
          "required": false,
          "type": "Array<{ label: string, relativeToLabel?: string, axis: 'x' | 'y' | 'z', sign: 'negative' | 'positive', minAbs?: number }>"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "array",
    "kind": "visual",
    "schema": {
      "fields": [
        {
          "constraints": {
            "fields": [
              {
                "constraints": {
                  "format": "project-relative-png",
                  "nonEmpty": true,
                  "kind": "string"
                },
                "name": "baselineImage",
                "required": false,
                "type": "project-relative PNG"
              },
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "minChangedPixelRatio",
                "required": false,
                "type": "number"
              },
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "maxChangedPixelRatio",
                "required": false,
                "type": "number"
              }
            ],
            "unknownKeys": "reject",
            "kind": "record"
          },
          "name": "frameDiff",
          "required": false,
          "type": "{ baselineImage?: project-relative PNG, minChangedPixelRatio?: number, maxChangedPixelRatio?: number }"
        },
        {
          "constraints": {
            "fields": [
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "x",
                "required": true,
                "type": "number"
              },
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "y",
                "required": true,
                "type": "number"
              },
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "width",
                "required": true,
                "type": "number"
              },
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "height",
                "required": true,
                "type": "number"
              },
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "minNonblankPixelRatio",
                "required": false,
                "type": "number"
              },
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "minDarkPixelRatio",
                "required": false,
                "type": "number"
              },
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "maxLuminance",
                "required": false,
                "type": "number"
              }
            ],
            "unknownKeys": "reject",
            "kind": "record"
          },
          "name": "region",
          "required": false,
          "type": "{ x: number, y: number, width: number, height: number, minNonblankPixelRatio?: number, minDarkPixelRatio?: number, maxLuminance?: number }"
        },
        {
          "constraints": {
            "fields": [
              {
                "constraints": {
                  "nonEmpty": true,
                  "kind": "string"
                },
                "name": "entity",
                "required": true,
                "type": "string"
              },
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "minProjectedPixels",
                "required": true,
                "type": "number"
              },
              {
                "constraints": {
                  "kind": "boolean"
                },
                "name": "throughoutFrames",
                "required": false,
                "type": "boolean"
              }
            ],
            "unknownKeys": "reject",
            "kind": "record"
          },
          "name": "entityVisible",
          "required": false,
          "type": "{ entity: string, minProjectedPixels: number, throughoutFrames?: boolean }"
        }
      ],
      "rules": [
        {
          "fields": [
            "entityVisible",
            "frameDiff",
            "region"
          ],
          "kind": "requireOneOf",
          "message": "must declare 'entityVisible', 'frameDiff', or 'region'; an empty visual assertion evaluates nothing."
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "object",
    "kind": "movement",
    "schema": {
      "fields": [
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "entity",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "fields": [
              {
                "constraints": {
                  "items": [
                    {
                      "kind": "number"
                    },
                    {
                      "kind": "number"
                    },
                    {
                      "kind": "number"
                    }
                  ],
                  "kind": "tuple"
                },
                "name": "position",
                "required": true,
                "type": "[number, number, number]"
              },
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "min",
                "required": true,
                "type": "number"
              }
            ],
            "unknownKeys": "reject",
            "kind": "record"
          },
          "name": "closesDistanceToPosition",
          "required": false,
          "type": "{ position: [number, number, number], min: number }"
        },
        {
          "constraints": {
            "kind": "number"
          },
          "name": "facesMovementWithinDegrees",
          "required": false,
          "type": "number"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "axis",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "fields": [
              {
                "constraints": {
                  "nonEmpty": true,
                  "kind": "string"
                },
                "name": "axis",
                "required": true,
                "type": "string"
              },
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "min",
                "required": true,
                "type": "number"
              }
            ],
            "unknownKeys": "reject",
            "kind": "record"
          },
          "name": "minAxisDelta",
          "required": false,
          "type": "{ axis: string, min: number }"
        },
        {
          "constraints": {
            "fields": [
              {
                "constraints": {
                  "nonEmpty": true,
                  "kind": "string"
                },
                "name": "axis",
                "required": true,
                "type": "string"
              },
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "min",
                "required": true,
                "type": "number"
              }
            ],
            "unknownKeys": "reject",
            "kind": "record"
          },
          "name": "minResolvedAxisDelta",
          "required": false,
          "type": "{ axis: string, min: number }"
        },
        {
          "constraints": {
            "max": 180,
            "min": 0,
            "kind": "number"
          },
          "name": "maxTiltDegrees",
          "required": false,
          "type": "number in [0, 180]"
        },
        {
          "constraints": {
            "kind": "number"
          },
          "name": "minDistance",
          "required": false,
          "type": "number"
        },
        {
          "constraints": {
            "integer": true,
            "min": 1,
            "kind": "number"
          },
          "name": "minTicks",
          "required": false,
          "type": "positive integer"
        },
        {
          "constraints": {
            "kind": "number"
          },
          "name": "maxDistance",
          "required": false,
          "type": "number"
        },
        {
          "constraints": {
            "kind": "number"
          },
          "name": "minVelocity",
          "required": false,
          "type": "number"
        },
        {
          "constraints": {
            "kind": "number"
          },
          "name": "pathLength",
          "required": false,
          "type": "number"
        },
        {
          "constraints": {
            "fields": [
              {
                "constraints": {
                  "nonEmpty": true,
                  "kind": "string"
                },
                "name": "entity",
                "required": true,
                "type": "string"
              },
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "minDegrees",
                "required": true,
                "type": "number"
              }
            ],
            "unknownKeys": "reject",
            "kind": "record"
          },
          "name": "notFacing",
          "required": false,
          "type": "{ entity: string, minDegrees: number }"
        },
        {
          "constraints": {
            "fields": [
              {
                "constraints": {
                  "items": [
                    {
                      "kind": "number"
                    },
                    {
                      "kind": "number"
                    },
                    {
                      "kind": "number"
                    }
                  ],
                  "kind": "tuple"
                },
                "name": "position",
                "required": true,
                "type": "[number, number, number]"
              },
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "minDegrees",
                "required": true,
                "type": "number"
              }
            ],
            "unknownKeys": "reject",
            "kind": "record"
          },
          "name": "notFacingPosition",
          "required": false,
          "type": "{ position: [number, number, number], minDegrees: number }"
        },
        {
          "constraints": {
            "fields": [
              {
                "constraints": {
                  "items": [
                    {
                      "kind": "number"
                    },
                    {
                      "kind": "number"
                    },
                    {
                      "kind": "number"
                    }
                  ],
                  "kind": "tuple"
                },
                "name": "position",
                "required": true,
                "type": "[number, number, number]"
              },
              {
                "constraints": {
                  "kind": "number"
                },
                "name": "maxDistance",
                "required": true,
                "type": "number"
              },
              {
                "constraints": {
                  "nonEmpty": true,
                  "kind": "string"
                },
                "name": "atStep",
                "required": false,
                "type": "string"
              }
            ],
            "unknownKeys": "reject",
            "kind": "record"
          },
          "name": "reachesPositionWithin",
          "required": false,
          "type": "{ position: [number, number, number], maxDistance: number, atStep?: string }"
        },
        {
          "constraints": {
            "kind": "boolean"
          },
          "name": "rotationChanged",
          "required": false,
          "type": "boolean"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "object",
    "kind": "camera",
    "schema": {
      "fields": [
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "entity",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "follows",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "kind": "number"
          },
          "name": "within",
          "required": false,
          "type": "number"
        },
        {
          "constraints": {
            "kind": "boolean"
          },
          "name": "targetInViewport",
          "required": false,
          "type": "boolean"
        }
      ],
      "rules": [
        {
          "fields": [
            "within"
          ],
          "kind": "requireOneOfOrTrue",
          "message": "must declare 'within' or 'targetInViewport: true'; a camera assertion with neither passes without consulting any observation.",
          "trueFields": [
            "targetInViewport"
          ]
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "array",
    "kind": "components",
    "schema": {
      "fields": [
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "entity",
          "required": true,
          "type": "string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "component",
          "required": true,
          "type": "string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "path",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "kind": "json"
          },
          "name": "equals",
          "required": false,
          "type": "json"
        },
        {
          "constraints": {
            "kind": "number"
          },
          "name": "gte",
          "required": false,
          "type": "number"
        },
        {
          "constraints": {
            "kind": "number"
          },
          "name": "lte",
          "required": false,
          "type": "number"
        },
        {
          "constraints": {
            "kind": "boolean"
          },
          "name": "changed",
          "required": false,
          "type": "boolean"
        },
        {
          "constraints": {
            "items": {
              "fields": [
                {
                  "constraints": {
                    "nonEmpty": true,
                    "kind": "string"
                  },
                  "name": "label",
                  "required": true,
                  "type": "string"
                },
                {
                  "constraints": {
                    "kind": "json"
                  },
                  "name": "equals",
                  "required": true,
                  "type": "json"
                }
              ],
              "unknownKeys": "reject",
              "kind": "record"
            },
            "kind": "array"
          },
          "name": "atSteps",
          "required": false,
          "type": "Array<{ label: string, equals: json }>"
        },
        {
          "constraints": {
            "minNonWhitespace": 20,
            "kind": "string"
          },
          "name": "allowTrivial",
          "required": false,
          "type": "triviality reason"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "array",
    "kind": "resources",
    "schema": {
      "discriminator": {
        "field": "anyOf",
        "presentVariant": 0
      },
      "kind": "union",
      "variants": [
        {
          "fields": [
            {
              "constraints": {
                "nonEmpty": true,
                "kind": "string"
              },
              "name": "id",
              "required": true,
              "type": "string"
            },
            {
              "constraints": {
                "items": {
                  "fields": [
                    {
                      "constraints": {
                        "nonEmpty": true,
                        "kind": "string"
                      },
                      "name": "path",
                      "required": true,
                      "type": "string"
                    },
                    {
                      "constraints": {
                        "kind": "json"
                      },
                      "name": "equals",
                      "required": false,
                      "type": "json"
                    },
                    {
                      "constraints": {
                        "kind": "number"
                      },
                      "name": "gte",
                      "required": false,
                      "type": "number"
                    },
                    {
                      "constraints": {
                        "kind": "number"
                      },
                      "name": "lte",
                      "required": false,
                      "type": "number"
                    },
                    {
                      "constraints": {
                        "nonEmpty": true,
                        "kind": "string"
                      },
                      "name": "textIncludes",
                      "required": false,
                      "type": "string"
                    },
                    {
                      "constraints": {
                        "kind": "boolean"
                      },
                      "name": "changed",
                      "required": false,
                      "type": "boolean"
                    }
                  ],
                  "unknownKeys": "reject",
                  "kind": "record"
                },
                "kind": "array"
              },
              "name": "anyOf",
              "required": true,
              "type": "Array<{ path: string, equals?: json, gte?: number, lte?: number, textIncludes?: string, changed?: boolean }>"
            }
          ],
          "unknownKeys": "reject",
          "kind": "record"
        },
        {
          "fields": [
            {
              "constraints": {
                "nonEmpty": true,
                "kind": "string"
              },
              "name": "id",
              "required": true,
              "type": "string"
            },
            {
              "constraints": {
                "nonEmpty": true,
                "kind": "string"
              },
              "name": "path",
              "required": false,
              "type": "string"
            },
            {
              "constraints": {
                "kind": "json"
              },
              "name": "equals",
              "required": false,
              "type": "json"
            },
            {
              "constraints": {
                "kind": "number"
              },
              "name": "gte",
              "required": false,
              "type": "number"
            },
            {
              "constraints": {
                "kind": "number"
              },
              "name": "lte",
              "required": false,
              "type": "number"
            },
            {
              "constraints": {
                "nonEmpty": true,
                "kind": "string"
              },
              "name": "textIncludes",
              "required": false,
              "type": "string"
            },
            {
              "constraints": {
                "kind": "boolean"
              },
              "name": "changed",
              "required": false,
              "type": "boolean"
            },
            {
              "constraints": {
                "kind": "boolean"
              },
              "name": "throughoutSteps",
              "required": false,
              "type": "boolean"
            },
            {
              "constraints": {
                "items": {
                  "fields": [
                    {
                      "constraints": {
                        "nonEmpty": true,
                        "kind": "string"
                      },
                      "name": "label",
                      "required": true,
                      "type": "string"
                    },
                    {
                      "constraints": {
                        "kind": "json"
                      },
                      "name": "equals",
                      "required": false,
                      "type": "json"
                    },
                    {
                      "constraints": {
                        "nonEmpty": true,
                        "kind": "string"
                      },
                      "name": "textIncludes",
                      "required": false,
                      "type": "string"
                    }
                  ],
                  "unknownKeys": "reject",
                  "kind": "record"
                },
                "kind": "array"
              },
              "name": "atSteps",
              "required": false,
              "type": "Array<{ label: string, equals?: json, textIncludes?: string }>"
            },
            {
              "constraints": {
                "minNonWhitespace": 20,
                "kind": "string"
              },
              "name": "allowTrivial",
              "required": false,
              "type": "triviality reason"
            }
          ],
          "unknownKeys": "reject",
          "kind": "record"
        }
      ]
    }
  },
  {
    "cardinality": "array",
    "kind": "tags",
    "schema": {
      "fields": [
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "tag",
          "required": true,
          "type": "string"
        },
        {
          "constraints": {
            "integer": true,
            "min": 0,
            "kind": "number"
          },
          "name": "count",
          "required": false,
          "type": "non-negative integer"
        },
        {
          "constraints": {
            "integer": true,
            "min": 0,
            "kind": "number"
          },
          "name": "gte",
          "required": false,
          "type": "non-negative integer"
        },
        {
          "constraints": {
            "integer": true,
            "min": 0,
            "kind": "number"
          },
          "name": "lte",
          "required": false,
          "type": "non-negative integer"
        },
        {
          "constraints": {
            "minNonWhitespace": 20,
            "kind": "string"
          },
          "name": "allowTrivial",
          "required": false,
          "type": "triviality reason"
        }
      ],
      "rules": [
        {
          "fields": [
            "count",
            "gte",
            "lte"
          ],
          "kind": "requireOneOf",
          "message": "must declare 'count', 'gte', or 'lte'; a tag assertion with none passes on a count of zero."
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "array",
    "kind": "signals",
    "minItems": 1,
    "minItemsMessage": "must contain at least one signal assertion.",
    "schema": {
      "fields": [
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "atStep",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "entity",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "integer": true,
            "min": 0,
            "kind": "number"
          },
          "name": "maxCount",
          "required": false,
          "type": "non-negative integer"
        },
        {
          "constraints": {
            "integer": true,
            "min": 0,
            "kind": "number"
          },
          "name": "minCount",
          "required": false,
          "type": "non-negative integer"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "name",
          "required": true,
          "type": "string"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "array",
    "kind": "states",
    "schema": {
      "fields": [
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "entity",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "equals",
          "required": true,
          "type": "string"
        },
        {
          "constraints": {
            "minNonWhitespace": 20,
            "kind": "string"
          },
          "name": "allowTrivial",
          "required": false,
          "type": "triviality reason"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "array",
    "kind": "hud",
    "schema": {
      "fields": [
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "id",
          "required": true,
          "type": "string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "path",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "kind": "json"
          },
          "name": "equals",
          "required": false,
          "type": "json"
        },
        {
          "constraints": {
            "kind": "number"
          },
          "name": "gte",
          "required": false,
          "type": "number"
        },
        {
          "constraints": {
            "kind": "number"
          },
          "name": "lte",
          "required": false,
          "type": "number"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "textIncludes",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "kind": "boolean"
          },
          "name": "changed",
          "required": false,
          "type": "boolean"
        },
        {
          "constraints": {
            "minNonWhitespace": 20,
            "kind": "string"
          },
          "name": "allowTrivial",
          "required": false,
          "type": "triviality reason"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "array",
    "kind": "overlayNodes",
    "schema": {
      "fields": [
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "overlayId",
          "required": true,
          "type": "string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "selector",
          "required": true,
          "type": "string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "attribute",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "kind": "json"
          },
          "name": "equals",
          "required": false,
          "type": "json"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "textIncludes",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "kind": "boolean"
          },
          "name": "visible",
          "required": false,
          "type": "boolean"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "object",
    "kind": "diagnostics",
    "schema": {
      "fields": [
        {
          "constraints": {
            "kind": "boolean"
          },
          "name": "noConsoleErrors",
          "required": false,
          "type": "boolean"
        },
        {
          "constraints": {
            "kind": "boolean"
          },
          "name": "noNetworkErrors",
          "required": false,
          "type": "boolean"
        },
        {
          "constraints": {
            "kind": "boolean"
          },
          "name": "noRuntimeDiagnostics",
          "required": false,
          "type": "boolean"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "consoleErrorsOptOutReason",
          "required": false,
          "type": "non-empty string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "networkErrorsOptOutReason",
          "required": false,
          "type": "non-empty string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "runtimeDiagnosticsOptOutReason",
          "required": false,
          "type": "non-empty string"
        },
        {
          "constraints": {
            "kind": "boolean"
          },
          "name": "runtimeReady",
          "required": false,
          "type": "boolean"
        }
      ],
      "rules": [
        {
          "equals": false,
          "field": "noConsoleErrors",
          "kind": "requireWhen",
          "message": "may be false only when 'consoleErrorsOptOutReason' explains the bounded exception.",
          "required": "consoleErrorsOptOutReason"
        },
        {
          "equals": false,
          "field": "noNetworkErrors",
          "kind": "requireWhen",
          "message": "may be false only when 'networkErrorsOptOutReason' explains the bounded exception.",
          "required": "networkErrorsOptOutReason"
        },
        {
          "equals": false,
          "field": "noRuntimeDiagnostics",
          "kind": "requireWhen",
          "message": "may be false only when 'runtimeDiagnosticsOptOutReason' explains the bounded exception.",
          "required": "runtimeDiagnosticsOptOutReason"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "object",
    "kind": "performance",
    "schema": {
      "fields": [
        {
          "constraints": {
            "min": 0,
            "kind": "number"
          },
          "name": "maxFrameMsP95",
          "required": false,
          "type": "non-negative number"
        },
        {
          "constraints": {
            "min": 0,
            "kind": "number"
          },
          "name": "maxDrawCalls",
          "required": false,
          "type": "non-negative number"
        },
        {
          "constraints": {
            "min": 0,
            "kind": "number"
          },
          "name": "maxTriangles",
          "required": false,
          "type": "non-negative number"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "array",
    "kind": "visibility",
    "schema": {
      "fields": [
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "entity",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "kind": "number"
          },
          "name": "minProjectedPixels",
          "required": false,
          "type": "number"
        },
        {
          "constraints": {
            "kind": "number"
          },
          "name": "maxOffscreenRatio",
          "required": false,
          "type": "number"
        },
        {
          "constraints": {
            "kind": "boolean"
          },
          "name": "present",
          "required": false,
          "type": "boolean"
        },
        {
          "constraints": {
            "minNonWhitespace": 20,
            "kind": "string"
          },
          "name": "allowTrivial",
          "required": false,
          "type": "triviality reason"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "object",
    "kind": "world",
    "schema": {
      "fields": [
        {
          "constraints": {
            "kind": "union",
            "variants": [
              {
                "kind": "number"
              },
              {
                "values": [
                  null
                ],
                "kind": "literal"
              }
            ]
          },
          "name": "seed",
          "required": true,
          "type": "json"
        },
        {
          "constraints": {
            "fields": [
              {
                "constraints": {
                  "nonEmpty": true,
                  "kind": "string"
                },
                "name": "agent",
                "required": true,
                "type": "string"
              },
              {
                "constraints": {
                  "nonEmpty": true,
                  "kind": "string"
                },
                "name": "core",
                "required": true,
                "type": "string"
              },
              {
                "constraints": {
                  "kind": "boolean"
                },
                "name": "portable",
                "required": false,
                "type": "boolean"
              },
              {
                "constraints": {
                  "integer": true,
                  "kind": "number"
                },
                "name": "randomState",
                "required": true,
                "type": "integer"
              },
              {
                "constraints": {
                  "kind": "union",
                  "variants": [
                    {
                      "nonEmpty": true,
                      "kind": "string"
                    },
                    {
                      "values": [
                        null
                      ],
                      "kind": "literal"
                    }
                  ]
                },
                "name": "rapier",
                "required": true,
                "type": "string | null"
              },
              {
                "constraints": {
                  "min": 0,
                  "minExclusive": true,
                  "kind": "number"
                },
                "name": "step",
                "required": true,
                "type": "positive number"
              }
            ],
            "unknownKeys": "reject",
            "kind": "record"
          },
          "name": "runtime",
          "required": false,
          "type": "object"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "array",
    "kind": "contacts",
    "schema": {
      "fields": [
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "atStep",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "entity",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "with",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "kind",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "kind": "number"
          },
          "name": "minCount",
          "required": false,
          "type": "number"
        },
        {
          "constraints": {
            "integer": true,
            "min": 0,
            "kind": "number"
          },
          "name": "maxCount",
          "required": false,
          "type": "non-negative integer"
        },
        {
          "constraints": {
            "items": {
              "values": [
                "web",
                "desktop",
                "bevy"
              ],
              "kind": "literal"
            },
            "kind": "array"
          },
          "name": "requiredOn",
          "required": false,
          "type": "Array<'web' | 'desktop' | 'bevy'>"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "array",
    "kind": "settled",
    "schema": {
      "fields": [
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "entity",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "atStep",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "integer": true,
            "min": 1,
            "kind": "number"
          },
          "name": "minBodies",
          "required": false,
          "type": "positive integer"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "compareToStep",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "min": 0,
            "minExclusive": true,
            "kind": "number"
          },
          "name": "minMeanPoseDistance",
          "required": false,
          "type": "positive number"
        },
        {
          "constraints": {
            "items": {
              "values": [
                "web",
                "desktop",
                "bevy"
              ],
              "kind": "literal"
            },
            "kind": "array"
          },
          "name": "requiredOn",
          "required": false,
          "type": "Array<'web' | 'desktop' | 'bevy'>"
        },
        {
          "constraints": {
            "minNonWhitespace": 20,
            "kind": "string"
          },
          "name": "allowTrivial",
          "required": false,
          "type": "triviality reason"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "array",
    "kind": "occluded",
    "schema": {
      "fields": [
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "entity",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "target",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "minNonWhitespace": 20,
            "kind": "string"
          },
          "name": "allowTrivial",
          "required": false,
          "type": "triviality reason"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  },
  {
    "cardinality": "array",
    "kind": "animation",
    "schema": {
      "fields": [
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "entity",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "nonEmpty": true,
            "kind": "string"
          },
          "name": "clip",
          "required": false,
          "type": "string"
        },
        {
          "constraints": {
            "kind": "boolean"
          },
          "name": "entered",
          "required": false,
          "type": "boolean"
        },
        {
          "constraints": {
            "kind": "number"
          },
          "name": "advancedFrames",
          "required": false,
          "type": "number"
        },
        {
          "constraints": {
            "kind": "boolean"
          },
          "name": "finished",
          "required": false,
          "type": "boolean"
        },
        {
          "constraints": {
            "minNonWhitespace": 20,
            "kind": "string"
          },
          "name": "allowTrivial",
          "required": false,
          "type": "triviality reason"
        }
      ],
      "unknownKeys": "reject",
      "kind": "record"
    }
  }
];

function hasOwn(value: Record<string, unknown>, key: string): boolean {
  return Object.prototype.hasOwnProperty.call(value, key);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function describeValue(value: unknown): string {
  if (value === null) return "null";
  if (Array.isArray(value)) return "an array";
  if (typeof value === "string") return "the string " + JSON.stringify(value);
  return typeof value + " " + (JSON.stringify(value) ?? String(value));
}

function isSafeProjectRelativePng(value: unknown): boolean {
  if (
    typeof value !== "string"
    || !value.toLowerCase().endsWith(".png")
    || value.startsWith("/")
    || /^[A-Za-z]:[\\/]/u.test(value)
  ) return false;
  return !value.split(/[\\/]/).includes("..");
}

function expectedType(constraint: IGeneratedConstraint, declaredType: string): string {
  if (constraint.kind === "string" && constraint.minNonWhitespace !== undefined) {
    return "a string with at least " + constraint.minNonWhitespace + " non-whitespace characters";
  }
  if (constraint.kind === "number" && declaredType === "number") {
    return "number (finite number)";
  }
  return declaredType;
}

function invalidType(
  value: unknown,
  constraint: IGeneratedConstraint,
  scenarioPath: string,
  objectPath: string,
  declaredType: string,
): never {
  throw invalidScenario(
    scenarioPath,
    "'" + objectPath + "' must be " + expectedType(constraint, declaredType) + ", received " + describeValue(value) + ".",
  );
}

function validateRecord(
  value: unknown,
  constraint: Extract<IGeneratedConstraint, { kind: "record" }>,
  scenarioPath: string,
  objectPath: string,
): Record<string, unknown> {
  if (!isRecord(value)) invalidType(value, constraint, scenarioPath, objectPath, "an object");
  const fields = new Map(constraint.fields.map((field) => [field.name, field]));
  if (constraint.unknownKeys !== "allow") {
    const unknown = Object.keys(value).find((key) => !fields.has(key));
    if (unknown !== undefined) {
      throw invalidScenario(
        scenarioPath,
        "Unknown key '" + unknown + "' at " + objectPath + "." + unknown + ". Supported keys: " + [...fields.keys()].sort().join(", ") + ".",
      );
    }
  }
  const result: Record<string, unknown> = {};
  for (const field of constraint.fields) {
    const present = hasOwn(value, field.name) && value[field.name] !== undefined;
    if (!present) continue;
    result[field.name] = validateConstraint(
      value[field.name],
      field.constraints,
      scenarioPath,
      objectPath + "." + field.name,
      field.type,
    );
  }
  for (const field of constraint.fields) {
    if (!hasOwn(value, field.name) || value[field.name] === undefined) {
      if (field.required) {
        invalidType(undefined, field.constraints, scenarioPath, objectPath + "." + field.name, field.type);
      }
    }
  }
  for (const rule of constraint.rules ?? []) validateRule(result, rule, scenarioPath, objectPath);
  return result;
}

function validateRule(
  value: Record<string, unknown>,
  rule: IGeneratedRule,
  scenarioPath: string,
  objectPath: string,
): void {
  if (rule.kind === "requireOneOf") {
    if (rule.fields.some((field) => hasOwn(value, field))) return;
    throw invalidScenario(scenarioPath, "'" + objectPath + "' " + (rule.message ?? ("must declare one of " + rule.fields.join(", "))));
  }
  if (rule.kind === "requireOneOfOrTrue") {
    if (rule.fields.some((field) => hasOwn(value, field)) || rule.trueFields.some((field) => value[field] === true)) return;
    throw invalidScenario(scenarioPath, "'" + objectPath + "' " + (rule.message ?? "must declare a binding predicate"));
  }
  if (rule.kind === "requireWhen") {
    if (value[rule.field] !== rule.equals) return;
    const reason = value[rule.required];
    if (typeof reason === "string" && reason.trim() !== "") return;
    throw invalidScenario(scenarioPath, "Assertion '" + objectPath + "." + rule.field + "' " + (rule.message ?? ("requires '" + rule.required + "'")));
  }
  if (rule.kind === "nonEmptyArray") {
    const entries = value[rule.field];
    if (Array.isArray(entries) && entries.length > 0) return;
    throw invalidScenario(scenarioPath, "'" + objectPath + "." + rule.field + "' " + (rule.message ?? "must contain at least one entry"));
  }
  const entries = value[rule.field];
  if (!Array.isArray(entries)) return;
  for (let index = 1; index < entries.length; index += 1) {
    if (entries[index] === entries[index - 1]) {
      throw invalidScenario(scenarioPath, rule.message ?? ("'" + objectPath + "." + rule.field + "' must not repeat a consecutive value."));
    }
  }
}

function validateConstraint(
  value: unknown,
  constraint: IGeneratedConstraint,
  scenarioPath: string,
  objectPath: string,
  declaredType: string,
): unknown {
  if (constraint.kind === "json") return value;
  if (constraint.kind === "boolean") {
    if (typeof value !== "boolean") invalidType(value, constraint, scenarioPath, objectPath, declaredType);
    return value;
  }
  if (constraint.kind === "number") {
    if (
      typeof value !== "number"
      || !Number.isFinite(value)
      || (constraint.integer === true && !Number.isInteger(value))
      || (constraint.min !== undefined && (constraint.minExclusive === true ? value <= constraint.min : value < constraint.min))
      || (constraint.max !== undefined && value > constraint.max)
    ) invalidType(value, constraint, scenarioPath, objectPath, declaredType);
    return value;
  }
  if (constraint.kind === "string") {
    if (
      typeof value !== "string"
      || (constraint.nonEmpty === true && value.trim() === "")
      || (constraint.minNonWhitespace !== undefined && value.replace(/\s/gu, "").length < constraint.minNonWhitespace)
      || (constraint.format === "project-relative-png" && !isSafeProjectRelativePng(value))
    ) invalidType(value, constraint, scenarioPath, objectPath, declaredType);
    return value;
  }
  if (constraint.kind === "literal") {
    if (!constraint.values.some((candidate) => candidate === value)) invalidType(value, constraint, scenarioPath, objectPath, declaredType);
    return value;
  }
  if (constraint.kind === "array") {
    if (!Array.isArray(value)) invalidType(value, constraint, scenarioPath, objectPath, declaredType);
    if (constraint.minItems !== undefined && value.length < constraint.minItems) {
      throw invalidScenario(scenarioPath, "'" + objectPath + "' must contain at least " + constraint.minItems + " entries.");
    }
    if (constraint.maxItems !== undefined && value.length > constraint.maxItems) {
      throw invalidScenario(scenarioPath, "'" + objectPath + "' must contain no more than " + constraint.maxItems + " entries.");
    }
    return value.map((item, index) => validateConstraint(item, constraint.items, scenarioPath, objectPath + "[" + index + "]", "the declared item type"));
  }
  if (constraint.kind === "tuple") {
    if (!Array.isArray(value) || value.length !== constraint.items.length) invalidType(value, constraint, scenarioPath, objectPath, declaredType);
    return constraint.items.map((item, index) => validateConstraint(value[index], item, scenarioPath, objectPath + "[" + index + "]", "the declared tuple item type"));
  }
  if (constraint.kind === "record") return validateRecord(value, constraint, scenarioPath, objectPath);
  const variantIndex = constraint.discriminator === undefined
    ? undefined
    : isRecord(value) && hasOwn(value, constraint.discriminator.field)
      ? constraint.discriminator.presentVariant
      : constraint.variants.findIndex((_, index) => index !== constraint.discriminator?.presentVariant);
  if (variantIndex !== undefined && variantIndex >= 0) {
    return validateConstraint(value, constraint.variants[variantIndex]!, scenarioPath, objectPath, declaredType);
  }
  let firstError: unknown;
  for (const variant of constraint.variants) {
    try {
      return validateConstraint(value, variant, scenarioPath, objectPath, declaredType);
    } catch (error) {
      firstError ??= error;
    }
  }
  throw firstError ?? invalidScenario(scenarioPath, "'" + objectPath + "' does not match any declared variant.");
}

function schemaFor(kind: keyof IPlaytestScenarioAssertions): IGeneratedEntry {
  const entry = GENERATED_ASSERTION_SCHEMAS.find((candidate) => candidate.kind === kind);
  if (entry === undefined) throw new Error("Generated assertion validator is missing '" + String(kind) + "'.");
  return entry;
}

export function validateGeneratedAssertion(
  kind: keyof IPlaytestScenarioAssertions,
  value: unknown,
  scenarioPath: string,
  objectPath = "assert." + String(kind),
): unknown {
  const entry = schemaFor(kind);
  if (entry.cardinality === "array" && !Array.isArray(value)) {
    throw invalidScenario(scenarioPath, "Assertion 'assert." + String(kind) + "' must be an array; the declared assertion cannot be executed.");
  }
  if (entry.cardinality === "object" && !isRecord(value)) {
    throw invalidScenario(scenarioPath, "Assertion 'assert." + String(kind) + "' must be an object; the declared assertion cannot be executed.");
  }
  if (entry.cardinality === "array" && entry.minItems !== undefined && (value as unknown[]).length < entry.minItems) {
    throw invalidScenario(
      scenarioPath,
      "Assertion 'assert." + String(kind) + "' " + (entry.minItemsMessage ?? ("must contain at least " + entry.minItems + " assertion.")),
    );
  }
  if (entry.cardinality === "array") {
    return (value as unknown[]).map((item, index) => validateConstraint(item, entry.schema, scenarioPath, objectPath + "[" + index + "]", "assertion"));
  }
  return validateConstraint(value, entry.schema, scenarioPath, objectPath, "assertion");
}

export function validateGeneratedAssertions(
  value: Record<string, unknown>,
  scenarioPath: string,
): IPlaytestScenarioAssertions {
  const result: Record<string, unknown> = {};
  for (const entry of GENERATED_ASSERTION_SCHEMAS) {
    if (value[entry.kind] === undefined) continue;
    result[entry.kind] = validateGeneratedAssertion(entry.kind, value[entry.kind], scenarioPath);
  }
  return result as IPlaytestScenarioAssertions;
}
