/**
 * Records JSON.parse (V8, the engine three runs on) over a corpus of valid and invalid texts as a
 * C++ table the native reader is compared against: each text and either `throws` or a canonical dump
 * (numbers as binary64 bits, strings as UTF-8 hex, object members in order).
 *
 *   pnpm --workspace-root exec tsx packages/runtime-native/tests/native-engine/json/json-reference.ts
 *   ... -- --check   (fails when the committed table is not what JSON.parse produces)
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const OUT = path.join(path.dirname(fileURLToPath(import.meta.url)), "json_reference.inc");

const CORPUS = [
  // values and whitespace
  "null",
  "true",
  "false",
  " \t\r\n 7 \n",
  '""',
  "[]",
  "{}",
  "[ ]",
  "{ }",
  "[1,2,3]",
  '{"a":1,"b":[true,null]}',
  '{"nested":{"deeper":{"deepest":[[[]]]}}}',
  // numbers
  "0",
  "-0",
  "1",
  "-1",
  "0.5",
  "-0.25",
  "1e3",
  "1E3",
  "1e+3",
  "1e-3",
  "123.456e-7",
  "0.1",
  "0.2",
  "0.30000000000000004",
  "9007199254740993",
  "18446744073709551616",
  "1.7976931348623157e308",
  "1.7976931348623159e308",
  "1e400",
  "-1e400",
  "5e-324",
  "2.4703282292062328e-324",
  "2e-324",
  "1e-400",
  "-1e-400",
  "0.000000000000000000001",
  "123456789012345678901234567890e-10",
  "0e0",
  "0E-0",
  "-0.0e+00",
  // strings and escapes
  '"plain"',
  '"\\"\\\\\\/\\b\\f\\n\\r\\t"',
  '"\\u0041\\u00e9\\u4e2d"',
  '"\\ud83d\\ude00"',
  '"\\uD83D\\uDE00"',
  '"lone \\ud83d end"',
  '"lone low \\ude00"',
  '"é€😀"',
  '"tab\\tinside"',
  // objects: order and duplicates
  '{"b":1,"a":2,"c":3}',
  '{"a":1,"a":2}',
  '{"a":1,"b":2,"a":3}',
  '{"":0}',
  '{"x":{"x":{"x":1}}}',
  // invalid
  "",
  " ",
  "[1,]",
  '{"a":1,}',
  "[,1]",
  "01",
  "+1",
  ".5",
  "1.",
  "1e",
  "1e+",
  "-",
  "--1",
  "0x10",
  "NaN",
  "Infinity",
  "'single'",
  '"unterminated',
  '"bad \\x escape"',
  '"\\u12"',
  "[1 2]",
  '{"a" 1}',
  "{a:1}",
  '{"a":}',
  "tru",
  "nul",
  "[1]]",
  "1 2",
  "/* c */ 1",
  '"line\nbreak"',
  '"\\u00"',
  "[",
  '{"a":1',
];

const bits = (x: number) => {
  const w = new Uint32Array(new Float64Array([x]).buffer);
  return ((BigInt(w[1] as number) << 32n) | BigInt(w[0] as number)).toString(16).padStart(16, "0");
};
// Strings as JavaScript holds them: UTF-16 code units, four hex digits each (lone surrogates kept).
const utf8 = (s: string) =>
  Array.from({ length: s.length }, (_, i) => s.charCodeAt(i).toString(16).padStart(4, "0")).join(
    "",
  );
const dump = (v: unknown): string => {
  if (v === null) return "n";
  if (v === true) return "t";
  if (v === false) return "f";
  if (typeof v === "number") return `d${bits(v)}`;
  if (typeof v === "string") return `s${utf8(v)}`;
  if (Array.isArray(v)) return `[${v.map(dump).join(",")}]`;
  return `{${Object.entries(v as object)
    .map(([k, x]) => `${utf8(k)}:${dump(x)}`)
    .join(",")}}`;
};

const rows = CORPUS.map((text) => {
  let result: string;
  let stringified = "";
  try {
    const value = JSON.parse(text);
    result = dump(value);
    stringified = JSON.stringify(value);
  } catch {
    result = "throws";
  }
  return [text, result, stringified] as const;
});
// Number::toString over the layout boundaries (1e21, 1e-7), shortest round-trip digits, and a walk.
let seed = 0x9e3779b9;
const walk = Array.from({ length: 120 }, () => {
  seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0;
  const mantissa = seed / 2 ** 32;
  seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0;
  // `10 ** k` is not correctly rounded and differs across V8 versions; parsing `1e<k>` is, so the
  // fixture does not depend on which Node regenerates or checks it.
  return (mantissa - 0.5) * Number(`1e${(seed % 60) - 30}`);
});
const NUMBERS = [
  0,
  -0,
  1,
  -1,
  0.1,
  0.2,
  0.1 + 0.2,
  1 / 3,
  2 / 3,
  100,
  1e20,
  1e21,
  1e22,
  123456789012345680000,
  1.5e21,
  1e-6,
  1e-7,
  1.5e-7,
  0.000001,
  0.0000012345,
  5e-324,
  Number.MAX_VALUE,
  Number.MIN_VALUE,
  Number.EPSILON,
  2 ** 53,
  2 ** 53 + 2,
  -(2 ** 31),
  4294967295,
  1e100,
  1.7976931348623157e308,
  9.999999999999999e22,
  Math.PI,
  Math.E,
  0.5,
  0.25,
  12.5,
  1234.5678,
  Number.NaN,
  Number.POSITIVE_INFINITY,
  Number.NEGATIVE_INFINITY,
  ...walk,
];
// Objects keyed by integer-like strings reorder in JavaScript; the corpus has none, and the reader
// keeps insertion order, which is JavaScript's order for every other key.
const cString = (s: string) => JSON.stringify(s);
const text = [
  "// Generated by packages/runtime-native/tests/native-engine/json/json-reference.ts from JSON.parse.",
  "// Do not edit: rerun the generator.",
  "static const char* const kCorpus[][3] = {",
  ...rows.map(([t, r, s]) => `    {${cString(t)}, ${cString(r)}, ${cString(s)}},`),
  "};",
  "static const std::pair<uint64_t, const char*> kNumbers[] = {",
  ...NUMBERS.map((x) => `    {0x${bits(x)}ull, ${cString(String(x))}},`),
  "};",
  "",
].join("\n");
if (process.argv.includes("--check")) {
  if (readFileSync(OUT, "utf8") !== text) {
    console.error("TN_FIXTURE_STALE: json_reference.inc is not what JSON.parse produces");
    process.exit(1);
  }
  console.log(`current: ${rows.length} texts`);
} else {
  writeFileSync(OUT, text);
  console.log(`wrote ${rows.length} texts`);
}
