# ctest native_engine_target_graph: fails when an engine target is below C++20 or reaches a JS
# engine, a web view or the scripting host. GRAPH is written by NativeEngine.cmake at configure.
if(NOT EXISTS "${GRAPH}")
    message(FATAL_ERROR "native engine target graph missing: ${GRAPH}")
endif()
file(STRINGS "${GRAPH}" rows)
if(NOT rows)
    message(FATAL_ERROR "native engine target graph is empty")
endif()
set(failures "")
foreach(row IN LISTS rows)
    string(REPLACE "|" ";" fields "${row}")
    list(GET fields 0 target)
    list(GET fields 1 standard)
    list(LENGTH fields count)
    set(links "")
    if(count GREATER 2)
        list(SUBLIST fields 2 -1 links)
    endif()
    if(NOT standard OR standard LESS 20)
        list(APPEND failures "${target}: C++ standard '${standard}' is below 20")
    endif()
    foreach(link IN LISTS links)
        string(TOLOWER "${link}" lower)
        if(lower MATCHES "(^|[/:_-]|lib)(v8|quickjs|javascriptcore|hermes|webkit|webkit2gtk|mystral-runtime)([./:_-]|$)")
            list(APPEND failures "${target}: links ${link}")
        endif()
    endforeach()
    message(STATUS "${target}: C++${standard}, ${count} graph fields")
endforeach()
if(failures)
    string(REPLACE ";" "\n  " failures "${failures}")
    message(FATAL_ERROR "native engine target graph reaches scripting:\n  ${failures}")
endif()
