# ctest native_engine_no_blocking_waits: engine sources never wait on the device or a thread, so
# the same code runs on browser WebGPU (owner decision 4, PRD-509). Tests may wait; src/engine may not.
file(GLOB_RECURSE sources "${ENGINE_SOURCE_DIR}/*.cpp" "${ENGINE_SOURCE_DIR}/*.h")
if(NOT sources)
    message(FATAL_ERROR "no engine sources under ${ENGINE_SOURCE_DIR}")
endif()
set(forbidden "wgpuInstanceWaitAny|wgpuDevicePoll\\([^,]+, *(true|1)|sleep_for|sleep_until|condition_variable|\\.wait\\(|std::future")
set(failures "")
foreach(source IN LISTS sources)
    file(STRINGS "${source}" lines REGEX "${forbidden}")
    foreach(line IN LISTS lines)
        list(APPEND failures "${source}: ${line}")
    endforeach()
endforeach()
if(failures)
    string(REPLACE ";" "\n  " failures "${failures}")
    message(FATAL_ERROR "blocking wait in engine sources:\n  ${failures}")
endif()
list(LENGTH sources count)
message(STATUS "${count} engine sources, no blocking waits")
