# PRD-368: an ABI/source change must invalidate an old unsafe compiler blob even if the package
# version was not bumped. No timestamps or build-directory paths: reproducible inputs only.
if(MYSTRAL_WGPU_PIPELINE_CACHE)
    file(GLOB_RECURSE TN_CACHE_IDENTITY_SOURCES CONFIGURE_DEPENDS
        "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp" "${CMAKE_CURRENT_SOURCE_DIR}/src/*.h"
        "${CMAKE_CURRENT_SOURCE_DIR}/src/*.mm" "${CMAKE_CURRENT_SOURCE_DIR}/src/*.js"
        "${CMAKE_CURRENT_SOURCE_DIR}/include/*.h" "${CMAKE_CURRENT_SOURCE_DIR}/cmake/*.cmake")
    list(APPEND TN_CACHE_IDENTITY_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/CMakeLists.txt")
    list(SORT TN_CACHE_IDENTITY_SOURCES)
    set(TN_CACHE_BUILD_MATERIAL "${PROJECT_VERSION}|${CMAKE_SYSTEM_NAME}|${CMAKE_SYSTEM_PROCESSOR}|${CMAKE_CXX_COMPILER_ID}|${CMAKE_CXX_COMPILER_VERSION}|${CMAKE_CXX_FLAGS}|${CMAKE_CXX_FLAGS_RELEASE}|${CMAKE_CXX_FLAGS_DEBUG}|${CMAKE_BUILD_TYPE}|${MYSTRAL_JS_ENGINE_NAME}|${MYSTRAL_WEBGPU_NAME}")
    foreach(TN_CACHE_INPUT IN LISTS TN_CACHE_IDENTITY_SOURCES)
        file(SHA256 "${TN_CACHE_INPUT}" TN_CACHE_INPUT_SHA)
        file(RELATIVE_PATH TN_CACHE_INPUT_NAME "${CMAKE_CURRENT_SOURCE_DIR}" "${TN_CACHE_INPUT}")
        string(APPEND TN_CACHE_BUILD_MATERIAL "|${TN_CACHE_INPUT_NAME}:${TN_CACHE_INPUT_SHA}")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${TN_CACHE_INPUT}")
    endforeach()
    # CMake already resolved this exact library against the installed cache API header.
    file(SHA256 "${WGPU_LIBRARY}" TN_CACHE_LIBRARY_SHA)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${WGPU_LIBRARY}")
    string(SHA256 TN_CACHE_BUILD_SHA "${TN_CACHE_BUILD_MATERIAL}|${TN_CACHE_LIBRARY_SHA}")
    target_compile_definitions(mystral-runtime PRIVATE
        TN_PIPELINE_CACHE_BUILD_ID="${TN_CACHE_BUILD_SHA}"
        TN_PIPELINE_CACHE_ABI_ID="wgpu25-cache-api1-${TN_CACHE_LIBRARY_SHA}")
endif()
