/**
 * Records loop.ts's fixed-step answers as a C++ table the native test compares against (PRD-528
 * phase 1). Inputs and answers are bit patterns, so the comparisons are exact.
 *
 * `FixedStepLoop` is driven through its own `requestFrame` seam: the callback is stored, then called
 * with each recorded frame time, exactly as a host would. The held and frozen branches are out of
 * scope -- the native clock does not port them. After every frame the table records the update
 * count, `tick()` and `interpolationAlpha` for the same frame times.
 *
 *   pnpm --workspace-root exec tsx packages/runtime-native/tests/native-engine/loop/loop-reference.ts
 *   ... -- --check   (fails when a committed table is not what loop.ts produces)
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { FixedStepLoop } from "../../../../core/src/loop.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, "loop_reference.inc");

const f64 = (x: number) => {
  const words = new Uint32Array(new Float64Array([x]).buffer);
  return (BigInt(words[1] as number) << 32n) | BigInt(words[0] as number);
};
const hex64 = (bits: bigint) => `0x${bits.toString(16).padStart(16, "0")}ull`;

interface ICase {
  name: string;
  step: number;
  maxSteps: number;
  start: number;
  times: number[];
}

/** Frame timestamps for a constant rate, the first at the start time. */
const hz = (rate: number, frames: number) =>
  Array.from({ length: frames }, (_, i) => (i * 1000) / rate);

/** Cumulative timestamps from inter-frame deltas, the first at the start time. */
const cumulative = (deltas: number[]) => {
  const times = [0];
  for (const delta of deltas) times.push((times[times.length - 1] as number) + delta);
  return times;
};

const FRAME = 1000 / 60;
const STALL = Array.from({ length: 121 }, (_, i) => (i === 60 ? 500 : 0) + FRAME);
let seed = 0x2f6b9a1d;
const JITTER = Array.from({ length: 200 }, () => {
  seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0;
  return 8 + (seed / 2 ** 32) * 26;
});

const cases: ICase[] = [
  { name: "60hz-60", maxSteps: 5, start: 0, step: 1 / 60, times: hz(60, 121) },
  { name: "144hz-60", maxSteps: 5, start: 0, step: 1 / 60, times: hz(144, 145) },
  { name: "30hz-60", maxSteps: 5, start: 0, step: 1 / 60, times: hz(30, 61) },
  { name: "60hz-120", maxSteps: 5, start: 0, step: 1 / 120, times: hz(60, 121) },
  { name: "jitter", maxSteps: 5, start: 0, step: 1 / 60, times: cumulative(JITTER) },
  { name: "stall", maxSteps: 5, start: 0, step: 1 / 60, times: cumulative(STALL) },
  {
    name: "backwards",
    maxSteps: 5,
    start: 0,
    step: 1 / 60,
    // Repeated timestamps, then a clock that goes backwards and recovers past the old high water.
    times: [0, 16, 32, 32, 20, 10, 33, 33, 49, 60, 50, 66, 66, 82],
  },
  { name: "one-max-step", maxSteps: 1, start: 0, step: 1 / 60, times: hz(20, 51) },
];

/** Drives one case the way a host does: start, then call the stored frame callback per timestamp. */
function record(c: ICase) {
  const updates: number[] = [];
  const ticks: number[] = [];
  const alphas: bigint[] = [];
  let callback: ((time: number) => void) | undefined;
  let currentTime = c.start;
  let updatesThisFrame = 0;
  const loop = new FixedStepLoop({
    maxSteps: c.maxSteps,
    now: () => currentTime,
    onUpdate: () => {
      updatesThisFrame += 1;
    },
    requestFrame: (scheduled) => {
      callback = scheduled;
      return 1;
    },
    step: c.step,
  });

  loop.start(c.start);
  for (const time of c.times) {
    currentTime = time;
    updatesThisFrame = 0;
    if (callback === undefined) throw new Error("loop did not schedule a frame");
    callback(time);
    updates.push(updatesThisFrame);
    ticks.push(loop.tick());
    alphas.push(f64(loop.interpolationAlpha));
  }
  return { alphas, ticks, updates };
}

const lines = [
  "// Generated by packages/runtime-native/tests/native-engine/loop/loop-reference.ts from",
  "// packages/core/src/loop.ts. Do not edit: rerun the generator.",
  "// Times are float64 bits in milliseconds; updates and ticks are integer quantities and alpha",
  "// is float64 bits.",
];
for (const [i, c] of cases.entries()) {
  const { alphas, ticks, updates } = record(c);
  lines.push(
    `static const uint64_t kTimes${i}[] = {${c.times.map((t) => hex64(f64(t))).join(", ")}};`,
    `static const uint64_t kUpdates${i}[] = {${updates.map((u) => `${u}ull`).join(", ")}};`,
    `static const uint64_t kTicks${i}[] = {${ticks.map((t) => `${t}ull`).join(", ")}};`,
    `static const uint64_t kAlphas${i}[] = {${alphas.map(hex64).join(", ")}};`,
  );
}
lines.push("static const LoopCase kCases[] = {");
for (const [i, c] of cases.entries())
  lines.push(
    `    {"${c.name}", ${hex64(f64(c.step))}, ${c.maxSteps}u, kTimes${i}, kUpdates${i}, kTicks${i}, kAlphas${i}, std::size(kTimes${i})},`,
  );
lines.push("};", "");

const text = lines.join("\n");
if (process.argv.includes("--check")) {
  if (readFileSync(OUT, "utf8") !== text) {
    console.error("TN_FIXTURE_STALE: loop_reference.inc is not what loop.ts produces");
    process.exit(1);
  }
  console.log("current: loop_reference.inc");
} else {
  writeFileSync(OUT, text);
  console.log(`wrote ${OUT}`);
}
