#!/usr/bin/env node
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { launchMcpServer } from "./launch.mjs";
import { MCP_PACKAGES } from "./servers.mjs";

// Core carries the built server beside this shim, so a project that installed `@threenative/core`
// has working Blender tools with no network and no extra install.
//
// `blender-server.mjs` is generated by `scripts/bundle-blender-mcp.mjs` **and committed**, unlike
// its `engine-server.mjs` neighbour, which is gitignored. The difference matters: the npx fallback
// below cannot work for this server, because `threenative-blender-mcp` has never been published —
// a missing bundle becomes
//
//   threenative-blender exited before completing MCP requests (1): npm error code E404
//
// which is what the golden-path matrix reported when the file was gitignored and CI's packed core
// tarball therefore did not contain it. `mcp-install.spec.ts` holds the committed copy equal to the
// current build output, the way `capabilities.json` and the census records are held.
const localServer = path.resolve(fileURLToPath(import.meta.url), "..", "blender-server.mjs");
if (existsSync(localServer)) {
  const { runServer } = await import("./blender-server.mjs");
  runServer();
} else {
  await launchMcpServer(MCP_PACKAGES.blender);
}
