#!/usr/bin/env node
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { launchMcpServer } from "./launch.mjs";
import { MCP_PACKAGES } from "./servers.mjs";

// The capability server must answer with the manifest of the engine the game actually runs, and
// the copy this package ships is generated by the same build as that engine. Prefer it over any
// copy the project committed: a committed snapshot drifts the moment the engine dependency moves.
// With no bundled copy (a stripped install), fall through to the server's own defaults.
const bundled = path.resolve(fileURLToPath(import.meta.url), "..", "..", "capabilities.json");
const env = existsSync(bundled)
  ? Object.fromEntries([["THREENATIVE_CAPABILITIES_MANIFEST", bundled]])
  : {};

const localServer = path.resolve(fileURLToPath(import.meta.url), "..", "engine-server.mjs");
if (existsSync(localServer)) {
  const { runServer } = await import("./engine-server.mjs");
  runServer(env.THREENATIVE_CAPABILITIES_MANIFEST);
} else {
  await launchMcpServer({ ...MCP_PACKAGES.engine, env });
}
