import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Document, Logger, NodeIO } from "@gltf-transform/core";
import { ALL_EXTENSIONS } from "@gltf-transform/extensions";
import { MeshoptDecoder } from "meshoptimizer";
import { describe, expect, it } from "vitest";
import { convertFoliageCutout } from "../src/foliage.js";
import type { ICardLevelSummary } from "../src/lod/cards.js";
import { type DiscreteLod, TNDiscreteLod, TN_DISCRETE_LOD } from "../src/lod/extension.js";
import {
  type IModelLodSummary,
  LOD_MIN_SAVING,
  LOD_TERMINAL_KEEP_RATIO,
  LOD_TERMINAL_MIN_TRIANGLES,
} from "../src/lod/generate.js";
import { type IModelPassOptions, modelPass } from "../src/passes/model.js";
import { TNVirtualGeometry } from "../src/virtual/extension.js";

// PRD-458 AC-4 — a real conifer through the real cook. The fixture is generated by the engine's own
// procedural vegetation exporter (see `foliage-conifer.mjs` beside it): a bark primitive and a
// needle-card primitive whose material ships as `BLEND` with the alpha in its base-colour texture,
// which is the shape every tree pack exports and the case the cook has to recognise.
//
// The failure this guards against is the earlier machinefall LOD1, where collapse decimation threw
// away whole needle and bark materials: a level that does not draw a material is a tree with holes
// in it, and it is invisible in a byte count. So every level is read back out of the *shipped*
// bytes and asserted to draw every LOD0 material, not merely to have fewer triangles.

const SILENT = new Logger(Logger.Verbosity.SILENT);
const FIXTURE = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "fixtures/foliage-conifer.glb",
);

async function readWithLod(root: Buffer): Promise<Document> {
  await MeshoptDecoder.ready;
  const io = new NodeIO()
    .setLogger(SILENT)
    .registerExtensions([...ALL_EXTENSIONS, TNVirtualGeometry, TNDiscreteLod])
    .registerDependencies({ "meshopt.decoder": MeshoptDecoder });
  return io.readJSON(await io.binaryToJSON(root));
}

interface ICooked {
  readonly buffer: Buffer;
  readonly document: Document;
  readonly summary: IModelLodSummary;
}

async function cookConifer(lod: IModelPassOptions["lod"] = true): Promise<ICooked> {
  const input = await readFile(FIXTURE);
  const result = await modelPass({ compact: false, lod, virtual: "none" }).apply(
    input,
    "trees/conifer.glb",
  );
  if (Buffer.isBuffer(result)) throw new Error("the model pass returned an unchanged buffer");
  const summary = result.entry?.lod as IModelLodSummary | undefined;
  if (summary === undefined) throw new Error("the pass produced no lod summary");
  return { buffer: result.buffer, document: await readWithLod(result.buffer), summary };
}

/**
 * Material name per LOD0 primitive, in document order, and each primitive's level triangle counts.
 *
 * The counts come from the pass's own summary, which `validateDiscreteLod` re-checks against the
 * *written* bytes (LOD0 identity, monotonic count/error, index ranges) before the pass returns, so
 * a green assertion here is a statement about the shipped file and not about an in-memory graph.
 */
function chains(
  document: Document,
  summary: IModelLodSummary,
): {
  readonly levels: readonly { counts: number[]; lod0: number; material: string; mesh: string }[];
  readonly lod0Materials: readonly string[];
} {
  const levels: { counts: number[]; lod0: number; material: string; mesh: string }[] = [];
  const lod0Materials: string[] = [];
  for (const mesh of document.getRoot().listMeshes()) {
    for (const [index, primitive] of mesh.listPrimitives().entries()) {
      const material = primitive.getMaterial()?.getName() ?? "";
      lod0Materials.push(material);
      const chain = summary.primitives.find(
        (entry) => entry.mesh === mesh.getName() && entry.primitive === index,
      );
      if (chain === undefined) continue;
      levels.push({
        counts: chain.levels.map((level) => level.triangles),
        lod0: chain.trianglesBefore,
        material,
        mesh: mesh.getName(),
      });
    }
  }
  return { levels, lod0Materials };
}

/**
 * A synthetic card set: `cards` isolated alpha-tested quads spread through a volume. Every vertex is
 * on a component border, so LockBorder refuses every collapse — the shape that routes foliage to the
 * card reducer and the shape whose per-cell floor the terminal level has to get below.
 */
async function cardsGlb(cards: number): Promise<Buffer> {
  const document = new Document();
  const buffer = document.createBuffer();
  const scene = document.createScene();
  const positions: number[] = [];
  const indices: number[] = [];
  let seed = 1_234_567;
  const random = (): number => {
    seed = (seed * 1_103_515_245 + 12_345) & 0x7f_ff_ff_ff;
    return seed / 0x7f_ff_ff_ff;
  };
  for (let card = 0; card < cards; card += 1) {
    const x = random() * 2 - 1;
    const y = random() * 2 - 1;
    const z = random() * 2 - 1;
    const size = 0.02;
    const base = positions.length / 3;
    positions.push(
      x - size,
      y - size,
      z,
      x + size,
      y - size,
      z,
      x + size,
      y + size,
      z,
      x - size,
      y + size,
      z,
    );
    indices.push(base, base + 1, base + 2, base, base + 2, base + 3);
  }
  const primitive = document
    .createPrimitive()
    .setAttribute(
      "POSITION",
      document
        .createAccessor()
        .setType("VEC3")
        .setArray(Float32Array.from(positions))
        .setBuffer(buffer),
    )
    .setIndices(
      document
        .createAccessor()
        .setType("SCALAR")
        .setArray(Uint32Array.from(indices))
        .setBuffer(buffer),
    )
    .setMaterial(document.createMaterial("leaf").setAlphaMode("MASK").setAlphaCutoff(0.5));
  scene.addChild(
    document.createNode("leaves").setMesh(document.createMesh("leaves").addPrimitive(primitive)),
  );
  return Buffer.from(await new NodeIO().registerExtensions(ALL_EXTENSIONS).writeBinary(document));
}

describe("foliage cutout conversion and LOD (PRD-458 AC-4)", () => {
  it("converts texture-alpha BLEND needles to MASK and reports the conversion", async () => {
    const source = await readWithLod(await readFile(FIXTURE));
    const needles = source
      .getRoot()
      .listMaterials()
      .find((material) => material.getName() === "leaf");
    expect(needles?.getAlphaMode()).toBe("BLEND");
    expect(needles?.getBaseColorTexture()).not.toBeNull();

    const { document, summary } = await cookConifer();
    const cooked = document
      .getRoot()
      .listMaterials()
      .find((material) => material.getName() === "leaf");
    expect(cooked?.getAlphaMode()).toBe("MASK");
    expect(cooked?.getAlphaCutoff()).toBe(0.5);
    // The bark is left exactly as authored: an opaque trunk is not foliage.
    expect(
      document
        .getRoot()
        .listMaterials()
        .find((material) => material.getName() === "bark")
        ?.getAlphaMode(),
    ).toBe("OPAQUE");
    expect(summary.cutout.converted).toEqual(["leaf"]);
    expect(summary.cutout.kept).toEqual([]);
  }, 300_000);

  it("gives the conifer a chain of at least two levels", async () => {
    const { summary } = await cookConifer();
    expect(summary.enabled).toBe(true);
    expect(summary.levels).toBeGreaterThanOrEqual(2);
    // The needles are the reason this PRD exists, and they are no longer refused by *material*:
    // that is the `material-unsupported` lift, proven here and completed by the tripwire below.
    expect(summary.reasons).not.toContain("material-unsupported");
  }, 300_000);

  // The needle cards are the reason this PRD exists. A card is two triangles, so the triangle
  // simplifier declines them `insufficient-reduction` — and a tree is a bark trunk plus needle
  // cards, which used to mean no chain for the tree at all. Cards are now spent in the unit they are
  // authored in: connected components of the index buffer, thinned by a deterministic 3D grid.
  it("thins needle CARDS rather than needle triangles, and keeps the crown covered", async () => {
    const { document, summary } = await cookConifer();
    const needles = summary.primitives.filter((entry) => entry.mesh === "leaves");
    expect(needles.length).toBeGreaterThan(0);
    // Two derived levels on the cards, not one: the chain has to be worth selecting between.
    expect(summary.levels).toBeGreaterThanOrEqual(2);
    for (const entry of needles) {
      expect(entry.strategy).toBe("cards");
      // A card's two triangles are all-or-nothing, so a card level's saving is a whole number of
      // cards. The gate is the same one the triangle chain lives under.
      expect(entry.levels.length).toBeGreaterThanOrEqual(1);
      expect(entry.cardLevels).toHaveLength(entry.levels.length);
      let previous = entry.trianglesBefore;
      for (const [index, level] of (entry.levels ?? []).entries()) {
        expect(level.triangles).toBeLessThan(previous);
        expect((previous - level.triangles) / previous).toBeGreaterThanOrEqual(LOD_MIN_SAVING);
        previous = level.triangles;
        const card = (entry.cardLevels ?? [])[index] as ICardLevelSummary;
        // Every level keeps at least one card, and drops at least one.
        expect(card.cards).toBeGreaterThan(0);
        expect(card.keep).toBeGreaterThan(0);
        // The crown: no occupied cell of LOD0's stratification grid is emptied at any level, which
        // is the property that separates a grid from a random or index-order sample. Cell coverage
        // is the ≥ 70% figure; card *area* coverage cannot be, because `TN_discrete_lod` is
        // index-only and cannot carry the per-level scale step (`cards.ts` says so at the top) — it
        // is the keep ratio up to the per-cell rounding, asserted here so the number cannot drift
        // into a claim it never met.
        expect(card.cellCoverage).toBeGreaterThanOrEqual(0.7);
        expect(card.areaCoverage).toBeCloseTo(card.keep, 1);
      }
    }

    // Read back out of the *shipped* bytes: the cards really are a subset of LOD0's own indices, so
    // a stock loader draws the crown and a level, and the chain validated against the written file.
    const leaves = document
      .getRoot()
      .listMeshes()
      .find((mesh) => mesh.getName() === "leaves");
    const primitive = leaves?.listPrimitives()[0];
    const lod0 = Uint32Array.from(primitive?.getIndices()?.getArray() as ArrayLike<number>);
    const chain = primitive?.getExtension<DiscreteLod>(TN_DISCRETE_LOD);
    expect(chain?.getStrategy()).toBe("cards");
    for (const accessor of chain?.getIndices() ?? []) {
      const level = Uint32Array.from(accessor.getArray() as ArrayLike<number>);
      expect(level.length).toBeGreaterThan(0);
      for (const index of level) expect(lod0).toContain(index);
    }
  }, 300_000);

  it("never drops a primitive or a material, and keeps every level on a LOD0 material", async () => {
    const { document, summary } = await cookConifer();
    const { levels, lod0Materials } = chains(document, summary);
    expect(lod0Materials).toEqual(["bark", "leaf"]);
    expect(levels.length).toBeGreaterThanOrEqual(1);
    for (const level of levels) {
      // A level is an index-only view over LOD0's own vertices, so the card silhouette the cutout
      // depends on is the one LOD0 has and the material it draws is the primitive's own. A chain
      // that crossed to another primitive's material is the needle-loss failure, and this is the
      // assertion that makes it impossible rather than merely unlikely.
      expect(lod0Materials).toContain(level.material);
      expect(level.lod0).toBeGreaterThan(0);
      for (const count of level.counts) expect(count).toBeGreaterThan(0);
    }
    // Nothing was collapsed: both authored primitives and both materials survive the cook.
    expect(
      document
        .getRoot()
        .listMeshes()
        .flatMap((mesh) => mesh.listPrimitives()),
    ).toHaveLength(2);
    expect(
      document
        .getRoot()
        .listMaterials()
        .map((material) => material.getName()),
    ).toEqual(["bark", "leaf"]);
  }, 300_000);

  it("keeps every level at or above the minSaving gate", async () => {
    const { document, summary } = await cookConifer();
    expect(summary.minSaving).toBe(LOD_MIN_SAVING);
    for (const level of chains(document, summary).levels) {
      let previous = level.lod0;
      for (const count of level.counts) {
        expect(count).toBeLessThan(previous);
        expect((previous - count) / previous).toBeGreaterThanOrEqual(LOD_MIN_SAVING);
        previous = count;
      }
    }
  }, 300_000);

  it("ends a card chain in a terminal level at the target without emptying it", async () => {
    // 4,000 quads: LOD0 is 8,000 triangles, so the target is max(1,500, 400) = 1,500. The ratio
    // ladder floors at one card per LOD0 cell and stalls above 1,500; only the terminal level, on a
    // coarser grid, reaches the target.
    const input = await cardsGlb(4_000);
    const result = await modelPass({ compact: false, lod: true, virtual: "none" }).apply(
      input,
      "leaves.glb",
    );
    if (Buffer.isBuffer(result)) throw new Error("the model pass returned an unchanged buffer");
    const summary = result.entry?.lod as IModelLodSummary;
    const entry = summary.primitives[0];
    if (entry === undefined) throw new Error("no card chain");
    const target = Math.max(
      LOD_TERMINAL_MIN_TRIANGLES,
      Math.ceil(LOD_TERMINAL_KEEP_RATIO * entry.trianglesBefore),
    );
    expect(entry.strategy).toBe("cards");
    const terminal = entry.levels.at(-1);
    const card = (entry.cardLevels ?? []).at(-1) as ICardLevelSummary;
    expect(entry.levels.length).toBeGreaterThanOrEqual(2);
    expect(terminal?.triangles ?? 0).toBeLessThanOrEqual(target);
    expect(terminal?.triangles ?? 0).toBeGreaterThan(0);
    expect(terminal?.triangles ?? 0).toBeLessThan(entry.levels.at(-2)?.triangles ?? 0);
    // Never empty: the terminal level drops below the ratio ladder's floor, but every coarse cell
    // it lands on still holds at least one card.
    expect(card.cards).toBeGreaterThan(0);
    expect(card.keep).toBeGreaterThan(0);
    expect(card.cellCoverage).toBeGreaterThan(0);

    // Read back out of the shipped bytes: the terminal is a non-empty subset of LOD0's own indices.
    const document = await readWithLod(result.buffer);
    const primitive = document
      .getRoot()
      .listMeshes()
      .find((mesh) => mesh.getName() === "leaves")
      ?.listPrimitives()[0];
    const lod0 = Uint32Array.from(primitive?.getIndices()?.getArray() as ArrayLike<number>);
    const chain = primitive?.getExtension<DiscreteLod>(TN_DISCRETE_LOD);
    const accessors = chain?.getIndices() ?? [];
    expect(accessors).toHaveLength(entry.levels.length);
    for (const accessor of accessors) {
      const level = Uint32Array.from(accessor.getArray() as ArrayLike<number>);
      expect(level.length).toBeGreaterThan(0);
      for (const index of level) expect(lod0).toContain(index);
    }
  }, 300_000);

  it("leaves the conversion to a per-asset opt-out", async () => {
    const { document, summary } = await cookConifer({ cutout: false });
    expect(summary.cutout.converted).toEqual([]);
    expect(
      document
        .getRoot()
        .listMaterials()
        .find((material) => material.getName() === "leaf")
        ?.getAlphaMode(),
    ).toBe("BLEND");
  }, 300_000);

  it("converts a VEC4 vertex colour that is opaque, refuses a real per-vertex fade", async () => {
    expect((await convertFoliageCutout(vertexAlphaDocument(1))).converted).toEqual(["needles"]);
    const faded = await convertFoliageCutout(vertexAlphaDocument(0.5));
    expect(faded.converted).toEqual([]);
    expect(faded.kept).toEqual([{ name: "needles", reason: "vertex-colour-alpha" }]);
  });

  it("keeps BLEND when texture has no cutout texels (alpha everywhere >= 130), converts when holes exist", async () => {
    const makePngDoc = (alphaVal: number) => {
      const { PNG } = require("pngjs");
      const png = new PNG({ width: 2, height: 2 });
      png.data.fill(255);
      for (let i = 0; i < 4; i += 1) {
        png.data[i * 4 + 3] = alphaVal;
      }
      const pngBuffer = PNG.sync.write(png);
      const document = new Document();
      const buffer = document.createBuffer();
      const texture = document.createTexture("glass").setImage(pngBuffer).setMimeType("image/png");
      const material = document
        .createMaterial("Scope")
        .setAlphaMode("BLEND")
        .setBaseColorTexture(texture);
      const primitive = document
        .createPrimitive()
        .setAttribute(
          "POSITION",
          document.createAccessor().setType("VEC3").setArray(new Float32Array(9)).setBuffer(buffer),
        )
        .setMaterial(material);
      document
        .createScene()
        .addChild(
          document
            .createNode("scope")
            .setMesh(document.createMesh("scope").addPrimitive(primitive)),
        );
      return document;
    };

    // Alpha >= 130 everywhere (cutoff is 0.5 * 255 = 127.5): no cutout texels, stays BLEND
    const translucentDoc = makePngDoc(147);
    const translucentResult = await convertFoliageCutout(translucentDoc);
    expect(translucentResult.converted).toEqual([]);
    expect(translucentResult.kept).toEqual([{ name: "Scope", reason: "no-cutout-texels" }]);
    expect(translucentDoc.getRoot().listMaterials()[0]?.getAlphaMode()).toBe("BLEND");

    // Alpha has cutout holes (e.g. 0): converts to MASK
    const cutoutDoc = makePngDoc(0);
    const cutoutResult = await convertFoliageCutout(cutoutDoc);
    expect(cutoutResult.converted).toEqual(["Scope"]);
    expect(cutoutResult.kept).toEqual([]);
    expect(cutoutDoc.getRoot().listMaterials()[0]?.getAlphaMode()).toBe("MASK");
  });
});

/** A BLEND needle primitive whose VEC4 `COLOR_0` alpha is `alpha` on every vertex. */
function vertexAlphaDocument(alpha: number): Document {
  const document = new Document();
  const buffer = document.createBuffer();
  const material = document
    .createMaterial("needles")
    .setAlphaMode("BLEND")
    .setBaseColorTexture(document.createTexture("base"));
  const count = 3;
  const positions = new Float32Array(count * 3);
  const colors = new Float32Array(count * 4);
  for (let vertex = 0; vertex < count; vertex += 1) colors[vertex * 4 + 3] = alpha;
  const primitive = document
    .createPrimitive()
    .setAttribute(
      "POSITION",
      document.createAccessor().setType("VEC3").setArray(positions).setBuffer(buffer),
    )
    .setAttribute(
      "COLOR_0",
      document.createAccessor().setType("VEC4").setArray(colors).setBuffer(buffer),
    )
    .setMaterial(material);
  document
    .createScene()
    .addChild(
      document
        .createNode("needles")
        .setMesh(document.createMesh("needles").addPrimitive(primitive)),
    );
  return document;
}
