import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { type Document, Logger, NodeIO } from "@gltf-transform/core";
import { ALL_EXTENSIONS } from "@gltf-transform/extensions";
import { MeshoptDecoder } from "meshoptimizer";
import { describe, expect, it } from "vitest";
import { TNDiscreteLod } from "../src/lod/extension.js";
import { type IModelLodSummary, LOD_MIN_SAVING } from "../src/lod/generate.js";
import { type IModelPassOptions, modelPass } from "../src/passes/model.js";
import { TNVirtualGeometry } from "../src/virtual/extension.js";

// PRD-458 AC-4 — a real conifer through the real cook. The fixture is generated by the engine's own
// procedural vegetation exporter (see `foliage-conifer.mjs` beside it): a bark primitive and a
// needle-card primitive whose material ships as `BLEND` with the alpha in its base-colour texture,
// which is the shape every tree pack exports and the case the cook has to recognise.
//
// The failure this guards against is the earlier machinefall LOD1, where collapse decimation threw
// away whole needle and bark materials: a level that does not draw a material is a tree with holes
// in it, and it is invisible in a byte count. So every level is read back out of the *shipped*
// bytes and asserted to draw every LOD0 material, not merely to have fewer triangles.

const SILENT = new Logger(Logger.Verbosity.SILENT);
const FIXTURE = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "fixtures/foliage-conifer.glb",
);

async function readWithLod(root: Buffer): Promise<Document> {
  await MeshoptDecoder.ready;
  const io = new NodeIO()
    .setLogger(SILENT)
    .registerExtensions([...ALL_EXTENSIONS, TNVirtualGeometry, TNDiscreteLod])
    .registerDependencies({ "meshopt.decoder": MeshoptDecoder });
  return io.readJSON(await io.binaryToJSON(root));
}

interface ICooked {
  readonly buffer: Buffer;
  readonly document: Document;
  readonly summary: IModelLodSummary;
}

async function cookConifer(lod: IModelPassOptions["lod"] = true): Promise<ICooked> {
  const input = await readFile(FIXTURE);
  const result = await modelPass({ compact: false, lod, virtual: "none" }).apply(
    input,
    "trees/conifer.glb",
  );
  if (Buffer.isBuffer(result)) throw new Error("the model pass returned an unchanged buffer");
  const summary = result.entry?.lod as IModelLodSummary | undefined;
  if (summary === undefined) throw new Error("the pass produced no lod summary");
  return { buffer: result.buffer, document: await readWithLod(result.buffer), summary };
}

/**
 * Material name per LOD0 primitive, in document order, and each primitive's level triangle counts.
 *
 * The counts come from the pass's own summary, which `validateDiscreteLod` re-checks against the
 * *written* bytes (LOD0 identity, monotonic count/error, index ranges) before the pass returns, so
 * a green assertion here is a statement about the shipped file and not about an in-memory graph.
 */
function chains(
  document: Document,
  summary: IModelLodSummary,
): {
  readonly levels: readonly { counts: number[]; lod0: number; material: string; mesh: string }[];
  readonly lod0Materials: readonly string[];
} {
  const levels: { counts: number[]; lod0: number; material: string; mesh: string }[] = [];
  const lod0Materials: string[] = [];
  for (const mesh of document.getRoot().listMeshes()) {
    for (const [index, primitive] of mesh.listPrimitives().entries()) {
      const material = primitive.getMaterial()?.getName() ?? "";
      lod0Materials.push(material);
      const chain = summary.primitives.find(
        (entry) => entry.mesh === mesh.getName() && entry.primitive === index,
      );
      if (chain === undefined) continue;
      levels.push({
        counts: chain.levels.map((level) => level.triangles),
        lod0: chain.trianglesBefore,
        material,
        mesh: mesh.getName(),
      });
    }
  }
  return { levels, lod0Materials };
}

describe("foliage cutout conversion and LOD (PRD-458 AC-4)", () => {
  it("converts texture-alpha BLEND needles to MASK and reports the conversion", async () => {
    const source = await readWithLod(await readFile(FIXTURE));
    const needles = source
      .getRoot()
      .listMaterials()
      .find((material) => material.getName() === "leaf");
    expect(needles?.getAlphaMode()).toBe("BLEND");
    expect(needles?.getBaseColorTexture()).not.toBeNull();

    const { document, summary } = await cookConifer();
    const cooked = document
      .getRoot()
      .listMaterials()
      .find((material) => material.getName() === "leaf");
    expect(cooked?.getAlphaMode()).toBe("MASK");
    expect(cooked?.getAlphaCutoff()).toBe(0.5);
    // The bark is left exactly as authored: an opaque trunk is not foliage.
    expect(
      document
        .getRoot()
        .listMaterials()
        .find((material) => material.getName() === "bark")
        ?.getAlphaMode(),
    ).toBe("OPAQUE");
    expect(summary.cutout.converted).toEqual(["leaf"]);
    expect(summary.cutout.kept).toEqual([]);
  }, 300_000);

  it("gives the conifer a chain of at least two levels", async () => {
    const { summary } = await cookConifer();
    expect(summary.enabled).toBe(true);
    expect(summary.levels).toBeGreaterThanOrEqual(2);
    // The needles are the reason this PRD exists, and they are no longer refused by *material*:
    // that is the `material-unsupported` lift, proven here and completed by the tripwire below.
    expect(summary.reasons).not.toContain("material-unsupported");
  }, 300_000);

  // OPEN GAP, PRD-458 §4: a needle card is two triangles, and a triangle simplifier cannot drop one
  // without punching a hole in the silhouette, so the leaves are declined `insufficient-reduction`
  // rather than `material-unsupported`. The card-preserving reducer the PRD asks for clusters whole
  // cards (`meshoptimizer.simplifyPoints` with the border locked) instead of decimating them. This
  // expected failure is the tripwire: it goes red the moment the reducer lands, and this case must
  // be deleted in the same commit.
  it.fails(
    "reduces needle CARDS rather than needle triangles",
    async () => {
      const { summary } = await cookConifer();
      const needles = summary.primitives.filter((entry) => entry.mesh === "leaves");
      expect(needles.length).toBeGreaterThan(0);
      for (const entry of needles) expect(entry.levels.length).toBeGreaterThanOrEqual(1);
    },
    300_000,
  );

  it("never drops a primitive or a material, and keeps every level on a LOD0 material", async () => {
    const { document, summary } = await cookConifer();
    const { levels, lod0Materials } = chains(document, summary);
    expect(lod0Materials).toEqual(["bark", "leaf"]);
    expect(levels.length).toBeGreaterThanOrEqual(1);
    for (const level of levels) {
      // A level is an index-only view over LOD0's own vertices, so the card silhouette the cutout
      // depends on is the one LOD0 has and the material it draws is the primitive's own. A chain
      // that crossed to another primitive's material is the needle-loss failure, and this is the
      // assertion that makes it impossible rather than merely unlikely.
      expect(lod0Materials).toContain(level.material);
      expect(level.lod0).toBeGreaterThan(0);
      for (const count of level.counts) expect(count).toBeGreaterThan(0);
    }
    // Nothing was collapsed: both authored primitives and both materials survive the cook.
    expect(
      document
        .getRoot()
        .listMeshes()
        .flatMap((mesh) => mesh.listPrimitives()),
    ).toHaveLength(2);
    expect(
      document
        .getRoot()
        .listMaterials()
        .map((material) => material.getName()),
    ).toEqual(["bark", "leaf"]);
  }, 300_000);

  it("keeps every level at or above the minSaving gate", async () => {
    const { document, summary } = await cookConifer();
    expect(summary.minSaving).toBe(LOD_MIN_SAVING);
    for (const level of chains(document, summary).levels) {
      let previous = level.lod0;
      for (const count of level.counts) {
        expect(count).toBeLessThan(previous);
        expect((previous - count) / previous).toBeGreaterThanOrEqual(LOD_MIN_SAVING);
        previous = count;
      }
    }
  }, 300_000);

  it("leaves the conversion to a per-asset opt-out", async () => {
    const { document, summary } = await cookConifer({ cutout: false });
    expect(summary.cutout.converted).toEqual([]);
    expect(
      document
        .getRoot()
        .listMaterials()
        .find((material) => material.getName() === "leaf")
        ?.getAlphaMode(),
    ).toBe("BLEND");
  }, 300_000);
});
