import { existsSync, readFileSync, realpathSync } from "node:fs";
import path from "node:path";
import { createInterface } from "node:readline";
import { fileURLToPath } from "node:url";

export interface ICapabilityEntry {
  readonly symbol: string;
  readonly package: string;
  readonly importPath: string;
  readonly kind: string;
  readonly signature: string;
  readonly summary: string;
  readonly situations: readonly string[];
  readonly example: string;
  readonly constraints: readonly string[];
  readonly overrides?: readonly string[];
}

export interface ICapabilityManifest {
  readonly version: number;
  readonly entries: readonly ICapabilityEntry[];
}

export interface ICapabilitySearchResult {
  readonly symbol: string;
  readonly importPath: string;
  readonly summary: string;
  readonly example: string;
  readonly constraints: readonly string[];
  readonly matchedSituation: string;
}

export interface ICapabilityDetail extends ICapabilityEntry {}

export interface IEngineTool {
  readonly name: string;
  readonly description: string;
  readonly annotations: {
    readonly destructiveHint: false;
    readonly openWorldHint: false;
    readonly readOnlyHint: true;
  };
  readonly inputSchema: {
    readonly type: "object";
    readonly properties: Record<
      string,
      {
        readonly description?: string;
        readonly enum?: readonly string[];
        readonly type: "string";
      }
    >;
    readonly required: readonly string[];
    readonly additionalProperties: false;
  };
}

export const ENGINE_MCP_TOOL_NAMES = [
  "engine_search_capabilities",
  "engine_capability_detail",
] as const;

const DEFAULT_MANIFEST_FILE = "capabilities.json";
const STOP_WORDS = new Set([
  "a",
  "add",
  "an",
  "and",
  "around",
  "build",
  "by",
  "create",
  "for",
  "from",
  "game",
  "in",
  "into",
  "it",
  "make",
  "of",
  "on",
  "that",
  "the",
  "to",
  "use",
  "with",
]);
const MAX_COMPLETE_REQUEST_RESULTS = 15;
const MAX_SITUATION_RESULTS = 5;
const AUTHORING_INSTRUCTIONS =
  'Before authoring, infer concrete gameplay mechanics. Preserve the request\'s distinctive fantasy: choose the smallest loop that uses its characteristic setting, traversal medium, or simulation instead of a generic character game with themed props, and search those implied mechanics even when the user did not name engine terms. Search the mechanically explicit complete request with scope "request", then each mechanic with scope "mechanic". A genre label alone is not a capability query: clarify or decompose it; do not assume a preset. Inspect capability detail and obey constraints before implementing. Capability detail is authoritative on platform support: never invent a platform limitation it does not state.';

export function defaultManifestPath(cwd = process.cwd()): string {
  const override = process.env.THREENATIVE_CAPABILITIES_MANIFEST;
  if (override !== undefined && override.trim().length > 0) return path.resolve(cwd, override);
  // The manifest that cannot drift is the one shipped inside the installed `@threenative/core`:
  // it is generated by the same build as the engine the project actually runs. A copy committed
  // into a project drifts the moment the engine dependency moves — twenty-four sandbox games had
  // committed copies between 115 and 231 entries against the same engine. Walk up so an MCP host
  // that launches from a nested working directory still finds the project root.
  for (let directory = path.resolve(cwd); ; directory = path.dirname(directory)) {
    const installed = path.join(
      directory,
      "node_modules",
      "@threenative",
      "core",
      "capabilities.json",
    );
    if (existsSync(installed)) return installed;
    const parent = path.dirname(directory);
    if (parent === directory) break;
  }
  // Running from the engine repository itself (the sandbox root's MCP config points straight at
  // `packages/engine-mcp/dist`): answer with the repository's own generated manifest rather than
  // any project's snapshot.
  for (
    let directory = path.dirname(fileURLToPath(import.meta.url));
    ;
    directory = path.dirname(directory)
  ) {
    const repository = path.join(directory, "packages", "core", "capabilities.json");
    if (existsSync(repository)) return repository;
    const parent = path.dirname(directory);
    if (parent === directory) break;
  }
  // Last resort, unchanged from the original default: a bare checkout with a committed copy and
  // no installed engine package.
  return path.resolve(cwd, DEFAULT_MANIFEST_FILE);
}

function manifestError(file: string, reason: string): Error {
  return new Error(`TN_ENGINE_CAPABILITIES_MANIFEST: ${file}: ${reason}`);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function validateManifest(value: unknown, file: string): ICapabilityManifest {
  if (!isRecord(value) || typeof value.version !== "number" || !Array.isArray(value.entries)) {
    throw manifestError(file, "root must contain a numeric version and entries array");
  }
  for (const [index, raw] of value.entries.entries()) {
    // Every field `ICapabilityEntry` declares is checked, `kind` and `example` included. They were
    // the two that were not, and they are the two an authoring agent is handed most directly: a
    // manifest missing `example` validated cleanly and then answered `engine_search_capabilities`
    // with `example: undefined` typed as a string. A capability tool that reports a usage example
    // it does not have is worse than one that refuses to start.
    if (
      !isRecord(raw) ||
      typeof raw.symbol !== "string" ||
      typeof raw.package !== "string" ||
      typeof raw.importPath !== "string" ||
      typeof raw.kind !== "string" ||
      typeof raw.signature !== "string" ||
      typeof raw.summary !== "string" ||
      typeof raw.example !== "string" ||
      !Array.isArray(raw.situations) ||
      !Array.isArray(raw.constraints) ||
      !raw.situations.every((situation) => typeof situation === "string") ||
      !raw.constraints.every((constraint) => typeof constraint === "string")
    ) {
      throw manifestError(file, `entry ${index} is malformed`);
    }
  }
  return value as unknown as ICapabilityManifest;
}

export function loadCapabilityManifest(file = defaultManifestPath()): ICapabilityManifest {
  let raw: string;
  try {
    raw = readFileSync(file, "utf8");
  } catch (error) {
    throw manifestError(file, `cannot read committed manifest: ${String(error)}`);
  }
  try {
    return validateManifest(JSON.parse(raw) as unknown, file);
  } catch (error) {
    if (error instanceof Error && error.message.startsWith("TN_ENGINE_CAPABILITIES_MANIFEST:"))
      throw error;
    throw manifestError(file, `cannot parse JSON: ${String(error)}`);
  }
}

function tokens(value: string): string[] {
  return value
    .toLocaleLowerCase()
    .split(/[^a-z0-9]+/u)
    .filter((token) => token.length > 1 && !STOP_WORDS.has(token))
    .map((token) => {
      if (token.length > 4 && token.endsWith("ies")) return `${token.slice(0, -3)}y`;
      if (token.length > 3 && token.endsWith("s") && !token.endsWith("ss"))
        return token.slice(0, -1);
      return token;
    });
}

function situationScore(
  query: readonly string[],
  situations: readonly string[],
): { readonly matchedSituation: string; readonly score: number } {
  if (query.length === 0) return { matchedSituation: "", score: 0 };
  const queryText = query.join(" ");
  let best = 0;
  let matchedSituation = "";
  for (const situation of situations) {
    const phrase = tokens(situation);
    const overlap = new Set(phrase.filter((token) => query.includes(token))).size;
    const score = overlap / Math.max(query.length, phrase.length);
    const phraseBonus =
      phrase.join(" ").includes(queryText) || queryText.includes(phrase.join(" ")) ? 1 : 0;
    if (overlap < (query.length >= 4 ? 2 : 1) && phraseBonus === 0) continue;
    const candidate = score + phraseBonus;
    if (candidate > best) {
      best = candidate;
      matchedSituation = situation;
    }
  }
  return { matchedSituation, score: best };
}

function capabilitySearchKey(entry: ICapabilityEntry): string {
  // One export declaration can expose a primary helper plus inspection aliases. The manifest
  // correctly keeps every public symbol for detail lookup, but returning the same declaration
  // twice wastes a broad authoring search slot. Import path + signature + authored docs identify
  // equivalent aliases without conflating distinct APIs that happen to share documentation.
  return `${entry.importPath}\n${entry.signature}\n${entry.summary}\n${entry.situations.join("\n")}`;
}

export function searchCapabilities(
  situation: string,
  manifestFile = defaultManifestPath(),
  scope: "mechanic" | "request" = "mechanic",
): readonly ICapabilitySearchResult[] {
  if (typeof situation !== "string" || situation.trim().length === 0)
    throw new Error("engine_search_capabilities requires a non-empty situation string.");
  const manifest = loadCapabilityManifest(manifestFile);
  const query = tokens(situation);
  const limit = scope === "request" ? MAX_COMPLETE_REQUEST_RESULTS : MAX_SITUATION_RESULTS;
  return manifest.entries
    .map((entry) => ({ entry, ...situationScore(query, entry.situations) }))
    .filter(({ score }) => score > 0)
    .sort(
      (left, right) =>
        right.score - left.score ||
        `${left.entry.importPath}:${left.entry.symbol}`.localeCompare(
          `${right.entry.importPath}:${right.entry.symbol}`,
        ),
    )
    .filter(
      (candidate, index, candidates) =>
        candidates.findIndex(
          (other) => capabilitySearchKey(other.entry) === capabilitySearchKey(candidate.entry),
        ) === index,
    )
    .slice(0, limit)
    .map(({ entry, matchedSituation }) => ({
      constraints: entry.constraints,
      example: entry.example,
      importPath: entry.importPath,
      matchedSituation,
      summary: entry.summary,
      symbol: entry.symbol,
    }));
}

export function capabilityDetail(
  symbol: string,
  manifestFile = defaultManifestPath(),
): ICapabilityDetail {
  if (typeof symbol !== "string" || symbol.trim().length === 0)
    throw new Error("engine_capability_detail requires a non-empty symbol string.");
  const manifest = loadCapabilityManifest(manifestFile);
  const entry = manifest.entries.find((candidate) => candidate.symbol === symbol);
  if (entry === undefined) throw new Error(`Unknown engine capability '${symbol}'.`);
  return entry;
}

const TOOL_DEFINITIONS: readonly IEngineTool[] = [
  {
    annotations: { destructiveHint: false, openWorldHint: false, readOnlyHint: true },
    name: "engine_search_capabilities",
    description:
      'Search the installed engine by concrete gameplay mechanic. Decompose genres first. Use scope "request" for the mechanically explicit full request and "mechanic" for each focused search; matchedSituation explains every result.',
    inputSchema: {
      additionalProperties: false,
      properties: {
        scope: {
          description:
            "Use request for the complete cross-system game request; use mechanic or omit it for one mechanic.",
          enum: ["request", "mechanic"],
          type: "string",
        },
        situation: { type: "string" },
      },
      required: ["situation"],
      type: "object",
    },
  },
  {
    annotations: { destructiveHint: false, openWorldHint: false, readOnlyHint: true },
    name: "engine_capability_detail",
    description:
      "Inspect one engine capability's import, signature, example, constraints, and overrides.",
    inputSchema: {
      additionalProperties: false,
      properties: { symbol: { type: "string" } },
      required: ["symbol"],
      type: "object",
    },
  },
];

export function toolDefinitions(): readonly IEngineTool[] {
  return TOOL_DEFINITIONS;
}

function jsonRpcError(id: unknown, code: number, message: string): string {
  return JSON.stringify({ id, jsonrpc: "2.0", error: { code, message } });
}

function jsonRpcResult(id: unknown, result: unknown): string {
  return JSON.stringify({ id, jsonrpc: "2.0", result });
}

function writeLine(value: string): void {
  process.stdout.write(`${value}\n`);
}

function toolText(value: unknown): { content: [{ type: "text"; text: string }] } {
  return { content: [{ text: JSON.stringify(value, null, 2), type: "text" }] };
}

function handleToolCall(
  params: Record<string, unknown>,
  manifestFile: string,
): { content: [{ type: "text"; text: string }] } {
  const name = params.name;
  const argumentsValue = isRecord(params.arguments) ? params.arguments : {};
  // The raw value goes to the validator, never through String(): a numeric or null argument
  // must come back as a tool error the authoring agent can read, not a vacuous empty search
  // that looks like the engine having no such capability.
  if (name === "engine_search_capabilities") {
    if (typeof argumentsValue.situation !== "string")
      throw new Error("engine_search_capabilities requires a string 'situation' argument.");
    const scope = argumentsValue.scope ?? "mechanic";
    if (scope !== "request" && scope !== "mechanic")
      throw new Error("engine_search_capabilities scope must be 'request' or 'mechanic'.");
    return toolText(searchCapabilities(argumentsValue.situation, manifestFile, scope));
  }
  if (name === "engine_capability_detail") {
    if (typeof argumentsValue.symbol !== "string")
      throw new Error("engine_capability_detail requires a string 'symbol' argument.");
    return toolText(capabilityDetail(argumentsValue.symbol, manifestFile));
  }
  throw new Error(`Unknown engine MCP tool '${String(name)}'.`);
}

/**
 * Handles one raw stdin line and returns the JSON-RPC response to write, or `undefined` when the
 * line must be consumed silently. Extracted so the stdio contract is testable without a live
 * `process.stdin`: this framing is the whole surface an authoring agent's MCP client speaks.
 */
export function handleLine(line: string, manifestFile: string): string | undefined {
  if (line.trim().length === 0) return undefined;
  let request: unknown;
  try {
    request = JSON.parse(line) as unknown;
  } catch (error) {
    return jsonRpcError(null, -32700, `Invalid JSON: ${String(error)}`);
  }
  if (!isRecord(request) || request.id === undefined || typeof request.method !== "string")
    return undefined;
  try {
    if (request.method === "initialize") {
      return jsonRpcResult(request.id, {
        capabilities: { tools: { listChanged: false } },
        instructions: AUTHORING_INSTRUCTIONS,
        protocolVersion: "2025-06-18",
        serverInfo: { name: "threenative-engine-mcp", version: "0.2.0" },
      });
    }
    if (request.method === "tools/list") {
      return jsonRpcResult(request.id, { tools: TOOL_DEFINITIONS });
    }
    if (request.method === "tools/call") {
      if (!isRecord(request.params)) throw new Error("tools/call requires an object params value.");
      return jsonRpcResult(request.id, handleToolCall(request.params, manifestFile));
    }
    return jsonRpcError(request.id, -32601, `Method not found: ${request.method}`);
  } catch (error) {
    return jsonRpcError(request.id, -32000, error instanceof Error ? error.message : String(error));
  }
}

export function runServer(manifestFile = defaultManifestPath()): void {
  // Load before accepting requests. A missing manifest is a startup failure, never an empty tool
  // response that an authoring agent could mistake for the engine having no capabilities.
  loadCapabilityManifest(manifestFile);
  const input = createInterface({ input: process.stdin });
  input.on("line", (line) => {
    const response = handleLine(line, manifestFile);
    if (response !== undefined) writeLine(response);
  });
}

const entryPath = process.argv[1];
if (
  entryPath !== undefined &&
  realpathSync(path.resolve(entryPath)) === realpathSync(fileURLToPath(import.meta.url))
) {
  try {
    runServer();
  } catch (error) {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  }
}
