import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'vitest';

import {
  collectReceipts,
  generateAll,
  generateLicenseInventory,
  lockHash,
  readLock,
} from '../scripts/generate-native-sbom.mjs';

test('should generate a complete deterministic CycloneDX document from the real lock', () => {
  // PRD-059 Phase 2 native-sbom gate. Every lock component appears exactly once
  // by package URL; every payload SHA/source revision is reachable; two runs
  // are byte-identical; no timestamp or absolute workstation path exists.
  const { sbom } = generateAll();
  const first = sbom;
  const { sbom: second } = generateAll();
  assert.equal(first, second, 'two runs must be byte-identical');
  assert.ok(!/\d{4}-\d{2}-\d{2}T\d{2}:/u.test(first), 'no timestamp in SBOM');
  assert.ok(!first.includes('/home/') && !first.includes('C:\\'), 'no absolute workstation path in SBOM');
  const document = JSON.parse(first);
  assert.equal(document.bomFormat, 'CycloneDX');
  assert.equal(document.specVersion, '1.5');
  const lock = readLock();
  const expectedPayloads = lock.components.flatMap((component) => component.payloads.map((payload) => payload.id)).sort();
  const actualRefs = document.components.map((component) => component['bom-ref']).sort();
  assert.deepEqual(actualRefs, expectedPayloads);
  // Negative control: remove one component after generation; the check below
  // (and --check in CI) exits nonzero and names it — exercised here by
  // asserting the shrunken document no longer covers the lock.
  const shrunken = { ...document, components: document.components.slice(1) };
  assert.ok(shrunken.components.length < actualRefs.length);
});

test('should fail when license evidence is absent changed or orphaned', async () => {
  // PRD-059 Phase 2 native-license-inventory gate. Set equality between lock
  // components and inventory components; exact SPDX/evidence match.
  const lock = readLock();
  const inventory = generateLicenseInventory(lock);
  assert.equal(inventory.components.length, lock.components.length);
  for (const row of inventory.components) {
    assert.ok(row.spdx.length > 0 && row.evidenceUrl.length > 0 && row.sourceRevision.length > 0);
    assert.ok(row.payloads.length > 0);
  }
  // Negative control: change one license tuple without regenerating; the
  // generator run against the mutated lock produces different bytes, so
  // --check against the old output fails.
  const mutated = JSON.parse(JSON.stringify(lock));
  mutated.components[0].license.spdx = 'CHANGED-0.0';
  const { generateLicenseInventory: regen } = await import('../scripts/generate-native-sbom.mjs');
  assert.notDeepEqual(regen(mutated), inventory);
});

test('should refuse stale acquisition receipts', async () => {
  // A receipt written against a different lock hash is stale evidence, not a
  // passing input: collection with an expected hash rejects it by name.
  const root = mkdtempSync(join(tmpdir(), 'threenative-sbom-receipt-'));
  try {
    const { mkdirSync } = await import('node:fs');
    mkdirSync(join(root, 'wgpu', '.threenative-receipts'), { recursive: true });
    writeFileSync(
      join(root, 'wgpu', '.threenative-receipts', 'receipt.json'),
      JSON.stringify({ lockHash: 'stale', payloads: [] }),
    );
    assert.throws(() => collectReceipts(root, 'current'), /TN_NATIVE_SBOM_RECEIPT_STALE.*wgpu/);
  } finally {
    rmSync(root, { force: true, recursive: true });
  }
});

test('should expose deterministic generation through the CLI', () => {
  // --check compares regenerated bytes with supplied outputs; tested here
  // through the real CLI entrypoint, not the imported functions.
  const script = join(import.meta.dirname, '..', 'scripts', 'generate-native-sbom.mjs');
  const out = execFileSync(process.execPath, [script, '--out', `${tmpdir()}/threenative-sbom-cli-${process.pid}`], { encoding: 'utf8' });
  assert.match(out, /Wrote SBOM/);
  void lockHash;
  void readFileSync;
});
