// PRD-449 Phase 1 — the `godot-lights-meshes` `benchmark_box_1000` canonical fixture: the bytes are
// the ones Godot produced, the identity is the SHA-256 of those bytes, and a change to object 10 is
// rejected. The fixture itself was generated by Godot (see the sibling README); this file only
// checks it, and fails closed on a missing or wrong count, an unknown field, or a real that is not
// the exact 17-decimal form of the binary64 a consumer reads.
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { describe, expect, it } from "vitest";

const root = resolve(import.meta.dirname, "../..");
const FIXTURE_DIR = join(root, "benchmark/engine-load-test/godot-lights-meshes");
const FIXTURE_PATH = join(FIXTURE_DIR, "benchmark_box_1000.json");
const SIDECAR_PATH = `${FIXTURE_PATH}.sha256`;
const sourceLock = JSON.parse(
  readFileSync(join(root, "benchmark/engine-load-test/sources.lock.json"), "utf8"),
) as Json;

/** The counts the pinned source's `create_scattered` actually builds, not the ones it requests. */
const ACTUAL_MESH_INSTANCES = 1024;
const ACTUAL_SPOT_LIGHTS = 9;
const TOTAL_NODES = 2082;

const TOP_LEVEL_KEYS = [
  "behavior",
  "census",
  "counts",
  "deviations",
  "encoding",
  "fixtureId",
  "nodes",
  "notClaimed",
  "produced",
  "resources",
  "rng",
  "schema",
  "schemaVersion",
  "source",
  "upstreamBehavior",
];
const NODE_KEYS = [
  "behaviorRef",
  "cameraRef",
  "cellCount",
  "class",
  "environmentRef",
  "grid",
  "id",
  "instanceDefaultsRef",
  "lightRef",
  "local",
  "meshRef",
  "parent",
  "phase",
  "role",
  "rotates",
  "scriptProperties",
  "speed",
  "world",
];
const SECTION_KEYS: Record<string, readonly string[]> = {
  behavior: [
    "frameSchedule",
    "gridRotaters",
    "lighters",
    "lighterPerFrame",
    "oppositeRotation",
    "sceneSpeed",
    "sceneSpeedNote",
    "verificationOracle",
  ],
  census: ["byNativeClass", "nodesIncludingRoot", "note"],
  "counts.actual": ["lightCells", "meshCells", "meshInstances", "spotLights"],
  "counts.gridSide": ["formula", "lightCells", "meshCells"],
  "counts.requested": ["lights", "objects"],
  counts: ["actual", "censusNote", "gridSide", "requested", "rule"],
  encoding: [
    "buffers",
    "byteOrder",
    "file",
    "floatPrecision",
    "integers",
    "nodeOrder",
    "objectIds",
    "scalars",
    "transform",
  ],
  produced: ["command", "godotBuild", "godotEngineCommit", "godotVersion", "producer"],
  "resources.mesh": [
    "class",
    "id",
    "instanceMaterialOverride",
    "parameters",
    "shared",
    "surface0",
    "surfaceCount",
  ],
  "resources.light": [
    "class",
    "engineDefaultsNotSetBySource",
    "id",
    "initialEnergy",
    "initialEnergyNote",
    "properties",
    "setByPinnedSource",
    "shadowNote",
    "shared",
  ],
  "resources.surface0": [
    "bounds",
    "buffers",
    "indexCount",
    "materialBinding",
    "primitive",
    "primitiveNote",
    "vertexCount",
  ],
};
const NODE_ROLES = [
  "camera",
  "light",
  "lightCell",
  "lightGrid",
  "lightGridRotater",
  "lightHolder",
  "meshCell",
  "meshGrid",
  "meshGridRotater",
  "meshModel",
  "sceneRoot",
  "worldEnvironment",
];

type Json = Record<string, unknown>;

const raw = readFileSync(FIXTURE_PATH, "utf8");
const sidecar = readFileSync(SIDECAR_PATH, "utf8");
const fixture = JSON.parse(raw) as Json;
const nodes = fixture.nodes as Json[];
const sha256 = (data: string | Buffer): string =>
  createHash("sha256")
    .update(typeof data === "string" ? Buffer.from(data, "utf8") : data)
    .digest("hex");

/** The fixture's bytes are exactly the canonical 2-space JSON of their own content, so a changed
 *  byte is a changed fact and never a reformatting. This is what makes the mutation test below
 *  exact instead of approximate. */
const canonical = (value: unknown): string => `${JSON.stringify(value, null, 2)}\n`;

/** Every real in the fixture is a string in the `%.17f` form Godot wrote. JS `Number` is correctly
 *  rounded, so re-formatting it at 17 decimals reproduces the same text: the string is the exact
 *  decimal of the binary64 any consumer parses out of it. The one tolerated difference is an exact
 *  tie, where C `printf` rounds half-to-even and `toFixed` rounds half-up; both spellings then name
 *  the same double, which is the only thing that can differ and is checked to be so. Godot's own
 *  parser cannot prove any of this: `String::to_float` accumulates and can land a ULP away. */
function expectExactReal(value: unknown, where: string): number {
  if (typeof value !== "string")
    throw new Error(`${where}: ${JSON.stringify(value)} is not a real string`);
  if (!/^-?\d+\.\d{17}$/u.test(value)) throw new Error(`${where}: ${value} is not a "%.17f" real`);
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) throw new Error(`${where}: ${value} is not finite`);
  const seventeen = parsed.toFixed(17);
  if (seventeen !== value && Number(seventeen) !== parsed)
    throw new Error(
      `${where}: ${value} is not the 17-decimal form of ${parsed}, which is ${seventeen}`,
    );
  return parsed;
}

function expectKeys(value: Json, allowed: readonly string[], where: string): void {
  for (const key of Object.keys(value))
    if (!allowed.includes(key)) throw new Error(`${where}: unsupported field ${key}`);
}

/** A transform is {origin:[3], basis:{x:[3],y:[3],z:[3]}} of exact reals. */
function expectTransform(value: unknown, where: string): void {
  const transform = value as Json;
  expectKeys(transform, ["basis", "origin"], where);
  const origin = transform.origin as unknown[];
  if (!Array.isArray(origin) || origin.length !== 3)
    throw new Error(`${where}.origin is not three reals`);
  for (const [index, component] of origin.entries())
    expectExactReal(component, `${where}.origin[${index}]`);
  const basis = transform.basis as Json;
  expectKeys(basis, ["x", "y", "z"], `${where}.basis`);
  for (const axis of ["x", "y", "z"] as const) {
    const column = basis[axis] as unknown[];
    if (!Array.isArray(column) || column.length !== 3)
      throw new Error(`${where}.basis.${axis} is not three reals`);
    for (const [index, component] of column.entries())
      expectExactReal(component, `${where}.basis.${axis}[${index}]`);
  }
}

/** The fail-closed reader. Every gate a later native adapter needs before it may trust a fixture:
 *  no unknown fields, no missing fields, the exact counts, a closed id/parent graph, and reals that
 *  survive a round trip. Throws on the first violation. */
function validateLightsMeshesFixture(value: Json): Json {
  expectKeys(value, TOP_LEVEL_KEYS, "fixture");
  if (value.schema !== "threenative.godot-lights-meshes.fixture")
    throw new Error(`fixture: unknown schema ${String(value.schema)}`);
  if (value.schemaVersion !== 1)
    throw new Error(`fixture: unknown schemaVersion ${String(value.schemaVersion)}`);

  for (const [name, keys] of Object.entries(SECTION_KEYS))
    if (!name.includes(".")) expectKeys(value[name] as Json, keys, `fixture.${name}`);

  const source = value.source as Json;
  expectKeys(
    source,
    [
      "commit",
      "entryPoint",
      "family",
      "projectGodot",
      "projectGodotGitBlobSha1",
      "repo",
      "script",
      "scriptBytes",
      "scriptGitBlobSha1",
      "scriptSha256",
    ],
    "fixture.source",
  );
  if (source.commit !== "b059e38a81230a87293828bbf65ab247b6b2d2a8")
    throw new Error(`fixture.source: commit is ${String(source.commit)}`);
  if (source.scriptGitBlobSha1 !== "e9ded113e727529965fcc172d23062e0e13948a7")
    throw new Error(`fixture.source: script blob sha1 is ${String(source.scriptGitBlobSha1)}`);
  if (!/^[0-9a-f]{64}$/u.test(String(source.scriptSha256)))
    throw new Error("fixture.source: scriptSha256 is not 64 lowercase hex characters");
  const produced = value.produced as Json;
  if (!/^4\.7\.1\.stable\.official\./u.test(String(produced.godotVersion)))
    throw new Error(`fixture.produced: unexpected Godot ${String(produced.godotVersion)}`);

  const counts = value.counts as Json;
  const requested = counts.requested as Json;
  expectKeys(counts, SECTION_KEYS.counts as string[], "fixture.counts");
  expectKeys(requested, SECTION_KEYS["counts.requested"] as string[], "fixture.counts.requested");
  if (requested.objects !== 1000 || requested.lights !== 10)
    throw new Error(
      `fixture.counts.requested: ${String(requested.objects)}/${String(requested.lights)} is not 1000/10`,
    );
  const actual = counts.actual as Json;
  expectKeys(actual, SECTION_KEYS["counts.actual"] as string[], "fixture.counts.actual");
  expectKeys(
    counts.gridSide as Json,
    SECTION_KEYS["counts.gridSide"] as string[],
    "fixture.counts.gridSide",
  );
  if (actual.meshInstances !== ACTUAL_MESH_INSTANCES)
    throw new Error(`fixture.counts.actual.meshInstances is ${String(actual.meshInstances)}`);
  if (actual.spotLights !== ACTUAL_SPOT_LIGHTS)
    throw new Error(`fixture.counts.actual.spotLights is ${String(actual.spotLights)}`);

  const nodeList = value.nodes;
  if (!Array.isArray(nodeList) || nodeList.length !== TOTAL_NODES)
    throw new Error(`fixture.nodes: ${String(nodeList)} is not ${TOTAL_NODES} nodes`);
  const byId = new Map<string, Json>();
  for (const [index, node] of nodeList.entries()) {
    const where = `fixture.nodes[${index}]`;
    expectKeys(node, NODE_KEYS, where);
    const id = String(node.id);
    if (byId.has(id)) throw new Error(`${where}: duplicate id ${id}`);
    byId.set(id, node);
  }
  for (const [index, node] of nodeList.entries()) {
    const where = `fixture.nodes[${index}] (${String(node.id)})`;
    if (!NODE_ROLES.includes(String(node.role)))
      throw new Error(`${where}: unsupported role ${String(node.role)}`);
    const parent = node.parent;
    if (index === 0) {
      if (node.id !== "" || parent !== null)
        throw new Error(`${where}: the first node must be the root with a null parent`);
    } else {
      if (typeof parent !== "string" || !byId.has(parent))
        throw new Error(`${where}: parent ${String(parent)} is not a node in this fixture`);
    }
    if (node.local === undefined || node.world === undefined) {
      if (node.class !== "WorldEnvironment") throw new Error(`${where}: a transform is missing`);
    } else {
      expectTransform(node.local, `${where}.local`);
      expectTransform(node.world, `${where}.world`);
    }
    if (typeof node.speed === "string") expectExactReal(node.speed, `${where}.speed`);
    if (typeof node.phase === "string") expectExactReal(node.phase, `${where}.phase`);
  }

  const meshModels = nodeList.filter((node) => node.role === "meshModel");
  if (meshModels.length !== ACTUAL_MESH_INSTANCES)
    throw new Error(`fixture.nodes: ${meshModels.length} meshModel nodes, expected 1024`);
  const lights = nodeList.filter((node) => node.role === "light");
  if (lights.length !== ACTUAL_SPOT_LIGHTS)
    throw new Error(`fixture.nodes: ${lights.length} light nodes, expected 9`);
  for (const light of lights)
    if (light.class !== "SpotLight3D")
      throw new Error(`fixture.nodes: ${String(light.id)} is ${String(light.class)}`);

  const behavior = value.behavior as Json;
  const rotaters = behavior.gridRotaters as Json[];
  const directions = rotaters.map((rotater) => Number(rotater.speed));
  if (
    directions.length !== 2 ||
    directions[0] === undefined ||
    directions[1] === undefined ||
    directions[0] === directions[1] ||
    directions[0] * directions[1] > 0
  )
    throw new Error(`fixture.behavior.gridRotaters: speeds ${directions} are not opposite`);
  const lighters = behavior.lighters as Json[];
  if (lighters.length !== ACTUAL_SPOT_LIGHTS)
    throw new Error(`fixture.behavior.lighters: ${lighters.length}, expected 9`);
  for (const [index, lighter] of lighters.entries())
    expectExactReal(lighter.phase, `fixture.behavior.lighters[${index}].phase`);

  const resources = value.resources as Json[];
  if (resources.length !== 5)
    throw new Error(`fixture.resources: ${resources.length} entries, expected 5`);
  const mesh = resources.find((entry) => entry.id === "mesh:box-1k");
  if (mesh === undefined) throw new Error("fixture.resources: no mesh:box-1k entry");
  expectKeys(mesh, SECTION_KEYS["resources.mesh"] as string[], "fixture.resources.mesh:box-1k");
  const light = resources.find((entry) => entry.id === "light:spot-9");
  if (light === undefined) throw new Error("fixture.resources: no light:spot-9 entry");
  expectKeys(light, SECTION_KEYS["resources.light"] as string[], "fixture.resources.light:spot-9");
  if ((light.initialEnergy as string) !== "5.00000000000000000")
    throw new Error(
      `fixture.resources.light:spot-9 initial energy is ${String(light.initialEnergy)}`,
    );
  const surface = mesh.surface0 as Json;
  expectKeys(
    surface,
    SECTION_KEYS["resources.surface0"] as string[],
    "fixture.resources.mesh:box-1k.surface0",
  );
  if (surface.vertexCount !== 24 || surface.indexCount !== 36)
    throw new Error(
      `fixture.resources: box surface is ${String(surface.vertexCount)}/${String(surface.indexCount)} vertices/indices`,
    );
  for (const [name, buffer] of Object.entries(surface.buffers as Json)) {
    const record = buffer as Json;
    if (record.encoding !== "base64")
      throw new Error(`fixture.resources.buffers.${name}: encoding`);
    const bytes = Buffer.from(String(record.data), "base64");
    if (bytes.length !== record.bytes)
      throw new Error(
        `fixture.resources.buffers.${name}: ${bytes.length} bytes, not ${String(record.bytes)}`,
      );
    if (sha256(bytes) !== record.sha256)
      throw new Error(`fixture.resources.buffers.${name}: sha256 does not cover these bytes`);
  }
  return value;
}

describe("PRD-449 godot-lights-meshes canonical fixture", () => {
  it("is byte-identical to the canonical JSON of its own content, so its SHA-256 is its identity", () => {
    expect(canonical(fixture)).toBe(raw);
  });

  it("hashes to the SHA-256 recorded beside it, in sha256sum format", () => {
    expect(`${sha256(raw)}  benchmark_box_1000.json\n`).toBe(sidecar);
  });

  it("records the pinned upstream source identity from the tracked lock", () => {
    validateLightsMeshesFixture(fixture);
    const source = fixture.source as Json;
    const godot = (sourceLock.inputs as Json).godotBenchmarks as Json;
    const paths = godot.requiredPaths as Json[];
    const pinned = paths.find(
      (entry) => entry.path === "benchmarks/rendering/lights_and_meshes.gd",
    );
    expect(pinned).toBeDefined();
    expect(source.commit).toBe((godot.pin as Json).commit);
    expect(source.scriptSha256).toBe(pinned?.sha256);
    expect(source.scriptGitBlobSha1).toBe(pinned?.gitBlobSha1);
    expect(source.scriptBytes).toBe(pinned?.bytes);
  });

  it("declares precision, byte order and the one adaptation, and claims nothing it did not measure", () => {
    const encoding = fixture.encoding as Json;
    for (const key of ["buffers", "byteOrder", "file", "floatPrecision", "objectIds", "scalars"])
      expect(encoding[key]).toBeTypeOf("string");
    expect(encoding.byteOrder).toContain("little-endian");
    expect(encoding.scalars).toContain("%.17f");
    const deviations = fixture.deviations as Json[];
    expect(deviations.map((entry) => entry.kind)).toContain("deterministicSeeding");
    expect((fixture.rng as Json).seed).toBe(20260927);
    const notClaimed = (fixture.notClaimed as unknown[]).join(" ");
    expect(notClaimed).toContain("No cross-engine equivalence");
    expect(notClaimed).toContain("No speed");
  });

  it("rejects an unknown field, a wrong count and a real that lost its digits", () => {
    const unknown = structuredClone(fixture) as Json;
    (unknown.counts as Json).surprise = 1;
    expect(() => validateLightsMeshesFixture(unknown)).toThrow(/unsupported field surprise/u);

    const miscounted = structuredClone(fixture) as Json;
    const actual = (miscounted.counts as Json).actual as Json;
    actual.meshInstances = 1000;
    (miscounted.nodes as Json[]).splice(24, 1);
    expect(() => validateLightsMeshesFixture(miscounted)).toThrow(/meshInstances is 1000/u);

    // A real that came back through a float formatter instead of the fixture's encoding.
    const firstModel = nodes.find((node) => node.role === "meshModel") as Json;
    const origin = ((firstModel.world as Json).origin as string[])[0] as string;
    expect(() => expectExactReal(Number(origin), "world origin x")).toThrow(
      /is not a real string/u,
    );
    expect(() => expectExactReal("0.9680910110473633", "world origin x")).toThrow(
      /is not a "%\.17f" real/u,
    );
    expect(() => expectExactReal("NaN", "world origin x")).toThrow(/is not a "%\.17f" real/u);
  });

  it("rejects a change to object 10 that a first-eight-placement hash cannot see", () => {
    // The legacy gate: eight placements, hashed. Object 10 is invisible to it by construction.
    const firstEight = (value: Json): string =>
      sha256(
        (value.nodes as Json[])
          .filter((node) => node.role === "meshModel")
          .slice(0, 8)
          .map((node) => JSON.stringify((node.world as Json).origin))
          .join("|"),
      );

    const mutated = structuredClone(fixture) as Json;
    const meshModels = (mutated.nodes as Json[]).filter((node) => node.role === "meshModel");
    const tenth = meshModels[10] as Json;
    expect(tenth.id).toBe("1/0/10/0");
    const origin = (tenth.world as Json).origin as string[];
    origin[0] = "0.00000000000000001";

    expect(firstEight(mutated)).toBe(firstEight(fixture));
    expect(canonical(mutated)).not.toBe(raw);
    expect(sha256(canonical(mutated))).not.toBe(sha256(raw));
    expect(`${sha256(canonical(mutated))}  benchmark_box_1000.json\n`).not.toBe(sidecar);
  });
});
