import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { publicWorkspacePackages } from "./workspace-packages.js";

/**
 * The stable-API contract (PRD-446 phase 1). `capabilities.json` is regenerated by `pnpm build`,
 * so it cannot notice a symbol that disappeared — the removal is simply absent from the new
 * manifest. This snapshot is the committed copy a public surface is compared against: a removed
 * export subpath, a removed symbol or a changed signature is red unless `CHANGELOG.md` carries a
 * `Breaking` entry naming it, and `--update` is the deliberate act that re-records the surface.
 *
 * Both halves are reused, not rebuilt: the published package list and its export subpaths come
 * from `workspace-packages.ts`, and the symbols and their signatures come from the capability
 * manifest, which already walks every exported class and function of every walked package.
 */

const REPO = path.resolve(import.meta.dirname, "..");
export const API_SURFACE_RELATIVE_PATH = path.join("scripts", "api-surface.json");
const MANIFEST_RELATIVE_PATH = path.join("packages", "create-threenative", "capabilities.json");
const CHANGELOG_RELATIVE_PATH = "CHANGELOG.md";
const BULLET = /^\s*[-*]\s/u;
/** A version heading — `## [Unreleased]`, `## [0.3.3] - unreleased (release candidate)`, `## [0.3.2] - 2026-09-12`. */
const VERSION_HEADING = /^##\s+\[[^\]]+\]/u;
/** A release date, which is what makes a version section published history rather than the next release. */
const RELEASE_DATE = /\d{4}-\d{2}-\d{2}/u;
/** Hyphens included so an export subpath like `./web-brand` is a name a changelog can carry. */
const IDENTIFIER = /[A-Za-z_$][\w$-]*/gu;
/**
 * A dotted member path, as the surface records a config member: `renderer.projection`. `IDENTIFIER`
 * splits at the dot, so without this a nested member — a symbol the surface can report as changed —
 * could be named by no changelog entry at all, and its first change would be unannounceable.
 */
const MEMBER_PATH = /[A-Za-z_$][\w$]*(?:\.[A-Za-z_$][\w$]*)+/gu;
/**
 * Whole package names, which `IDENTIFIER` splits at the scope separator. Greedy, so
 * `@threenative/gone-extra` is collected whole and never answers for `@threenative/gone`; the two
 * unscoped families are listed because three published packages carry no scope.
 */
const PACKAGE_NAME = /@[\w-]+\/[\w-]+|create-threenative|threenative-[\w-]+-mcp/gu;

export interface IApiSurfacePackage {
  /** Export-map subpaths; `.` is the root conditional export, and none is a manifest with no `exports`. */
  readonly exports: readonly string[];
  /** `importPath#symbol` → the signature string the manifest derived from the source. */
  readonly symbols: Readonly<Record<string, string>>;
}

export interface IApiSurface {
  readonly packages: Readonly<Record<string, IApiSurfacePackage>>;
}

interface IDriftedSymbol {
  readonly key: string;
  readonly symbol: string;
}

export interface IApiSurfaceDrift {
  readonly changed: readonly IDriftedSymbol[];
  readonly removedSubpaths: readonly { readonly package: string; readonly subpath: string }[];
  readonly removedSymbols: readonly IDriftedSymbol[];
}

interface IMutableDrift {
  changed: IDriftedSymbol[];
  removedSubpaths: { package: string; subpath: string }[];
  removedSymbols: IDriftedSymbol[];
}

interface IManifestEntry {
  readonly importPath: string;
  readonly package: string;
  readonly signature: string;
  readonly symbol: string;
}

function sortedSymbols(values: ReadonlyMap<string, string>): Record<string, string> {
  return Object.fromEntries(
    [...values.entries()].sort(([left], [right]) => left.localeCompare(right)),
  );
}

/**
 * Every published package, its export subpaths, and its public symbols with their signatures. A
 * package whose manifest declares no `exports` map is still recorded, with none: filtering on "has
 * code exports" drops the published native host out of the contract it is published under.
 */
export function deriveApiSurface(root = REPO): IApiSurface {
  const manifestPath = path.join(root, MANIFEST_RELATIVE_PATH);
  if (!existsSync(manifestPath))
    throw new Error(
      `TN_API_SURFACE_MANIFEST_MISSING: ${manifestPath} is the public surface being recorded.`,
    );
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as {
    readonly entries: readonly IManifestEntry[];
  };
  const packages = publicWorkspacePackages(root);
  const published = new Set(packages.map(({ name }) => name));
  const symbols = new Map(packages.map(({ name }) => [name, new Map<string, string>()]));
  for (const entry of manifest.entries) {
    if (!published.has(entry.package)) continue;
    symbols.get(entry.package)?.set(`${entry.importPath}#${entry.symbol}`, entry.signature);
  }
  return {
    packages: Object.fromEntries(
      packages.map(({ exports: subpaths, name }) => [
        name,
        { exports: [...subpaths].sort(), symbols: sortedSymbols(symbols.get(name) ?? new Map()) },
      ]),
    ),
  };
}

/** How a recorded symbol differs from the live one, or not at all. */
function signatureDrift(
  live: IApiSurfacePackage,
  key: string,
  signature: string,
): "changed" | "removed" | undefined {
  const present = live.symbols[key];
  if (present === undefined) return "removed";
  return present === signature ? undefined : "changed";
}

function recordPackageDrift(
  name: string,
  drift: IMutableDrift,
  recorded: IApiSurfacePackage,
  live: IApiSurfacePackage | undefined,
): void {
  if (live === undefined) {
    drift.removedSubpaths.push({ package: name, subpath: "." });
    return;
  }
  for (const subpath of recorded.exports)
    if (!live.exports.includes(subpath)) drift.removedSubpaths.push({ package: name, subpath });
  for (const [key, signature] of Object.entries(recorded.symbols)) {
    const verdict = signatureDrift(live, key, signature);
    if (verdict === undefined) continue;
    const entry = { key: `${name} ${key}`, symbol: key.slice(key.lastIndexOf("#") + 1) };
    if (verdict === "removed") drift.removedSymbols.push(entry);
    else drift.changed.push(entry);
  }
}

/** What a surface dropped or retyped. An addition is a non-event for a consumer on version N. */
export function compareApiSurface(baseline: IApiSurface, current: IApiSurface): IApiSurfaceDrift {
  if (Object.keys(baseline.packages).length === 0)
    throw new Error("TN_API_SURFACE_SNAPSHOT_EMPTY: no published packages are recorded.");
  const drift: IMutableDrift = { changed: [], removedSubpaths: [], removedSymbols: [] };
  for (const name of Object.keys(baseline.packages).sort((left, right) =>
    left.localeCompare(right),
  )) {
    const recorded = baseline.packages[name];
    if (recorded === undefined) continue;
    recordPackageDrift(name, drift, recorded, current.packages[name]);
  }
  return drift;
}

/**
 * Names a `CHANGELOG.md` bullet under `Breaking` can announce: a published package, an exported
 * symbol, or an export subpath such as `./web-brand`. The marker counts in the bullet or in the
 * section heading above it, because a `### Breaking` section is how a changelog states a migration
 * and its bullets are the entries.
 *
 * Only a version section explicitly marked unreleased and carrying no release date is in scope.
 * A changelog with no such section throws instead of treating old notes as announcements.
 */
export function announcedBreakingSymbols(changelog: string): ReadonlySet<string> {
  const names = new Set<string>();
  let inScope = false;
  let inScopeSeen = false;
  let breaking = false;
  let bullet: string[] = [];
  const flush = (): void => {
    const text = bullet.join(" ");
    bullet = [];
    if (!inScope || (!breaking && !/\bBreaking\b/u.test(text))) return;
    for (const match of text.matchAll(IDENTIFIER)) names.add(match[0]);
    for (const match of text.matchAll(MEMBER_PATH)) names.add(match[0]);
    for (const match of text.matchAll(PACKAGE_NAME)) names.add(match[0]);
  };
  for (const line of changelog.split("\n")) {
    if (VERSION_HEADING.test(line)) {
      flush();
      inScope = /\bunreleased\b/iu.test(line) && !RELEASE_DATE.test(line);
      inScopeSeen ||= inScope;
      breaking = /\bBreaking\b/u.test(line);
      continue;
    }
    if (line.startsWith("#")) {
      flush();
      breaking = /\bBreaking\b/u.test(line);
      continue;
    }
    if (BULLET.test(line)) {
      flush();
      bullet = [line];
      continue;
    }
    if (bullet.length === 0 || line.trim().length === 0) {
      flush();
      continue;
    }
    bullet.push(line);
  }
  flush();
  if (!inScopeSeen)
    throw new Error(
      "TN_API_SURFACE_CHANGELOG_SCOPE_MISSING: the changelog has no unreleased version section, so a current `Breaking` entry cannot be told from one that already shipped.",
    );
  return names;
}

/**
 * Whether a `Breaking` entry announces a removed export subpath, as `./navigation` or `navigation`.
 * The root subpath `.` is also how a published package that is gone outright is recorded, and no
 * changelog writes that: a package is announced by its exact name, or not at all.
 */
function subpathAnnounced(announced: ReadonlySet<string>, subpath: string, name: string): boolean {
  if (subpath === ".") return announced.has(name);
  return announced.has(subpath) || announced.has(subpath.replace(/^\.\//u, ""));
}

/** Findings for every removal or signature change the changelog has not announced. */
export function unannouncedBreaks(
  baseline: IApiSurface,
  current: IApiSurface,
  changelog: string,
): readonly string[] {
  const announced = announcedBreakingSymbols(changelog);
  const { changed, removedSubpaths, removedSymbols } = compareApiSurface(baseline, current);
  return [
    ...removedSubpaths
      .filter(({ package: name, subpath }) => !subpathAnnounced(announced, subpath, name))
      .map(
        ({ package: name, subpath }) =>
          `export subpath ${name}${subpath} is gone without a Breaking entry`,
      ),
    ...removedSymbols
      .filter(({ symbol }) => !announced.has(symbol))
      .map(({ key }) => `removed symbol ${key} has no Breaking entry naming it`),
    ...changed
      .filter(({ symbol }) => !announced.has(symbol))
      .map(({ key }) => `changed signature ${key} has no Breaking entry naming it`),
  ];
}

export function apiSurfaceFindings(root = REPO): readonly string[] {
  const snapshotPath = path.join(root, API_SURFACE_RELATIVE_PATH);
  if (!existsSync(snapshotPath))
    throw new Error(
      `TN_API_SURFACE_SNAPSHOT_MISSING: ${snapshotPath} is the contract; run \`pnpm api:surface:sync\` once to record it.`,
    );
  const changelogPath = path.join(root, CHANGELOG_RELATIVE_PATH);
  if (!existsSync(changelogPath))
    throw new Error(
      `TN_API_SURFACE_CHANGELOG_MISSING: ${changelogPath} is where a break is announced.`,
    );
  const baseline = JSON.parse(readFileSync(snapshotPath, "utf8")) as IApiSurface;
  return unannouncedBreaks(baseline, deriveApiSurface(root), readFileSync(changelogPath, "utf8"));
}

function surfaceCounts(surface: IApiSurface): string {
  const symbols = Object.values(surface.packages).reduce(
    (total, item) => total + Object.keys(item.symbols).length,
    0,
  );
  return `${Object.keys(surface.packages).length} published packages, ${symbols} symbols`;
}

function unannouncedBreakMessage(findings: readonly string[]): string {
  return `TN_API_SURFACE_UNANNOUNCED_BREAK:\n${findings.map((finding) => `- ${finding}`).join("\n")}\nName each break in a CHANGELOG.md \`Breaking\` entry, then re-record with \`pnpm api:surface:sync\`.`;
}

/**
 * Re-record the surface. `--update` is the deliberate act, so it refuses while the committed
 * snapshot still shows a break the next release does not announce: without that refusal the one
 * command an author reaches for when the check is red would re-record the removal and silence it,
 * which is how an unannounced removal reaches `develop`.
 */
export function recordApiSurface(root = REPO): IApiSurface {
  const snapshotPath = path.join(root, API_SURFACE_RELATIVE_PATH);
  // A first record has nothing to be compared against; every later one has to earn its write.
  if (existsSync(snapshotPath)) {
    const findings = apiSurfaceFindings(root);
    if (findings.length > 0) throw new Error(unannouncedBreakMessage(findings));
  }
  const surface = deriveApiSurface(root);
  writeFileSync(snapshotPath, `${JSON.stringify(surface, null, 2)}\n`);
  return surface;
}

function main(): void {
  if (process.argv.includes("--update")) {
    console.log(`api surface recorded: ${surfaceCounts(recordApiSurface(REPO))}`);
    return;
  }
  const findings = apiSurfaceFindings(REPO);
  if (findings.length > 0) {
    console.error(unannouncedBreakMessage(findings));
    process.exitCode = 1;
    return;
  }
  console.log(
    `api surface ok: ${surfaceCounts(deriveApiSurface(REPO))}, every removal and signature change announced`,
  );
}

if (
  process.argv[1] &&
  path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname)
) {
  try {
    main();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
