import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Regenerates the shipped capability reference page from `capabilities.json` (PRD-187 phase 4).
 *
 * The template `AGENTS.md` files used to hand-type the symbol inventory — seven copies that
 * rotted on contact with the code. The manifest is the single authored source; this script
 * renders every entry with its summary, situations, constraints, superseded constructs and
 * example into `agent-docs/references/capability-reference.md`, which a scaffolded game reads
 * as a plain file with no MCP server. Run via `pnpm build`; a stale page fails the same way a
 * stale manifest does.
 */

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const MANIFEST_RELATIVE_PATH = path.join("packages", "create-threenative", "capabilities.json");
const TARGET_RELATIVE_PATH = path.join(
  "packages",
  "create-threenative",
  "agent-docs",
  "references",
  "capability-reference.md",
);

interface IManifestEntry {
  readonly constraints: readonly string[];
  readonly example: string;
  readonly importPath: string;
  readonly kind: string;
  readonly overrides: readonly string[];
  readonly package: string;
  readonly signature: string;
  readonly situations: readonly string[];
  readonly summary: string;
  readonly supersedes: readonly string[];
  readonly symbol: string;
}

function inlineCodeList(items: readonly string[]): string {
  const formatted = items.map((item) => `\`${item}\``);
  if (formatted.length <= 1) return formatted[0] ?? "no packages";
  if (formatted.length === 2) return formatted.join(" and ");
  return `${formatted.slice(0, -1).join(", ")}, and ${formatted.at(-1)}`;
}

function bulletList(items: readonly string[], label: string): string[] {
  if (items.length === 0) return [];
  return [`- **${label}:** ${items.join(" · ")}`];
}

function section(entry: IManifestEntry): string {
  const parts = [
    `### \`${entry.symbol}\``,
    "",
    `\`${entry.kind}\` — ${entry.summary}`,
    "",
    "```ts",
    entry.signature,
    "```",
    "",
    ...bulletList(entry.situations, "Use when"),
    ...bulletList(entry.constraints, "Constraints"),
    ...bulletList(entry.supersedes, "Supersedes (writing this fails `pnpm budgets`)"),
    ...bulletList(entry.overrides, "Overrides"),
  ];
  if (entry.example.length > 0) {
    parts.push("", "```ts", entry.example, "```");
  }
  return parts.join("\n");
}

export function renderCapabilityReference(entries: readonly IManifestEntry[]): string {
  const packages = inlineCodeList(
    [...new Set(entries.map((entry) => entry.package))].sort((left, right) =>
      left.localeCompare(right),
    ),
  );
  const byImportPath = new Map<string, IManifestEntry[]>();
  for (const entry of entries) {
    const group = byImportPath.get(entry.importPath) ?? [];
    group.push(entry);
    byImportPath.set(entry.importPath, group);
  }
  const sections = [...byImportPath.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .flatMap(([importPath, group]) => [
      `## \`${importPath}\``,
      "",
      ...group
        .sort((left, right) => left.symbol.localeCompare(right.symbol))
        .flatMap((entry) => [section(entry), ""]),
    ]);
  return [
    "<!-- Generated by scripts/generate-capability-reference.ts from capabilities.json — do not hand-edit. -->",
    "<!-- Regenerate: pnpm build -->",
    "",
    "# Capability reference",
    "",
    `Every public class and function export represented by this manifest across ${packages},`,
    "generated from the doc tags the engine itself compiles, so this page cannot disagree with",
    "the code. Look here before writing a replacement; ask `engine_search_capabilities` when an",
    "MCP server is available.",
    "",
    ...sections,
    "",
  ].join("\n");
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  const manifest = JSON.parse(
    await readFile(path.join(repoRoot, MANIFEST_RELATIVE_PATH), "utf8"),
  ) as { entries: IManifestEntry[] };
  const page = renderCapabilityReference(manifest.entries);
  const target = path.join(repoRoot, TARGET_RELATIVE_PATH);
  if (check) {
    const actual = await readFile(target, "utf8");
    if (actual !== page) {
      console.error(
        `RED observed: ${TARGET_RELATIVE_PATH} disagrees with capabilities.json; run pnpm build`,
      );
      process.exitCode = 1;
      return;
    }
    console.log("capability reference in sync with capabilities.json");
    return;
  }
  await writeFile(target, page);
  console.log(
    `capability reference: ${manifest.entries.length} entries -> ${path.relative(repoRoot, target)}`,
  );
}

if (
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname)
) {
  await main();
}
