import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { PLAYTEST_ASSERTION_REGISTRY } from "../packages/playtest/src/assertion-schema.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const target = path.join(
  repoRoot,
  "packages/playtest/src/scenario/generated-assertion-validators.ts",
);
const checkOnly = process.argv.includes("--check");

function predicate(type: string): string {
  switch (type) {
    case "boolean":
      return 'typeof value === "boolean"';
    case "true":
      return "value === true";
    case "string":
    case "non-empty string":
      return 'typeof value === "string" && value.trim() !== ""';
    case "number":
      return 'typeof value === "number" && Number.isFinite(value)';
    case "positive number":
      return 'typeof value === "number" && Number.isFinite(value) && value > 0';
    case "finite non-negative number":
      return 'typeof value === "number" && Number.isFinite(value) && value >= 0';
    case "positive integer":
      return 'typeof value === "number" && Number.isInteger(value) && value > 0';
    case "non-negative integer":
      return 'typeof value === "number" && Number.isInteger(value) && value >= 0';
    case "non-negative integer 0..6":
      return 'typeof value === "number" && Number.isInteger(value) && value >= 0 && value <= 6';
    case "integer 0..255":
      return 'typeof value === "number" && Number.isInteger(value) && value >= 0 && value <= 255';
    case "number in [0, 180]":
      return 'typeof value === "number" && Number.isFinite(value) && value >= 0 && value <= 180';
    case "triviality reason":
      return 'typeof value === "string" && value.replace(/\\s/gu, "").length >= MIN_TRIVIALITY_REASON_LENGTH';
    case "'browser' or 'native'":
      return 'value === "browser" || value === "native"';
    case "Array<'web' | 'desktop' | 'bevy'>":
      return 'Array.isArray(value) && value.every((item) => item === "web" || item === "desktop" || item === "bevy")';
    case "string[] (minimum 2)":
      return 'Array.isArray(value) && value.length >= 2 && value.every((item) => typeof item === "string" && item.trim() !== "")';
    case "[integer 0..255, integer 0..255, integer 0..255]":
      return 'Array.isArray(value) && value.length === 3 && value.every((item) => typeof item === "number" && Number.isInteger(item) && item >= 0 && item <= 255)';
    case "json":
      return "true";
    case "object":
      return "isRecord(value)";
    default:
      if (type.startsWith("Array<")) return "Array.isArray(value)";
      if (type.startsWith("{") || type.startsWith("static bounds ")) return "isRecord(value)";
      throw new Error(
        `No generated assertion validator predicate for registry type '${type}'. Add an explicit fail-closed mapping before changing the registry.`,
      );
  }
}

const registryEntries = PLAYTEST_ASSERTION_REGISTRY.map((entry) => {
  const fields = entry.fields.map(
    (field) => `    ${JSON.stringify(field.name)}: (value: unknown) => ${predicate(field.type)},`,
  );
  return [`  ${JSON.stringify(entry.kind)}: Object.freeze({`, ...fields, "  }),"].join("\n");
});

const generated = `/* eslint-disable */\n// Generated by scripts/generate-assertion-validators.ts from PLAYTEST_ASSERTION_REGISTRY.\n// Do not hand-edit. Regenerate with: pnpm tsx scripts/generate-assertion-validators.ts\n\nimport { MIN_TRIVIALITY_REASON_LENGTH } from "./schema-base.js";\n\nexport type GeneratedAssertionFieldValidator = (value: unknown) => boolean;\n\nfunction isRecord(value: unknown): value is Record<string, unknown> {\n  return typeof value === "object" && value !== null && !Array.isArray(value);\n}\n\nexport const GENERATED_ASSERTION_FIELD_VALIDATORS: Readonly<Record<string, Readonly<Record<string, GeneratedAssertionFieldValidator>>>> = Object.freeze({\n${registryEntries.join("\n")}\n});\n`;

if (checkOnly) {
  const existing = await readFile(target, "utf8").catch(() => undefined);
  if (existing !== generated) {
    throw new Error(
      "Generated assertion validators are missing or stale. Run `pnpm tsx scripts/generate-assertion-validators.ts` and commit the result.",
    );
  }
  console.log(`assertion validators: ${PLAYTEST_ASSERTION_REGISTRY.length} kinds are current`);
} else {
  await writeFile(target, generated);
  console.log(
    `assertion validators: ${PLAYTEST_ASSERTION_REGISTRY.length} kinds -> ${path.relative(repoRoot, target)}`,
  );
}
