import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { IPlaytestAssertionSchemaEntry } from "../packages/playtest/src/assertion-schema.js";

/**
 * Regenerates the shipped assertion reference page from the live registry.
 *
 * Report §4.1/§4.2: the capability rows agents read are generated, never hand-written —
 * a hand-written completeness claim is the failure mode itself. The registry in
 * `packages/playtest/src/assertion-schema.ts` is the single source; this script renders
 * every kind with its use-when description, fields and example into
 * `packages/create-threenative/agent-docs/references/assertion-reference.md`.
 *
 * Run after adding or changing an assertion kind:
 *   pnpm --filter @threenative/playtest build && pnpm tsx scripts/generate-assertion-reference.ts
 * The doc-drift gate (`packages/playtest/__tests__/doc-drift.spec.ts`) fails when a
 * registry kind appears nowhere in the teaching docs, so a stale page is a red test.
 */

interface IRegistryModule {
  PLAYTEST_ASSERTION_REGISTRY: readonly IPlaytestAssertionSchemaEntry[];
}

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dist = new URL("../packages/playtest/dist/index.js", import.meta.url);

const { PLAYTEST_ASSERTION_REGISTRY } = (await import(dist.href)) as unknown as IRegistryModule;

if (!Array.isArray(PLAYTEST_ASSERTION_REGISTRY) || PLAYTEST_ASSERTION_REGISTRY.length === 0) {
  throw new Error("assertion registry import came back empty — build @threenative/playtest first");
}

function fieldTable(entry: IPlaytestAssertionSchemaEntry): string {
  if (entry.fields.length === 0) return "_No fields._";
  const header = "| Field | Type | Required |\n| --- | --- | --- |";
  const rows = entry.fields.map(
    (field) => `| \`${field.name}\` | ${field.type} | ${field.required === true ? "yes" : "no"} |`,
  );
  return [header, ...rows].join("\n");
}

function exampleBlock(entry: IPlaytestAssertionSchemaEntry): string {
  if (entry.example === undefined) return "";
  return `\n\n\`\`\`json\n${JSON.stringify(entry.example, null, 2)}\n\`\`\``;
}

const sections = PLAYTEST_ASSERTION_REGISTRY.map((entry) => {
  const capabilities =
    entry.requiredCapabilities.length > 0 ? entry.requiredCapabilities.join(", ") : "none";
  const targets = entry.supportedOn.join(", ");
  return [
    `### \`${entry.kind}\``,
    "",
    `${entry.description} **Use when** that is the thing the scenario must prove.`,
    "",
    `- **Supported on:** ${targets} · **Requires:** ${capabilities}`,
    "",
    fieldTable(entry),
    exampleBlock(entry),
  ].join("\n");
});

const page = `<!-- Generated by scripts/generate-assertion-reference.ts from PLAYTEST_ASSERTION_REGISTRY — do not hand-edit. -->
<!-- Regenerate: pnpm --filter @threenative/playtest build && pnpm tsx scripts/generate-assertion-reference.ts -->

# Assertion reference

Every assertion kind the playtest validator accepts, generated from the registry the
validator itself reads, so this page cannot disagree with the runtime. Assertions fail
closed: a malformed assertion throws at load, and a scenario whose assertions all hold
trivially fails \`TN_PLAYTEST_SCENARIO_ASSERTS_NOTHING\`.

${sections.join("\n\n")}
`;

const target = path.join(
  repoRoot,
  "packages/create-threenative/agent-docs/references/assertion-reference.md",
);
await writeFile(target, page);
console.log(
  `assertion reference: ${PLAYTEST_ASSERTION_REGISTRY.length} kinds -> ${path.relative(repoRoot, target)}`,
);
