import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";

import { classifyEvidence } from "./evidence-citations.js";

/**
 * The generated retention index (PRD-323 Phase 2): docs/benchmark/SCREENSHOT-RETENTION.md
 * becomes generated output in the shape the hand-written 2026-08-16 note established — one row
 * per archive directory with its PNG count, bytes and citations — plus the verification-tree
 * summary the hand-written note never had. The header says it is generated, exactly as every
 * CLAUDE.md in this repository does. `--check` regenerates and fails on a hand edit, mirroring
 * `pnpm sync:agents --check`.
 */

const INDEX_PATH = "docs/benchmark/SCREENSHOT-RETENTION.md";

interface IArchiveRow {
  readonly archive: string;
  readonly files: number;
  readonly bytes: number;
  readonly citedBy: readonly string[];
}

function archiveOf(artifactPath: string): string {
  const relative = artifactPath.replace(/^docs\/benchmark\//u, "");
  return relative.includes("/") ? relative.slice(0, relative.indexOf("/")) : relative;
}

async function buildIndex(root: string): Promise<string> {
  const { scan } = await classifyEvidence(root);
  const lines: string[] = [
    "# Screenshot and evidence retention index",
    "",
    "<!-- Generated by scripts/generate-retention-index.ts from the citation scan. Do not",
    "--> <!-- hand-edit: `pnpm budgets` regenerates this file and fails when it drifts, the same",
    "--> <!-- contract as `pnpm sync:agents --check`. -->",
    "",
    "Every artifact under the evidence trees is classified by what cites it (a round ledger, a",
    "done PRD, an open PRD, a script) or `uncited`. Deletion is decided by citation, not age, and",
    "nothing here deletes anything: removal runs only in PRD-323's owner-checkpointed phases.",
    "An artifact the scanner cannot read or place fails the gate rather than defaulting.",
    "",
  ];

  // The index does not measure itself: writing it would change its own byte count, making the
  // next generation disagree with the one on disk. Everything else in the tree is measured.
  const benchmark = scan.filter(
    (artifact) => artifact.path.startsWith("docs/benchmark/") && artifact.path !== INDEX_PATH,
  );
  const archives = new Map<string, { files: number; bytes: number; citedBy: Set<string> }>();
  for (const artifact of benchmark) {
    const archive = archiveOf(artifact.path);
    const entry = archives.get(archive) ?? { bytes: 0, citedBy: new Set<string>(), files: 0 };
    entry.bytes += artifact.bytes;
    entry.files += 1;
    for (const citation of artifact.citedBy) entry.citedBy.add(citation);
    archives.set(archive, entry);
  }
  const verification = scan.filter((artifact) => artifact.path.startsWith("docs/verification/"));
  const verificationBytes = verification.reduce((total, artifact) => total + artifact.bytes, 0);
  const uncited = scan.filter((artifact) => artifact.classification === "uncited");
  const uncitedVerification = verification.filter((a) => a.classification === "uncited");

  lines.push("## Summary", "");
  lines.push("| Tree | Tracked files | Bytes | Uncited |");
  lines.push("|---|---:|---:|---:|");
  lines.push(
    `| \`docs/benchmark\` | ${benchmark.length} | ${benchmark.reduce((total, artifact) => total + artifact.bytes, 0)} | ${benchmark.filter((a) => a.classification === "uncited").length} |`,
  );
  lines.push(
    `| \`docs/verification\` | ${verification.length} | ${verificationBytes} | ${uncitedVerification.length} |`,
  );
  lines.push("");
  if (uncited.length > 0) {
    lines.push(
      `**${uncited.length} artifact(s) are uncited.** Deletion is decided by citation and runs only in PRD-323's owner-checkpointed phases; nothing here removes anything.`,
    );
    lines.push("");
  }

  lines.push("## `docs/benchmark` archive directories", "");
  lines.push("| Archive | Files | Bytes | Cited by |");
  lines.push("|---|---:|---:|---|");
  for (const archive of [...archives.keys()].sort()) {
    const entry = archives.get(archive);
    if (entry === undefined) continue;
    const citations = [...entry.citedBy].sort();
    lines.push(
      `| \`${archive}\` | ${entry.files} | ${entry.bytes} | ${citations.length === 0 ? "—" : citations.join(", ")} |`,
    );
  }
  lines.push("");
  lines.push("## `docs/verification` uncited artifacts", "");
  if (uncitedVerification.length === 0) {
    lines.push("None — every verification artifact carries a citation.");
  } else {
    const listed = uncitedVerification.slice(0, 50);
    lines.push("| Artifact | Bytes |");
    lines.push("|---|---:|");
    for (const artifact of listed) {
      lines.push(`| \`${artifact.path}\` | ${artifact.bytes} |`);
    }
    if (uncitedVerification.length > listed.length) {
      lines.push(`| …and ${uncitedVerification.length - listed.length} more | |`);
    }
  }
  lines.push("");
  return lines.join("\n");
}

async function main(): Promise<void> {
  const root = process.cwd();
  const content = await buildIndex(root);
  const target = path.join(root, INDEX_PATH);
  if (process.argv.includes("--check")) {
    let current: string;
    try {
      current = await readFile(target, "utf8");
    } catch {
      console.error(`retention index is missing at ${INDEX_PATH}; run the generator.`);
      process.exitCode = 1;
      return;
    }
    if (current !== content) {
      console.error(`retention index is stale at ${INDEX_PATH}; regenerate it (do not hand-edit).`);
      process.exitCode = 1;
      return;
    }
    console.log(`retention index fresh: ${INDEX_PATH}`);
    return;
  }
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, content);
  console.log(`retention index generated: ${INDEX_PATH}`);
}

const invokedDirectly =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname);
if (invokedDirectly) {
  void main().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
