// A spruce, built out of ordinary Three.js geometry. Every number here is the game's, and every
// one of them is appearance: the height, how fast the trunk tapers, how many whorls of branches
// there are and how far each one droops. ThreeNative draws it; it decides nothing about it.
//
// The point of this file is that a spruce is not a cone. A cone is a silhouette with no interior,
// no branch, and no trunk under the crown — the rubric calls that out by name, and it is right: a
// cone tree is the shape you get when nobody looked at a tree. What a spruce actually is:
//
//   - a trunk that tapers and leans slightly, and stays visible as bare red-brown bark for the
//     bottom quarter of its height, because that is where a spruce's lowest live branches start;
//   - whorls — rings of branches at a fixed spacing up the trunk, denser and shorter toward the
//     leader, which is the single strongest silhouette cue and the one a stack of cones lacks;
//   - each branch a drooping strip of cards rather than a solid, so the crown has depth, gaps and
//     a silhouette that changes as the camera moves around it.
//
// Cards, not cones: a card is a strip of quads bent along the branch and cut out by alpha, so a
// branch costs a handful of triangles and reads as needles from any angle. The needles themselves
// are `needle-atlas.png`, generated by `scripts/make-needle-atlas.mjs`.
import { createRandom } from "@threenative/core";
import { BufferAttribute, BufferGeometry, Vector3 } from "three";

/** One cell of the needle atlas, in UV. The atlas is 2x2; these are its quadrants. */
export const ATLAS_CELLS = {
  /** Dense whorl card: the branches that build the tree's mass. */
  dense: { u0: 0, v0: 0.5, u1: 0.5, v1: 1 },
  /** Open card: fewer, longer needles, so a crown never reads as one repeated texture. */
  open: { u0: 0.5, v0: 0.5, u1: 1, v1: 1 },
  /** Tip card: short, bright new growth for the leader and the outermost branches. */
  tip: { u0: 0, v0: 0, u1: 0.5, v1: 0.5 },
} as const;

/** How tall a spruce is, and how wide its crown is, in metres. Tall and narrow is the species. */
export const SPRUCE = {
  /** Bare trunk, as a share of total height: a spruce's crown starts about a fifth of the way up. */
  bareTrunk: 0.22,
  /**
   * Whorls up the trunk. This is the number that decides whether a spruce is a tree or a pole with
   * a hat on: at 12 the whorls sit a metre apart on a fourteen-metre trunk and the crown reads as
   * bare sticks with foliage on them.
   */
  whorls: 26,
  /** Branches per whorl at the widest part of the crown. */
  branchesPerWhorl: 8,
  /** Longest branch, as a share of height. A spruce is spire, not sphere. */
  crown: 0.2,
  /** Trunk radius at the base, as a share of height. */
  trunkRadius: 0.021,
} as const;

/**
 * Positions, normals, UVs, the wind envelope and indices, accumulated before one buffer is built.
 *
 * The wind envelope is baked per vertex as a share of the tree's own height rather than read from
 * world Y, because an instanced tree's vertices are shared by every copy of it: a share of the
 * variant's height is the same weight on a tree at the origin and a tree a kilometre away.
 */
class MeshBuffer {
  readonly index: number[] = [];
  readonly normal: number[] = [];
  readonly position: number[] = [];
  readonly sway: number[] = [];
  readonly uv: number[] = [];

  vertex(point: Vector3, normal: Vector3, u: number, v: number, weight: number): number {
    this.position.push(point.x, point.y, point.z);
    this.normal.push(normal.x, normal.y, normal.z);
    this.uv.push(u, v);
    this.sway.push(weight);
    return this.sway.length - 1;
  }

  quad(
    corners: readonly Vector3[],
    normal: Vector3,
    texture: readonly (readonly [number, number])[],
    weight: number,
  ): void {
    const base = this.sway.length;
    corners.forEach((point, i) => {
      const [u, v] = texture[i] as readonly [number, number];
      this.vertex(point, normal, u, v, weight);
    });
    this.index.push(base, base + 1, base + 2, base, base + 2, base + 3);
  }

  build(): BufferGeometry {
    const geometry = new BufferGeometry();
    geometry.setAttribute("position", new BufferAttribute(new Float32Array(this.position), 3));
    geometry.setAttribute("normal", new BufferAttribute(new Float32Array(this.normal), 3));
    geometry.setAttribute("uv", new BufferAttribute(new Float32Array(this.uv), 2));
    geometry.setAttribute("sway", new BufferAttribute(new Float32Array(this.sway), 1));
    geometry.setIndex(this.index);
    geometry.computeBoundingSphere();
    return geometry;
  }
}

/** `value` squared, named so the wind envelope below reads as an expression. */
function envelope(value: number): number {
  return value * value;
}

/**
 * The trunk: a tapered, slightly leaning tube with bark UVs.
 *
 * A cylinder with a constant radius would be a pipe, and a pipe with foliage on it is a lollipop.
 * The taper is what lets the trunk disappear into the crown; the root flare is what stops it
 * looking pushed into the ground rather than grown out of it.
 */
function trunk(height: number, seed: number): BufferGeometry {
  const random = createRandom(seed);
  const sides = 8;
  const rings = 6;
  const base = height * SPRUCE.trunkRadius;
  // Two degrees of lean is enough to break a row of trees without looking blown over.
  const leanX = (random() - 0.5) * 0.07;
  const leanZ = (random() - 0.5) * 0.07;
  const buffer = new MeshBuffer();
  const ring = (level: number, side: number): Vector3 => {
    const level01 = level / rings;
    const angle = (side / sides) * Math.PI * 2;
    const flare = 1 + Math.max(0, 0.55 - level01 * 3.2);
    const radius = base * (1 - level01) ** 0.75 * flare;
    return new Vector3(
      Math.cos(angle) * radius + leanX * envelope(level01) * height,
      level01 * height,
      Math.sin(angle) * radius + leanZ * envelope(level01) * height,
    );
  };
  for (let level = 0; level < rings; level += 1) {
    const v0 = (level / rings) * (height / 1.6);
    const v1 = ((level + 1) / rings) * (height / 1.6);
    const weight = envelope(level / rings);
    for (let side = 0; side < sides; side += 1) {
      const next = (side + 1) % sides;
      const a = ring(level, side);
      const b = ring(level, next);
      const c = ring(level + 1, next);
      const d = ring(level + 1, side);
      const normal = new Vector3()
        .subVectors(c, a)
        .cross(new Vector3().subVectors(b, a))
        .normalize();
      buffer.quad(
        [a, b, c, d],
        normal,
        [
          [side / sides, v0],
          [(side + 1) / sides, v0],
          [(side + 1) / sides, v1],
          [side / sides, v1],
        ],
        weight,
      );
    }
  }
  return buffer.build();
}

/**
 * One branch: a strip of quads that leaves the trunk near-horizontal and droops as it goes out.
 *
 * The card is rolled about its own axis by a seeded angle, because a card that always lies in the
 * horizontal plane disappears when the camera looks along it, and one that always stands vertical
 * reads as a fin. The roll is what makes a crown look like volume from every angle.
 */
function branch(
  buffer: MeshBuffer,
  options: {
    readonly azimuth: number;
    readonly cell: { u0: number; u1: number; v0: number; v1: number };
    readonly droop: number;
    readonly height: number;
    readonly length: number;
    readonly origin: Vector3;
    readonly roll: number;
    readonly segments: number;
    readonly width: number;
  },
): void {
  const { azimuth, cell, droop, height, length, origin, roll, segments, width } = options;
  const outward = new Vector3(Math.cos(azimuth), 0, Math.sin(azimuth));
  const across = new Vector3(-Math.sin(azimuth), 0, Math.cos(azimuth))
    .multiplyScalar(Math.cos(roll))
    .add(new Vector3(0, 1, 0).multiplyScalar(Math.sin(roll)))
    .normalize();
  // A spruce branch is a catenary: it leaves the trunk nearly level and falls away as it goes out.
  const reach = (at: number) => origin.clone().addScaledVector(outward, length * at);
  const drop = (at: number) => droop * length * at * at;
  const halfWidth = (at: number) => (width * (1 - at * 0.82) * Math.min(1, 0.35 + at * 1.6)) / 2;
  for (let i = 0; i < segments; i += 1) {
    const at0 = i / segments;
    const at1 = (i + 1) / segments;
    const a = reach(at0).addScaledVector(across, -halfWidth(at0));
    const b = reach(at0).addScaledVector(across, halfWidth(at0));
    const c = reach(at1).addScaledVector(across, halfWidth(at1));
    const d = reach(at1).addScaledVector(across, -halfWidth(at1));
    const normal = new Vector3().subVectors(b, a).cross(new Vector3().subVectors(d, a)).normalize();
    const u0 = cell.u0 + (cell.u1 - cell.u0) * at0;
    const u1 = cell.u0 + (cell.u1 - cell.u0) * at1;
    buffer.quad(
      [a, b, c, d],
      normal,
      [
        [u0, cell.v0],
        [u0, cell.v1],
        [u1, cell.v1],
        [u1, cell.v0],
      ],
      envelope((origin.y - drop(at0)) / height),
    );
  }
}

/** The whole crown: whorls of branches from the top of the bare trunk to the leader. */
function crown(height: number, seed: number): BufferGeometry {
  const random = createRandom(seed ^ 0x5bf0);
  const buffer = new MeshBuffer();
  for (let w = 0; w < SPRUCE.whorls; w += 1) {
    // Whorls start above the bare trunk and close on the leader, so the last is a handful of short
    // cards rather than a ring.
    const at = SPRUCE.bareTrunk + ((1 - SPRUCE.bareTrunk) * w) / (SPRUCE.whorls - 1);
    // Widest at the bottom of the crown, tapering to a spire. A cone of branches is a fir.
    const taper = (1 - (at - SPRUCE.bareTrunk) / (1 - SPRUCE.bareTrunk)) ** 0.78;
    const length = height * SPRUCE.crown * taper * (0.85 + random() * 0.3);
    const count = Math.max(3, Math.round(SPRUCE.branchesPerWhorl * (0.55 + taper * 0.45)));
    const phase = random() * Math.PI * 2;
    for (let b = 0; b < count; b += 1) {
      // Alternating whorls are rotated against each other so no two neighbouring rings line up
      // into a visible ladder of branches.
      const azimuth = phase + (b / count) * Math.PI * 2 + (w % 2 === 0 ? 0 : Math.PI / count);
      branch(buffer, {
        azimuth,
        cell:
          w === SPRUCE.whorls - 1
            ? ATLAS_CELLS.tip
            : b % 3 === 0
              ? ATLAS_CELLS.open
              : ATLAS_CELLS.dense,
        // Lower branches hang hardest; the leader's barely fall at all.
        droop: 0.22 + taper * 0.5 + random() * 0.12,
        height,
        length,
        origin: new Vector3(0, at * height, 0),
        roll: (random() - 0.5) * 1.5,
        segments: 3,
        width: length * (0.72 + random() * 0.2),
      });
    }
  }
  return buffer.build();
}

/** One seeded spruce variant: a tapered trunk and its crown, as two buffers and a draw each. */
export interface ISpruceVariant {
  readonly crown: BufferGeometry;
  readonly height: number;
  readonly trunk: BufferGeometry;
}

/**
 * Build `count` bounded spruce variants from one seed.
 *
 * Each variant is a different height and crown proportion, which is the whole of "2-3 size/shape
 * variants": a forest of three shapes scattered by seed reads as a forest, and a forest of one shape
 * reads as a repeated asset no matter how good that shape is.
 */
export function spruceVariants(count: number, seed: number): ISpruceVariant[] {
  if (!Number.isInteger(count) || count < 1)
    throw new Error(`Spruce variant count must be a positive integer, received ${count}.`);
  const random = createRandom(seed);
  return Array.from({ length: count }, () => {
    const height = 12 + random() * 5;
    const variantSeed = (random() * 0xffffffff) >>> 0;
    return {
      crown: crown(height, variantSeed),
      height,
      trunk: trunk(height, variantSeed),
    };
  });
}
