import type { Recording } from "@threenative/core";

// Generated by capture-browser-recording.mjs from a running browser consumer.
export const browserRecording = {
  randomState: 90210,
  runtime: {
    agent:
      "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36",
    core: "0.1.0",
    portable: true,
    rapier: null,
    step: 0.016666666666666666,
  },
  seed: 90210,
  version: 1,
  input: [
    {
      keys: ["KeyD"],
      tick: 0,
    },
    {
      keys: [],
      tick: 12,
    },
  ],
  ticks: 24,
} satisfies Recording;
export const browserRecordingSha256 =
  "df52b648947cdb6e5cd60b650d9db55f9dd9bae9b7ce4c393ccb08d49424dff9";
