import type { Recording } from "@threenative/core";

// Generated by capture-browser-recording.mjs from a running browser consumer.
export const browserRecording = {
  randomState: 90210,
  runtime: {
    agent:
      "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36",
    core: "0.2.0",
    portable: true,
    rapier: null,
    step: 0.016666666666666666,
  },
  seed: 90210,
  version: 1,
  input: [
    {
      keys: ["KeyD"],
      tick: 0,
    },
    {
      keys: [],
      tick: 12,
    },
  ],
  ticks: 24,
} satisfies Recording;
export const browserRecordingSha256 =
  "0d69a76e6b158d9fd7727a1d1e40bcdcfb3d373e9e5f8bf69614385dd45453e2";
