// Generated by capture-vanilla-recording.mjs from the running plain-Three.js control arm.
export const vanillaBrowserRecording = {
  input: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
  liveHash: 3305283306,
  replayHash: 3305283306,
};
export const vanillaBrowserRecordingSha256 =
  "523f97e09298621eff54ff7458cbafc0b9a669cf0b2e3a195959a22427207713";
