/**
 * Records packages/core/src/static-transform.ts over three@<pin> as a C++ table the native test
 * compares against (PRD-519): one scripted scenario, and after every step each node's local and
 * world matrix (bits), its three update flags, isStatic and the census. The native test runs the
 * same steps on the native scene graph with the native registry.
 *
 *   pnpm --workspace-root exec tsx packages/runtime-native/tests/native-engine/scene/static-transform-reference.ts
 *   ... -- --check   (fails when the committed table is not what static-transform.ts produces)
 */

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Object3D } from "three";

import {
  invalidateStatic,
  isStatic,
  markStatic,
  refreshStaticTransforms,
  resetStaticTransforms,
  staticTransformCensus,
  unmarkStatic,
} from "../../../../core/src/static-transform.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(HERE, "static_transform_reference.inc");

const bits = (x: number) => {
  const words = new Uint32Array(new Float64Array([x]).buffer);
  return ((BigInt(words[1] as number) << 32n) | BigInt(words[0] as number))
    .toString(16)
    .padStart(16, "0");
};
const named = (name: string) => Object.assign(new Object3D(), { name });
const scene = named("scene");
const a = named("a");
const b = named("b");
const c = named("c");
const d = named("d");
const e = named("e");
const f = named("f");
scene.add(a, d, f);
a.add(b);
b.add(c);
d.add(e);
a.position.set(1, 2, 3);
a.rotation.set(0.3, 0.2, 0.1);
a.scale.set(2, 1, 0.5);
b.position.set(0, 1, 0);
b.rotation.set(0, 0.7, 0);
c.position.set(0.5, 0, -1);
d.position.set(-4, 0, 0);
e.position.set(0, 0, 2);
f.position.set(0, -3, 0);
const NODES = [scene, a, b, c, d, e, f];

const flag = (x: boolean) => (x ? 1 : 0);
const steps: string[] = [];
const observe = (label: string, result: string) => {
  const census = staticTransformCensus();
  const nodes = NODES.map(
    (o) =>
      `${o.name}:m=${o.matrix.elements.map(bits).join(",")};w=${o.matrixWorld.elements.map(bits).join(",")};` +
      `au=${flag(o.matrixAutoUpdate)};wau=${flag(o.matrixWorldAutoUpdate)};wnu=${flag(o.matrixWorldNeedsUpdate)};s=${flag(isStatic(o))}`,
  );
  steps.push(
    [
      label,
      `r=${result}`,
      ...nodes,
      `census=${census.roots},${census.objects},${census.rearmed}`,
    ].join("|"),
  );
};

scene.updateMatrixWorld();
observe("initial", "-");
observe("mark-a", String(markStatic(a)));
b.position.x += 1; // a deep write nobody announces: the frozen subtree keeps its matrices
scene.updateMatrixWorld();
observe("deep-write-unannounced", "-");
const v = invalidateStatic(c); // announced from a grandchild: the root re-arms
scene.updateMatrixWorld();
observe("invalidate-from-grandchild", String(v));
a.position.y += 0.5; // the root itself moved: refresh re-arms it
refreshStaticTransforms();
scene.updateMatrixWorld();
observe("root-moved-refresh", "-");
refreshStaticTransforms(); // nothing moved: nothing re-arms
observe("refresh-still", "-");
a.position.z = 9;
scene.updateMatrixWorld(true); // an explicit forced walk while frozen and unrefreshed
observe("forced-walk-while-frozen", "-");
e.matrixAutoUpdate = false; // the game owns e's matrix before the freeze
observe("mark-d", String(markStatic(d)));
observe("mark-d-again", String(markStatic(d)));
unmarkStatic(d);
scene.updateMatrixWorld();
observe("unmark-d", "-");
observe("invalidate-outside", String(invalidateStatic(f)));
unmarkStatic(a);
scene.updateMatrixWorld();
observe("unmark-a", "-");
markStatic(a);
resetStaticTransforms();
observe("reset", "-");

const cString = (s: string) => JSON.stringify(s);
const text = [
  "// Generated by packages/runtime-native/tests/native-engine/scene/static-transform-reference.ts.",
  "// Do not edit: rerun the generator. Matrix elements are their 16 hex digits of bits.",
  "static const char* const kSteps[] = {",
  ...steps.map((s) => `    ${cString(s)},`),
  "};",
  "",
].join("\n");
if (process.argv.includes("--check")) {
  if (readFileSync(OUT, "utf8") !== text) {
    console.error(
      `TN_FIXTURE_STALE: ${path.relative(process.cwd(), OUT)} is not what static-transform.ts produces`,
    );
    process.exit(1);
  }
  console.log(`current: ${steps.length} steps`);
} else {
  writeFileSync(OUT, text);
  console.log(`wrote ${steps.length} steps`);
}
