// Generate one tiny native project per measurement arm.
//
// The projects are the crate's own bench HUD (`packages/runtime-native/native/css-ui/examples/bench.rs`:
// 100 rows of (1 row + 9 cells) = 1,000 elements, text in every cell, classes row/cell/hot) over the
// example's cube scene, wired the way `corpus/project.mjs` wires a fixture: a native entry that
// mounts the tree through `createCssUiRoot()`, and a plain stylesheet imported by `src/ui/main.tsx`
// so Vite emits the sheet the engine resolves.
//
// Everything written here is build output. It lives under `bench/out/<arm>/dist/` on purpose: the
// repo's Biome config ignores `dist/`, and a generated project is a mirror of a page, not
// application code — the same reason `corpus/desktop.mjs` nests its projects there.
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/** The arms, and the host each one is packaged against. `ui-off` never stages a UI at all. */
export const ARMS = {
  "ui-off": {
    renderer: "native",
    host: "tn-linux",
    mode: "none",
    note: 'the same cube game with no UI module and ui.renderer "native": no overlay, no UI bundle, no second process',
  },
  "native-css-static": {
    renderer: "native-css",
    host: "tn-linux",
    mode: "static",
    note: "1,000-node HUD, rendered once and never touched again",
  },
  "native-css-10pct": {
    renderer: "native-css",
    host: "tn-linux",
    mode: "10pct",
    note: "90 of the 900 cell texts (10%) change value every 6th frame",
  },
  "native-css-active": {
    renderer: "native-css",
    host: "tn-linux",
    mode: "active",
    note: "a 4 s background-color transition on those same 90 cells, re-triggered every 30 frames",
  },
  "web-overlay": {
    renderer: "web",
    host: "tn-linux-both",
    mode: "static",
    page: true,
    note: "the same HUD through react-dom on the both-backends host (static: an A/B for the static arm)",
  },
};

/**
 * The stylesheet, one byte-identical sheet for every arm so the arms differ only in what changes.
 *
 * The first three rules are the crate bench's own sheet. The transition is the active arm's: the
 * engine keeps repainting while a transition runs (`CssUi::render` returns early only when nothing
 * is dirty *and* no transition is in flight), so a long duration re-triggered every 30 frames makes
 * the repaint-per-frame case continuous instead of a 2 Hz flip. Inert in the other arms, which
 * never change a class.
 */
const CSS = `.row{display:flex;gap:4px;margin:2px 8px}
.cell{width:60px;height:14px;background:#334155;color:#e2e8f0;font-size:10px;overflow:hidden;transition:background-color 4000ms linear}
.hot{background:#2563eb}
`;

/** The crate's bench HUD as React: the same elements, the same classes, the same text density. */
const HUD_TSX = `/**
 * GENERATED by bench/project.mjs — do not edit.
 *
 * The crate's own bench HUD (packages/runtime-native/native/css-ui/examples/bench.rs), as React:
 * 100 rows of (1 row + 9 cells) = 1,000 elements with text in every cell and the classes
 * row/cell/hot. A fragment, not a wrapper, so the element count is exactly the crate's.
 */
const ROWS = 100;
const COLS = 9;
/** Every tenth cell: 90 of the 900 texts, and 90 of the 1,000 elements. The PRD's 10%. */
const TENTH = 10;

/**
 * @param kick  increments once per mutation burst; rewrites the text of the 90 tenth cells, so
 *              exactly 10% of the texts differ from the previous commit and 90% of the tree is
 *              byte-identical to it.
 * @param phase increments once per mutation burst in the active arm; flips \`hot\` on those same
 *              90 cells, and the sheet's transition is what keeps painting between the flips.
 */
export function Hud({ kick, phase }: { kick: number; phase: number }): React.ReactElement {
  const rows = [];
  for (let r = 0; r < ROWS; r += 1) {
    const cells = [];
    for (let c = 0; c < COLS; c += 1) {
      const tenth = (r * COLS + c) % TENTH === 0;
      const text = tenth ? \`r\${r}c\${c}#\${kick}\` : \`r\${r}c\${c}\`;
      const hot = tenth && phase % 2 === 1;
      cells.push(<div key={c} className={hot ? "cell hot" : "cell"}>{text}</div>);
    }
    rows.push(<div key={r} className="row">{cells}</div>);
  }
  return <>{rows}</>;
}
`;

const GAME_TS = (warmup, measured) => `/**
 * GENERATED by bench/project.mjs — do not edit.
 *
 * The example's cube scene, unchanged, plus the bench's own evidence: one line a second carrying
 * the frame count and whatever the HUD has published. \`posts\`/\`ops\` are the React root's counters
 * (-1 on the ui-off arm, which has no root), so a run that mounted no UI says so in its own log
 * instead of reading as one that painted nothing.
 */
import { type ICtx, Scene, defineGame } from "@threenative/core";
import { BoxGeometry, Color, Mesh, MeshStandardMaterial, PointLight } from "three";

/** The PRD's run shape, baked in so the log can be joined to the plan that asked for it. */
export const PLAN = { warmup: ${warmup}, measured: ${measured} };

export type BenchState = { frames: number };

/**
 * The one seam between the game's frame loop and the HUD.
 *
 * \`corpus/project.mjs\` runs its click ledger the other way — the UI calls into the game's store —
 * because a click originates in the UI. A dirty-frames arm originates in the game, so the game
 * calls the UI here instead, through a module-level sink that keeps \`game.ts\` and \`native.tsx\`
 * free of an import cycle.
 */
export const bench: {
  onFrame?: (frame: number) => void;
  report?: () => { posts: number; ops: number; mutations: number };
} = {};

declare global {
  var canvas: HTMLCanvasElement | undefined;
}

const hostCanvas = globalThis.canvas;

class Cube extends Scene<BenchState> {
  static override readonly initialState: BenchState = { frames: 0 };

  override enter(ctx: ICtx<BenchState>) {
    ctx.scene.background = new Color(0x18181b);
    ctx.camera.position.set(2, 2, 3);
    ctx.camera.lookAt(0, 0, 0);
    const light = ctx.add(new PointLight(0xffffff, 40));
    light.position.set(4, 6, 8);
    const cube = ctx.add(new Mesh(new BoxGeometry(1, 1, 1), new MeshStandardMaterial()));
    return (frameCtx: ICtx<BenchState>, dt: number) => {
      cube.rotation.x += dt * 0.6;
      cube.rotation.y += dt;
      const frames = frameCtx.state.getState().frames + 1;
      // Zero-based, so \`frame % 6 === 0\` is the crate's cadence read from the game's own count.
      bench.onFrame?.(frames - 1);
      if (frames % 60 === 0) {
        const ui = bench.report?.();
        console.log(
          \`TN_BENCH:\${JSON.stringify({
            frames,
            posts: ui?.posts ?? -1,
            ops: ui?.ops ?? -1,
            mutations: ui?.mutations ?? -1,
          })}\`,
        );
      }
      frameCtx.state.set({ frames });
    };
  }
}

const game: ReturnType<typeof defineGame<BenchState>> = defineGame<BenchState>({
  canvas: hostCanvas,
  inputTarget: hostCanvas,
  scenes: { cube: Cube },
  start: "cube",
});

export default game;
`;

/** The ui-off arm: no UI module, no root, no second renderer. The game is the whole bundle. */
const NATIVE_TS_UI_OFF = `/**
 * GENERATED by bench/project.mjs — do not edit.
 *
 * No \`react-css\` import and no stylesheet: this is the opted-out configuration the PRD asks to be
 * measured against, and its cost is the cost of the game alone.
 */
import game from "./game.js";

export default game;
`;

/**
 * The native-css entry, one mutation policy per arm.
 *
 * `static` renders exactly once for the whole run, so its `postCount` stays at 1 whatever else the
 * host does — the observable half of "an unchanged UI performs no repeated reconciliation". The
 * other two re-render from the game's frame callback through the root's own `render()`, which is
 * the path `corpus/project.mjs` uses and the only one that reaches React's diff.
 */
const NATIVE_TSX = (mode) => {
  const policy = {
    static: `// Nothing is posted after the mount below. Every later frame is measured on this.
bench.onFrame = () => {};`,
    "10pct": `// The crate's cadence: 10% of the texts change every 6th frame, 10 Hz at 60 Hz.
bench.onFrame = (frame) => {
  if (frame % 6 !== 0) return;
  kick += 1;
  mutations += 90;
  root.render(<Hud kick={kick} phase={0} />);
};`,
    active: `// A transition, re-triggered every 30 frames and left running for 4 s, so the engine is
// repainting every frame between the flips rather than only on them.
bench.onFrame = (frame) => {
  if (frame % 30 !== 0) return;
  phase += 1;
  mutations += 90;
  root.render(<Hud kick={0} phase={phase} />);
};`,
  }[mode];
  return `/**
 * GENERATED by bench/project.mjs — do not edit.
 *
 * The React root, mounted once and re-rendered only when this arm says something changed.
 */
import { createCssUiRoot } from "@threenative/core/react-css";
import game, { bench } from "./game.js";
import { Hud } from "./ui/Hud.js";

const root = createCssUiRoot();
let kick = 0;
let phase = 0;
let mutations = 0;

root.render(<Hud kick={0} phase={0} />);

${policy}

bench.report = () => ({ posts: root.postCount, ops: root.opCount, mutations });

export default game;
`;
};

const MAIN_TSX_CSS = `/**
 * GENERATED by bench/project.mjs — do not edit.
 *
 * The stylesheet entry, and nothing else: importing the sheet is what makes the native build emit
 * the stylesheet the CSS engine resolves. The tree is mounted by \`src/native.tsx\`, in the game's
 * own JS realm.
 */
import "./hud.css";

export {};
`;

const MAIN_TSX_WEB = `/**
 * GENERATED by bench/project.mjs — do not edit.
 *
 * The web overlay's page: react-dom into the host's own \`#tn-ui\`, mounting the same \`Hud\` and the
 * same stylesheet the native-css arms mount. This is the comparison arm, so the tree and the sheet
 * must be the same bytes on both sides.
 */
import { UI_READY_INTENT, connectUiBridge, sendUiIntent } from "@threenative/core/ui-layer";
import { createRoot } from "react-dom/client";
import { Hud } from "./Hud.js";
import "./hud.css";

const host = document.getElementById("tn-ui");
if (host === null) throw new Error("TN_BENCH_UI_ROOT_MISSING: the overlay page has no #tn-ui");
const bridge = connectUiBridge({ end: "ui" });
createRoot(host).render(<Hud kick={0} phase={0} />);

// The overlay's readiness contract, through the engine's own seam: the page says its tree is on
// screen, or the host's 15-second deadline shuts the run down with TN_UI_LOAD_FAILED. This is the
// same intent @threenative/ui's <UiLayer> sends, from the same rAF, once the first frame is up.
requestAnimationFrame(() => sendUiIntent(bridge, UI_READY_INTENT, 0));
`;

const CONFIG_TS = (name, renderer) => `import type { IThreeNativeConfig } from "@threenative/core";

/**
 * GENERATED by bench/project.mjs — do not edit.
 *
 * 1280x720 at dpr 1, the size the crate's bench rasters at, so the host's UI surface is the same
 * one the engine-level numbers were taken at.
 */
const config: IThreeNativeConfig = {
  app: {
    id: "com.threenative.bench.${name.replaceAll(/-/gu, "")}",
    name: "tn-bench-${name}",
    version: "1.0.0",
    build: 1,
  },
  display: { orientation: "landscape" },
  window: { width: 1280, height: 720 },
  nativeEntry: "src/native.tsx",
  ui: { renderer: "${renderer}" },
};

export default config;
`;

const VITE_TS = `import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

/** GENERATED by bench/project.mjs — the React plugin only: this arm's sheet is plain CSS. */
export default defineConfig({
  plugins: [react()],
});
`;

/**
 * Write one arm's project under `dir`, replacing whatever was there.
 *
 * `warmup`/`measured` are the PRD's run shape and are baked into the game so its own log can be
 * joined to the plan; the driver holds the same numbers.
 */
export function writeProject(dir, arm, { warmup = 120, measured = 1000 } = {}) {
  const spec = ARMS[arm];
  const write = (relative, contents) => {
    rmSync(join(dir, relative), { force: true });
    writeFileSync(join(dir, relative), contents);
  };
  mkdirSync(join(dir, "src", "ui"), { recursive: true });

  write(
    "package.json",
    `${JSON.stringify({ name: `tn-bench-${arm.replaceAll(/-/gu, "")}`, version: "0.0.0", private: true, type: "module" }, null, 2)}\n`,
  );
  write("threenative.config.ts", CONFIG_TS(arm, spec.renderer));
  write("vite.config.ts", VITE_TS);
  write("src/game.ts", GAME_TS(warmup, measured));
  if (spec.mode !== "none") {
    write("src/ui/Hud.tsx", HUD_TSX);
    write("src/ui/hud.css", CSS);
    write("src/ui/main.tsx", spec.page === true ? MAIN_TSX_WEB : MAIN_TSX_CSS);
  }
  write("src/native.tsx", spec.mode === "none" ? NATIVE_TS_UI_OFF : NATIVE_TSX(spec.mode));
  return dir;
}
